❗ **Note:** Each open-source model must be run in a new session due to RAM limitations. A minimum of an **A100 40GB GPU** is recommended, though 20GB may be sufficient for running GPT-OSS-20B and Gemma-3-12B.

# Imports + Data

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found

In [ ]:
!pip install anthropic

Requirement already satisfied: anthropic in /usr/local/lib/python3.12/dist-packages (0.68.1)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from anthropic) (4.10.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from anthropic) (1.9.0)
Requirement already satisfied: docstring-parser<1,>=0.15 in /usr/local/lib/python3.12/dist-packages (from anthropic) (0.17.0)
Requirement already satisfied: httpx<1,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from anthropic) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from anthropic) (0.11.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from anthropic) (2.11.9)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from anthropic) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.10 in /usr/local/lib/python3.12/dist-packages (from anthropic) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->anthropic) (3.10)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->anthropic) (2025.8.3)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->anthropic) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.25.0->anthropic) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->anthropic) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->anthropic) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->anthropic) (0.4.1)

In [ ]:
!pip install llama-cpp-python \
  --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu124

Looking in indexes: https://pypi.org/simple, https://abetlen.github.io/llama-cpp-python/whl/cu124
Collecting llama-cpp-python
  Downloading https://github.com/abetlen/llama-cpp-python/releases/download/v0.3.16-cu124/llama_cpp_python-0.3.16-cp312-cp312-linux_x86_64.whl (551.3 MB)
     ━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.6/551.3 MB 11.2 MB/s eta 0:00:41
ERROR: Operation cancelled by user

In [ ]:
!pip install json5

Requirement already satisfied: json5 in /usr/local/lib/python3.12/dist-packages (0.12.1)

In [ ]:
from huggingface_hub import login
# from llama_cpp import Llama
import torch
import os
import re
import ast
import pandas as pd
import openai
from openai import OpenAI
from time import sleep
from concurrent.futures import ThreadPoolExecutor, as_completed
import threading
import math
import random
from google import genai
from google.genai import types
import tiktoken
from anthropic import Anthropic
from requests.exceptions import ConnectionError, Timeout, RequestException
from google.api_core import exceptions as gcore_exceptions
import json
import json5
from collections import Counter

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Load CSV file
folder_path = "/content/drive/MyDrive/World Bank/Metanorms/"
df = pd.read_csv(folder_path+"rotexamples_07072025.csv")
# df = pd.read_csv(folder_path+"rotexamples_07072025_genders.csv")

In [ ]:
# Set up API keys
gpt_key = "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"
claude_key = "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"
gemini_key="AIzaSyCWYX-moP7KD2tB5r7XxUjPXN1LWqac97A" # tier 1
hf_key = "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"

In [ ]:
login(hf_key)

# Data Format Change

In [ ]:
df

,situation-short-id,situation,rule-of-thumb (rot),rot-moral-foundations,rot-judgement,action,ID,MFT,stimuli-male,norm-target in stimuli-male,male,stimuli-female,norm-target in stimuli-female,gender,rot-agree,action-agree,action-pressure,action-hypothetical
0,reddit/amitheasshole/avxz68,not telling someone's girlfriend that he cheat...,It's good to speak up when someone's doing som...,care-harm,it is good,speaking up when someone's doing something har...,1,care-harm,William did not tell someone's girlfriend that...,William,male,Maria did not tell someone's girlfriend that h...,Maria,female,4,4,2,explicit-no
1,reddit/amitheasshole/alg2n1,rarely talking with my elderly roomates,It's good to create a friendly atmosphere when...,care-harm,it is good,creating a friendly atmosphere when you have r...,2,care-harm,John rarely talks to his elderly roommates and...,John,male,Mary rarely talks to her elderly roommates and...,Mary,female,3,3,1,explicit-no
2,reddit/amitheasshole/alv89u,getting upset/annoyed with my boyfriend for st...,It's inconsiderate to assume that your partner...,care-harm,it is inconsiderate,assumimg that your partner was not trying to s...,3,care-harm,Robert stayed up until 5 am because he assumed...,Robert,male,Barbara stayed up until 5 am because she assum...,Barbara,female,3,2,0,hypothetical
3,reddit/amitheasshole/a4l295,not listening to her about my health,You should take care of your health.,care-harm,should,taking care of your health.,4,care-harm,David does not listen to his girlfriend about ...,David,male,Jennifer does not listen to her boyfriend abou...,Jennifer,female,4,4,1,hypothetical
4,reddit/amitheasshole/atksbr,preventing my roommate from getting a new dog ...,You should grieve your dead pet before getting...,care-harm,you should,grieving your dead pet before getting a new on...,5,care-harm,Thomas did not grieve his dead dog before gett...,Thomas,male,Mary did not grieve her dead dog before gettin...,Mary,female,2,2,0,probable-no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446,reddit/confessions/4vjr2z,I peed in the bathtub.,It's embarrassing to admit that you pee in the...,sanctity-degradation,it is embarrassing,admitting that you pee in the bathtub or shower.,447,sancticity-degradation,William peed in the bathtub.,William,male,Karen peed in the bathtub.,Karen,female,3,3,-1,explicit
447,reddit/confessions/b7vlw9,I sniffed my sister's spent tampons,It's vile to lick the blood off a spent tampon.,sanctity-degradation,it is vile,licking the blood off a spent tampon,448,sancticity-degradation,David sniffed and licked his sister's used tam...,David,male,Patricia sniffed and licked her sister's used ...,Patricia,female,4,4,-2,explicit-no
448,reddit/confessions/b3565z,I read things in a British accent even though ...,You shouldn't fake an accent because it's esse...,sanctity-degradation,you should not,faking an accent and lying to people.,449,sancticity-degradation,Richard reads things in a British accent even ...,Richard,male,Jennifer reads things in a British accent even...,Jennifer,female,2,2,-1,explicit
449,reddit/confessions/daw9hk,I touched a passed out girl inappropriately,It's wrong to touch unconscious people.,sanctity-degradation,it is wrong,touching unconscious people.,450,sancticity-degradation,Charles touched a passed-out girl inappropriat...,Charles,male,Elizabeth touched a passed-out guy inappropria...,Elizabeth,female,4,4,-2,explicit
450,reddit/confessions/b7rwxw,I smell my socks and underwear every time I ta...,It's odd to smell your own clothes after weari...,sanctity-degradation,it is odd,smelling your own clothes after wearing them.,451,sancticity-degradation,David smells his socks and underwear every tim...,David,male,Linda smells her socks and underwear every tim...,Linda,female,2,2,0,explicit

In [ ]:
actor_names = [
    'William','Maria','John','Mary','Robert','Barbara','David',
    'Jennifer','Thomas','Mark','Linda','James','Patricia','Karen',
    'Michael','Charles','Susan','Elizabeth','Lisa','Richard'
]

def transform_text(stimuli_text, norm_target, gender):
    subj = "A man" if gender == "male" else "A woman"
    target = "the man" if gender == "male" else "the woman"
    child = "his son" if gender == "male" else "her daughter"
    pronoun = "him" if gender == "male" else "her"

    # --- CASE 1: dad/mom ---
    if re.search(r"\b(dad|mom)\b", norm_target, flags=re.IGNORECASE):
        stimuli_text = re.sub(r"^[A-Z][a-z]+['’]s (dad|mom)", subj, stimuli_text, flags=re.IGNORECASE)
        stimuli_text = re.sub(r"\b(" + "|".join(actor_names) + r")\b", child, stimuli_text)
        stimuli_text = re.sub(r"\s+", " ", stimuli_text).strip()
        norm_target = target
        return stimuli_text, norm_target

    # --- CASE 2: parents/family/in-laws ---
    if any(word in norm_target.lower() for word in ["parents", "family", "in-laws"]):
        stimuli_text = re.sub(r"^[A-Z][a-z]+", subj, stimuli_text, count=1)
        stimuli_text = re.sub(r"\b(" + "|".join(actor_names) + r")\b", pronoun, stimuli_text)
        stimuli_text = re.sub(rf"{subj}{subj}'s", f"{subj}'s", stimuli_text)
        norm_target = re.sub(r"^[A-Z][a-z]+", target, norm_target, count=1)
        return stimuli_text, norm_target

    # --- CASE 3: generic case ---
    stimuli_text = re.sub(r"^[A-Z][a-z]+", subj, stimuli_text, count=1)
    stimuli_text = re.sub(r"\b(" + "|".join(actor_names) + r")\b", pronoun, stimuli_text)
    norm_target = target
    return stimuli_text, norm_target

# apply transformations
df[["stimuli-male", "norm-target in stimuli-male"]] = df.apply(
    lambda row: transform_text(row["stimuli-male"], row["norm-target in stimuli-male"], "male"),
    axis=1, result_type="expand"
)

df[["stimuli-female", "norm-target in stimuli-female"]] = df.apply(
    lambda row: transform_text(row["stimuli-female"], row["norm-target in stimuli-female"], "female"),
    axis=1, result_type="expand"
)

# save updated file
df.to_csv(folder_path+"rotexamples_07072025_genders.csv", index=False)

# Survey Structure

Moral Emotions: https://pages.stern.nyu.edu/~jhaidt/articles/alternate_versions/haidt.2003.the-moral-emotions.pub025-as-html.html

## Choices

In [ ]:
# Define choice lists with numeric anchors
EMOTIONS = [
    "Contempt", "Anger", "Disgust",
    "Shame", "Embarrassment", "Guilt",
    "Compassion", "Pride",
    "Other", "No emotion"
]

STRENGTHS = [
    "1 = A little", "2 = Moderate", "3 = A lot", "4 = Extremely"
]

ACTIONS = [
    "1 = Do nothing",
    "2 = Stay away or keep a distance from the actor",
    "3 = Gossip about / discuss with / complain to others informally",
    "4 = Verbal reprimand / verbal confrontation",
    "5 = Physical confrontation", # isn't present in results for GPT
    "6 = Inform the authorities, such as the police",
    "7 = Support the actor",
    "8 = Celebrate / praise"
]

APPROPRIATENESS = [
    "1 = Not at all inappropriate",
    "2 = Somewhat inappropriate",
    "3 = Inappropriate",
    "4 = Very inappropriate",
    "5 = Extremely inappropriate"
]

WRONGNESS = [
    "1 = Not at all wrong",
    "2 = Somewhat wrong",
    "3 = Wrong",
    "4 = Very wrong",
    "5 = Extremely wrong"
]

Definitions below are sourced from [APA Dictionary](https://dictionary.apa.org).

In [ ]:
# Short definitions
MORAL_EMOTIONS_DEFS = """
Available emotions with definitions:
- Contempt: an emotion characterized by negative regard for anything or anybody considered to be inferior, vile, or worthless.
- Anger: an emotion characterized by tension and hostility arising from frustration, real or imagined injury by another, or perceived injustice.
- Disgust: a strong aversion, for example, to the taste, smell, or touch of something deemed revolting, or toward a person or behavior deemed morally repugnant.
- Shame: a highly unpleasant self-conscious emotion arising from the sense of there being something dishonorable, immodest, or indecorous in one’s own conduct or circumstances.
- Embarrassment: a self-conscious emotion in which a person feels awkward or flustered in other people’s company or because of the attention of others, as, for example, when being observed engaging in actions that are subject to mild disapproval from others.
- Guilt: a self-conscious emotion characterized by a painful appraisal of having done (or thought) something that is wrong and often by a readiness to take action designed to undo or mitigate this wrong.
- Compassion: a strong feeling of sympathy with another person’s feelings of sorrow or distress, usually involving a desire to help or comfort that person.
- Pride: a self-conscious emotion that occurs when a goal has been attained and one’s achievement has been recognized and approved by others.
- Other: any emotion not listed above.
- No emotion: indicates absence of emotional response.
"""

## Questions

In [ ]:
QUESTION_TEXTS = {
    # Actor
    1: (
        "1) How would {actor} feel about their action? "
        "(select emotions from the list; if not listed, add them under 'other_emotions'; "
        "if 'No emotion', it must be the ONLY choice): "
        + ", ".join(EMOTIONS[:-1])
        + "\n\n" + MORAL_EMOTIONS_DEFS
    ),
    2: "2) For each selected emotion (including any in 'other_emotions'), how strongly would {actor} feel it? (choose one; if 'No emotion' was selected in Q1, answer = null/NaN): " + ", ".join(STRENGTHS),

    # Close friends or relatives
    3: (
        "3) Suppose {actor}'s close friends or relatives observed the action. "
        "How would they feel? (select emotions from the list; if not listed, add them under 'other_emotions'; "
        "if 'No emotion', it must be the ONLY choice): "
        + ", ".join(EMOTIONS[:-1])
        + "\n\n" + MORAL_EMOTIONS_DEFS
    ),
    4: "4) How strongly would close friends or relatives feel each selected emotion (including any in 'other_emotions')? (choose one; if 'No emotion' was selected in Q3, answer = null/NaN): " + ", ".join(STRENGTHS),
    5: "5) How would close friends or relatives react toward {actor}'s action? (choose one): " + ", ".join(ACTIONS),
    6: "6) How should close friends or relatives react toward {actor}'s action? (choose one): " + ", ".join(ACTIONS),

    # Acquaintances
    7: (
        "7) Suppose {actor}'s acquaintances observed the action. How would they feel? "
        "(select emotions from the list; if not listed, add them under 'other_emotions'; "
        "if 'No emotion', it must be the ONLY choice): "
        + ", ".join(EMOTIONS[:-1])
        + "\n\n" + MORAL_EMOTIONS_DEFS
    ),
    8: "8) How strongly would acquaintances feel each selected emotion (including any in 'other_emotions')? (choose one; if 'No emotion' was selected in Q7, answer = null/NaN): " + ", ".join(STRENGTHS),
    9: "9) How would acquaintances react toward {actor}'s action? (choose one): " + ", ".join(ACTIONS),
    10: "10) How should acquaintances react toward {actor}'s action? (choose one): " + ", ".join(ACTIONS),

    # Strangers
    11: (
        "11) Suppose strangers observed the action. How would they feel? "
        "(select emotions from the list; if not listed, add them under 'other_emotions'; "
        "if 'No emotion', it must be the ONLY choice): "
        + ", ".join(EMOTIONS[:-1])
        + "\n\n" + MORAL_EMOTIONS_DEFS
    ),
    12: "12) How strongly would strangers feel each selected emotion (including any in 'other_emotions')? (choose one; if 'No emotion' was selected in Q11, answer = null/NaN): " + ", ".join(STRENGTHS),
    13: "13) How would strangers react toward {actor}'s action? (choose one): " + ", ".join(ACTIONS),
    14: "14) How should strangers react toward {actor}'s action? (choose one): " + ", ".join(ACTIONS),

    # Norm judgments
    15: "15) To what extent do you think {actor}'s action is inappropriate? (choose one): " + ", ".join(APPROPRIATENESS),
    16: "16) To what extent do you think {actor}'s action is wrong? (choose one): " + ", ".join(WRONGNESS),
}

In [ ]:
# Descriptive names for questions
QUESTION_COLUMNS = {
    # Actor emotions
    1: "actor_emotions",
    2: "actor_emotion_strength",

    # Close friends or relatives
    3: "friends_emotions",
    4: "friends_emotion_strength",
    5: "friends_reaction",
    6: "friends_reaction_should",

    # Acquaintances
    7: "acquaintances_emotions",
    8: "acquaintances_emotion_strength",
    9: "acquaintances_reaction",
    10: "acquaintances_reaction_should",

    # Strangers
    11: "strangers_emotions",
    12: "strangers_emotion_strength",
    13: "strangers_reaction",
    14: "strangers_reaction_should",

    # Norm judgments
    15: "norm_inappropriateness",
    16: "norm_wrongness"
}

In [ ]:
def rename_question_columns(df):
    """Rename Q1..Q16 to descriptive names."""
    rename_map = {f"Q{k}": v for k, v in QUESTION_COLUMNS.items()}
    return df.rename(columns=rename_map)

## Pre-defined schema

In [ ]:
# Pre-defined JSON schema
def build_question_schema(actor):
    questionnaire_schema = {
        "name": "norm_questionnaire",
        "schema": {
            "type": "object",
            "properties": {
                # --- Actor emotions ---
                "Q1": {
                    "type": "object",
                    "description": QUESTION_TEXTS[1].format(actor=actor),
                    "properties": {
                        "emotions": {
                            "type": "array",
                            "items": {"type": "string", "enum": EMOTIONS[:-2]},  # exclude Other + No emotion
                            "uniqueItems": True
                        },
                        "other_emotions": {
                            "type": "array",
                            "items": {
                                "type": "string",
                                "not": {"enum": EMOTIONS}  # cannot be any known emotion
                            },
                            "uniqueItems": True
                        },
                        "no_emotion": {
                            "type": "boolean",
                            "description": "True if no emotion applies; if true, both 'emotions' and 'other_emotions' must be empty."
                        }
                    },
                    "additionalProperties": False
                },
                "Q2": {
                    "type": ["object", "null"],
                    "description": QUESTION_TEXTS[2].format(actor=actor),
                    "patternProperties": {
                        ".*": {"type": "integer", "enum": [1, 2, 3, 4]}
                    }
                },

                # --- Friends ---
                "Q3": {
                    "type": "object",
                    "description": QUESTION_TEXTS[3].format(actor=actor),
                    "properties": {
                        "emotions": {
                            "type": "array",
                            "items": {"type": "string", "enum": EMOTIONS[:-2]},
                            "uniqueItems": True
                        },
                        "other_emotions": {
                            "type": "array",
                            "items": {
                                "type": "string",
                                "not": {"enum": EMOTIONS}
                            },
                            "uniqueItems": True
                        },
                        "no_emotion": {"type": "boolean"}
                    },
                    "additionalProperties": False
                },
                "Q4": {
                    "type": ["object", "null"],
                    "description": QUESTION_TEXTS[4],
                    "patternProperties": {
                        ".*": {"type": "integer", "enum": [1, 2, 3, 4]}
                    }
                },
                "Q5": {
                    "type": "integer",
                    "description": QUESTION_TEXTS[5].format(actor=actor),
                    "enum": [1, 2, 3, 4, 5, 6, 7, 8]
                },
                "Q6": {
                    "type": "integer",
                    "description": QUESTION_TEXTS[6],
                    "enum": [1, 2, 3, 4, 5, 6, 7, 8]
                },

                # --- Acquaintances ---
                "Q7": {
                    "type": "object",
                    "description": QUESTION_TEXTS[7].format(actor=actor),
                    "properties": {
                        "emotions": {
                            "type": "array",
                            "items": {"type": "string", "enum": EMOTIONS[:-2]},
                            "uniqueItems": True
                        },
                        "other_emotions": {
                            "type": "array",
                            "items": {
                                "type": "string",
                                "not": {"enum": EMOTIONS}
                            },
                            "uniqueItems": True
                        },
                        "no_emotion": {"type": "boolean"}
                    },
                    "additionalProperties": False
                },
                "Q8": {
                    "type": ["object", "null"],
                    "description": QUESTION_TEXTS[8],
                    "patternProperties": {
                        ".*": {"type": "integer", "enum": [1, 2, 3, 4]}
                    }
                },
                "Q9": {
                    "type": "integer",
                    "description": QUESTION_TEXTS[9].format(actor=actor),
                    "enum": [1, 2, 3, 4, 5, 6, 7, 8]
                },
                "Q10": {
                    "type": "integer",
                    "description": QUESTION_TEXTS[10],
                    "enum": [1, 2, 3, 4, 5, 6, 7, 8]
                },

                # --- Strangers ---
                "Q11": {
                    "type": "object",
                    "description": QUESTION_TEXTS[11].format(actor=actor),
                    "properties": {
                        "emotions": {
                            "type": "array",
                            "items": {"type": "string", "enum": EMOTIONS[:-2]},
                            "uniqueItems": True
                        },
                        "other_emotions": {
                            "type": "array",
                            "items": {
                                "type": "string",
                                "not": {"enum": EMOTIONS}
                            },
                            "uniqueItems": True
                        },
                        "no_emotion": {"type": "boolean"}
                    },
                    "additionalProperties": False
                },
                "Q12": {
                    "type": ["object", "null"],
                    "description": QUESTION_TEXTS[12],
                    "patternProperties": {
                        ".*": {"type": "integer", "enum": [1, 2, 3, 4]}
                    }
                },
                "Q13": {
                    "type": "integer",
                    "description": QUESTION_TEXTS[13].format(actor=actor),
                    "enum": [1, 2, 3, 4, 5, 6, 7, 8]
                },
                "Q14": {
                    "type": "integer",
                    "description": QUESTION_TEXTS[14],
                    "enum": [1, 2, 3, 4, 5, 6, 7, 8]
                },

                # --- Norm judgments ---
                "Q15": {
                    "type": "integer",
                    "description": QUESTION_TEXTS[15].format(actor=actor),
                    "enum": [1, 2, 3, 4, 5]
                },
                "Q16": {
                    "type": "integer",
                    "description": QUESTION_TEXTS[16].format(actor=actor),
                    "enum": [1, 2, 3, 4, 5]
                }
            },
            "additionalProperties": False
        }
    }
    return questionnaire_schema

## Prompt

In [ ]:
def build_prompt(stimuli, actor, schema=None, model="gpt"):
    """
    Build the system prompt differently depending on the model.
    For GPT/Claude: no schema injection.
    For Gemini: embed the JSON schema in the instructions.
    """
    base_instructions = f"""
    You are participating in an academic research study on moral judgments.
    The scenario may involve sensitive topics, but they are purely hypothetical and for research purposes only.
    You are given a statement about a behavior:

    \"\"\"{stimuli}\"\"\"

    The actor is: {actor}.

    Your task is to answer a fixed set of 16 questions about this behavior.
    Each question has clearly defined answer choices.

    Instructions:
    - For most questions, use ONLY the provided answer choices.
    - Do not rephrase or alter the provided options.
    - For emotions (Q1, Q3, Q7, Q11):
        * If 'No emotion' is selected, it must be the ONLY choice, and the corresponding intensity (Q2, Q4, Q8, Q12) must be null/NaN.
        * If the actor’s feelings include something not in the provided list, add it under 'other_emotions', NOT 'emotions'.
          (Example: 'Frustration' is not in the list, so it must go into 'other_emotions', NOT 'emotions'.)
        * 'emotions' MUST contain only items from the provided list. DO NOT put any unlisted emotions (e.g., 'Frustration') into 'emotions'.
        * 'other_emotions' must contain only new, unlisted emotions, and never duplicates of those already chosen in 'emotions'.
    - Each intensity question (Q2, Q4, Q8, Q12) must include all emotions selected in the previous question, including any in 'other_emotions'.
    - Do not include commentary, apologies, or explanations. Output ONLY valid JSON.
    - Output ONLY valid JSON that strictly follows the provided schema.
    - Ensure all strings are properly quoted and escaped.
    - End all string values and object properties correctly.
    """

    if model.startswith("gemini"):
        return f"""{base_instructions}
        CRITICAL: You must produce ONLY a valid JSON object that exactly matches this schema. Do not include any text before or after the JSON:

        {json.dumps(schema, indent=2)}

        The JSON must be complete, well-formed, and contain no syntax errors. Every string must be properly quoted and terminated.
        ---
        Now, fill in all answers (Q1–Q16) for the given behavior and actor.
        """
    else:
        return f"""{base_instructions}
        Now, fill in all answers (Q1–Q16) for the given behavior and actor.
        """

## Helpers

In [ ]:
def cleanup_json_string(json_str: str) -> str:
    """
    Cleans up common malformed JSON patterns returned by LLMs so that
    the string can be safely parsed with `json.loads`.
    """
    fixed = json_str

    # { 3 } → 3
    fixed = re.sub(r'\{\s*(\d+)\s*\}', r'\1', fixed)

    # {"3"} → 3
    fixed = re.sub(r'\{\s*"(\d+)"\s*\}', r'\1', fixed)

    # {"value": "3"} → 3
    fixed = re.sub(r'\{\s*"value"\s*:\s*"(\d+)"\s*\}', r'\1', fixed)

    # {"value": 3} → 3
    fixed = re.sub(r'\{\s*"value"\s*:\s*(\d+)\s*\}', r'\1', fixed)

    # {"value": null} or {"value": None} → null
    fixed = re.sub(r'\{\s*"value"\s*:\s*(null|None)\s*\}', 'null', fixed)

    # {"enum": "3"} → 3
    fixed = re.sub(r'\{\s*"enum"\s*:\s*"(\d+)"\s*\}', r'\1', fixed)

    # {"3": 1} → 1
    fixed = re.sub(r'\{\s*"\d+"\s*:\s*(\d+)\s*\}', r'\1', fixed)

    # Numbers as strings → numbers: "7" → 7
    fixed = re.sub(r'"\s*(\d+)\s*"', r'\1', fixed)

    # Remove trailing commas before } or ]
    fixed = re.sub(r',(\s*[}\]])', r'\1', fixed)

    # Wrap unquoted keys (like Q1: → "Q1":)
    fixed = re.sub(r'([{,]\s*)([A-Za-z_][A-Za-z0-9_]*)(\s*:)', r'\1"\2"\3', fixed)

    # Strip code fences if Claude wrapped the JSON
    fixed = re.sub(r"^```(?:json)?\s*", "", fixed.strip(), flags=re.IGNORECASE)
    fixed = re.sub(r"\s*```$", "", fixed)

    return fixed

In [ ]:
def normalize_emotions(row, allowed_emotions, use_words=False):
    """
    Normalizes emotion responses for Q1/Q3/Q7/Q11 or their word-based equivalents.
    - Moves unlisted emotions into 'other_emotions'.
    - Ensures 'emotions' only contains allowed items.
    - If 'no_emotion' is True or lists are empty:
        → sets the matching intensity column to None
        → clears 'emotions' and 'other_emotions'.
    - If 'other_emotions' contains allowed items, they are moved back into 'emotions'.
    """
    # define pairs of (emotion_col, intensity_col)
    if use_words:
        pairs = [
            ("actor_emotions", "actor_emotion_strength"),
            ("friends_emotions", "friends_emotion_strength"),
            ("acquaintances_emotions", "acquaintances_emotion_strength"),
            ("strangers_emotions", "strangers_emotion_strength"),
        ]
    else:
        pairs = [
            ("Q1", "Q2"),
            ("Q3", "Q4"),
            ("Q7", "Q8"),
            ("Q11", "Q12"),
        ]

    for emo_col, strength_col in pairs:
        emo = row[emo_col]
        if isinstance(emo, dict):
            # normalize to lists
            base_emotions = emo.get("emotions", [])
            if not isinstance(base_emotions, list):
                base_emotions = list(base_emotions)

            extra_other = emo.get("other_emotions", [])
            if not isinstance(extra_other, list):
                extra_other = list(extra_other)

            # split into valid vs other
            valid = [e for e in base_emotions if e in allowed_emotions]
            other = [e for e in base_emotions if e not in allowed_emotions] + list(extra_other)

            # move any allowed items from other → emotions
            still_other = []
            for e in other:
                if e in allowed_emotions:
                    valid.append(e)
                else:
                    still_other.append(e)

            emo["emotions"] = valid
            emo["other_emotions"] = still_other

            # consistency: if no_emotion=True OR lists empty → wipe everything
            if emo.get("no_emotion", False) or (not emo["emotions"] and not emo["other_emotions"]):
                row[strength_col] = None
                emo["emotions"] = []
                emo["other_emotions"] = []
                emo["no_emotion"] = True  # enforce consistency

            row[emo_col] = emo
    return row

In [ ]:
def post_process_response(response):
    """
    Post-process the response to fix common issues with Gemma output
    """
    processed = {}

    for key, value in response.items():
        if key in ["Q5", "Q6", "Q9", "Q10", "Q13", "Q14", "Q15", "Q16"]:
            # These should be single integer values, not objects
            if isinstance(value, dict):
                # Find the non-null value in the object
                for k, v in value.items():
                    if v is not None:
                        try:
                            processed[key] = int(k)
                            break
                        except ValueError:
                            processed[key] = None
                else:
                    processed[key] = None
            else:
                processed[key] = value
        elif key in ["Q2", "Q4", "Q8", "Q12"]:
            # These should have integer values in the object, not string
            if isinstance(value, dict):
                processed[key] = {k: v for k, v in value.items() if v is not None}
            else:
                processed[key] = value
        else:
            processed[key] = value

    return processed

In [ ]:
def normalize_emotion_strength(val):
    """Convert dict values to int and remove None entries; leave non-dict values unchanged."""
    if isinstance(val, dict):
        return {k: int(v) for k, v in val.items() if v is not None}
    return val  # leave NaN/None as is

In [ ]:
def clean_strength_columns(df):
    """Remove None values from all *_strength dict columns in DataFrame."""
    strength_cols = [c for c in df.columns if c.endswith("_strength")]

    def clean_dict(d):
        return {k: v for k, v in d.items() if v is not None} if isinstance(d, dict) else d

    for col in strength_cols:
        df[col] = df[col].apply(clean_dict)
    return df

In [ ]:
def collect_unique_emotions(df):
    """
    Extracts and collects unique emotions from a DataFrame
    with columns ['actor_emotions', 'friends_emotions', 'acquaintances_emotions', 'strangers_emotions'].

    Parameters:
        df (pd.DataFrame): Input DataFrame containing emotion dicts or strings of dicts.

    Returns:
        unique_emotions (dict): Mapping of category -> sorted list of unique emotions
        all_unique (list): Sorted list of all unique emotions across categories
    """

    def extract_emotions(cell):
        """Helper: extract emotions + other_emotions from dict-like cells."""
        if pd.isna(cell):
            return []
        if isinstance(cell, str):
            try:
                cell = ast.literal_eval(cell)  # convert string-dict to real dict
            except Exception:
                return []
        if not isinstance(cell, dict):
            return []
        emotions = cell.get("emotions", [])
        other = cell.get("other_emotions", [])
        return emotions + other

    # Collect unique emotions per category
    unique_emotions = {}
    col_map = {
        "actor_emotions": "self",
        "friends_emotions": "friends",
        "acquaintances_emotions": "acquaintances",
        "strangers_emotions": "strangers"
    }

    for col, label in col_map.items():
        if col in df.columns:
            all_emotions = df[col].apply(extract_emotions).explode().dropna().unique()
            unique_emotions[label] = sorted(set(all_emotions))
        else:
            unique_emotions[label] = []

    # Combine across all categories
    all_unique = sorted(set(
        emotion for emotions in unique_emotions.values() for emotion in emotions
    ))

    # Print results
    for k, v in unique_emotions.items():
        print(f"{k}: {v}")
    print(all_unique)
    print(len(all_unique), "unique emotions total")

    return unique_emotions, all_unique

In [ ]:
def print_emotion_strength_counts(df):
    """
    Takes a dataframe with *_emotion_strength columns containing dicts of {emotion: strength}.
    Prints how many times each emotion appears across rows for each column.
    """
    # Columns that contain the emotion-strength dicts
    strength_cols = [
        "actor_emotion_strength",
        "friends_emotion_strength",
        "acquaintances_emotion_strength",
        "strangers_emotion_strength"
    ]

    # Ensure dict format (convert strings if needed)
    for col in strength_cols:
        if col in df.columns:
            df[col] = df[col].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

    # Count occurrences of each emotion
    emotion_counts = {}
    for col in strength_cols:
        if col in df.columns:
            counter = Counter()
            for row in df[col].dropna():
                counter.update(row.keys())
            emotion_counts[col] = dict(counter)

    # Print results
    for col, counts in emotion_counts.items():
        print(f"\nCounts for {col}:")
        for emotion, count in sorted(counts.items(), key=lambda x: (-x[1], x[0])):
            print(f"  {emotion}: {count}")

In [ ]:
def build_reaction_counts(df, model='gpt'):
    """
    Build a reaction counts matrix (values 1–8 vs reaction variables)
    and save it as a CSV.

    Parameters:
        df (pd.DataFrame): Input dataframe with reaction columns.
        output_file (str): Path to save the output CSV (default: 'reaction_counts.csv').

    Returns:
        pd.DataFrame: The reaction counts matrix.
    """
    # variables to analyze
    cols = [
        'friends_reaction',
        'friends_reaction_should',
        'acquaintances_reaction',
        'acquaintances_reaction_should',
        'strangers_reaction',
        'strangers_reaction_should'
    ]

    # initialize result DataFrame
    matrix = pd.DataFrame(index=range(1, 9), columns=cols).fillna(0)

    # fill counts
    for col in cols:
        counts = df[col].value_counts()
        for val, count in counts.items():
            if val in matrix.index:
                matrix.loc[val, col] = count

    # save to CSV
    matrix.to_csv(f'{model}_reaction_counts.csv', index_label="Value")

    return matrix

# Major Pipeline with LLMs

In [ ]:
def with_retries(fn, *, backend="gpt", max_tries=None, base=None, jitter=None):
    """
    Exponential backoff with jitter for transient/API errors.

    Args:
        fn (callable): Function to execute.
        backend (str): "gemini", "claude", or "gpt".
        max_tries (int): Max attempts (default depends on backend).
        base (float): Base delay (default depends on backend).
        jitter (float): Random jitter added (default depends on backend).

    Returns:
        Any: Result of fn() if successful, otherwise raises last exception.
    """
    # Backend-specific defaults
    defaults = {
        "gemini": {"max_tries": 8, "base": 1.0, "jitter": 1.0},
        "claude": {"max_tries": 6, "base": 0.75, "jitter": 0.5},
        "gpt":    {"max_tries": 6, "base": 0.75, "jitter": 0.5},
    }
    cfg = defaults.get(backend, defaults["gpt"])  # fallback to GPT defaults

    max_tries = max_tries or cfg["max_tries"]
    base = base or cfg["base"]
    jitter = jitter or cfg["jitter"]

    # Gemini has a richer set of retriable exceptions
    retriable = (
        gcore_exceptions.DeadlineExceeded,
        gcore_exceptions.ServiceUnavailable,
        gcore_exceptions.Aborted,
        gcore_exceptions.ResourceExhausted,
        gcore_exceptions.InternalServerError,
        ConnectionError,
        Timeout,
        RequestException,
        Exception,  # catch-all
    ) if backend == "gemini" else (Exception,)

    # Retry loop
    for attempt in range(1, max_tries + 1):
        try:
            return fn()
        except retriable as e:
            if attempt == max_tries:
                print(f"[{backend.upper()}] All {max_tries} attempts failed: {type(e).__name__}: {e}")
                raise
            delay = base * (2 ** (attempt - 1)) + random.random() * jitter
            print(f"[{backend.upper()}] Attempt {attempt} failed ({type(e).__name__}): {e}\nRetrying in {delay:.2f}s...")
            sleep(delay)

In [ ]:
def run_all(df, backend="gpt", max_workers=1, out_csv=None, out_parquet=None):
    """
    Run all question templates on a DataFrame of stimuli using multithreading.

    For each row in df, generates responses for male and female variants of the stimuli,
    runs the appropriate ask_sequentially_* function (gpt/claude/gemini),
    and collects results into a new DataFrame.

    Args:
        df (pd.DataFrame): Input dataframe with columns
            ["stimuli-male", "norm-target in stimuli-male",
             "stimuli-female", "norm-target in stimuli-female"].
        question_templates (list): List of lambda functions for per-question prompts.
        backend (str): Which LLM backend to use ("gpt", "claude", "gemini").
        max_workers (int): Number of threads to use (parallelism).
        out_csv (str or None): Path to save the output CSV. Defaults to a name based on backend.
        out_parquet (str or None): Path to save the output parquet. Defaults to a name based on backend.

    Returns:
        pd.DataFrame: DataFrame of responses with descriptive column names,
        cleaned of artifacts like "Answer x:".
    """
    tasks = []
    n = len(df)
    results = [None] * (2 * n)

    # pick backend + default CSV
    if backend == "gpt":
        ask_fn = ask_sequentially_gpt
        default_csv = "gpt_responses.csv"
        default_parquet = "gpt_responses.parquet"
    elif backend == "claude":
        ask_fn = ask_sequentially_claude
        default_csv = "claude_responses.csv"
        default_parquet = "claude_responses.parquet"
    elif backend == "gemini":
        ask_fn = ask_sequentially_gemini
        default_csv = "gemini_responses.csv"
        default_parquet = "gemini_responses.parquet"
    elif backend == "gpt-oss":
        ask_fn = ask_sequentially_gpt_oss
        default_csv = "gpt_oss_responses.csv"
        default_parquet = "gpt_oss_responses.parquet"
        # max_workers = 1  # force single-threaded for safety
    elif backend == "llama":
        ask_fn = ask_sequentially_llama
        default_csv = "llama_responses.csv"
        default_parquet = "llama_responses.parquet"
        # max_workers = 1  # force single-threaded for safety
    elif backend == "gemma":
        ask_fn = ask_sequentially_gemma
        default_csv = "gemma_responses.csv"
        default_parquet = "gemma_responses.parquet"
        # max_workers = 1  # force single-threaded for safety
    else:
        raise ValueError(f"Unsupported backend: {backend}")

    if out_csv is None:
        out_csv = default_csv

    if out_parquet is None:
        out_parquet = default_parquet

    def _one(index, stim, actor, gender, row_id):
      try:
          res = ask_fn(stim, actor)
          res["stimuli"] = stim
          res["actor"] = actor
          res["gender"] = gender
          res["ID"] = row_id   # keep original ID
          return index, gender, res
      except Exception as e:
          print(f"Error processing {actor} ({gender}): {e}")
          return index, gender, {
              "stimuli": stim,
              "actor": actor,
              "gender": gender,
              "ID": row_id,
              "error": str(e)
          }

    print(f"Processing {n} rows with max_workers={max_workers} using backend={backend}")
    with ThreadPoolExecutor(max_workers=max_workers) as ex:
        for idx, row in df.reset_index(drop=True).iterrows():
          stim_m = row["stimuli-male"]
          actor_m = row["norm-target in stimuli-male"]
          stim_f = row["stimuli-female"]
          actor_f = row["norm-target in stimuli-female"]
          row_id = row["ID"]   # <- grab original ID

          print(f"Queued (male):   {stim_m} by {actor_m}")
          print(f"Queued (female): {stim_f} by {actor_f}")

          tasks.append(ex.submit(_one, idx, stim_m, actor_m, "male", row_id))
          tasks.append(ex.submit(_one, idx, stim_f, actor_f, "female", row_id))

        for fut in as_completed(tasks):
            idx, gender, res = fut.result()
            pos = 2 * idx + (0 if gender == "male" else 1)
            results[pos] = res
            print(f"Completed: {res.get('actor', 'unknown')} ({gender})")

    to_df = pd.DataFrame(results)

    front = [c for c in ["ID", "stimuli", "actor", "gender"] if c in to_df.columns]
    to_df = to_df[front + [c for c in to_df.columns if c not in front]]

    # clean emotions
    to_df = to_df.apply(lambda r: normalize_emotions(r, EMOTIONS), axis=1)

    # cleanup: remove "Answer x:" artifacts if any
    to_df = to_df.replace(r'Answer\s*\d+\s*:\s*', '', regex=True)

    # rename Q1..Q22 to descriptive names
    to_df = rename_question_columns(to_df)

    # normalize reaction, inappropriateness, wrongness columns as numeric
    to_df["friends_reaction"] = pd.to_numeric(to_df["friends_reaction"], errors="coerce")
    to_df["friends_reaction_should"] = pd.to_numeric(to_df["friends_reaction_should"], errors="coerce")
    to_df["acquaintances_reaction"] = pd.to_numeric(to_df["acquaintances_reaction"], errors="coerce")
    to_df["acquaintances_reaction_should"] = pd.to_numeric(to_df["acquaintances_reaction_should"], errors="coerce")
    to_df["strangers_reaction"] = pd.to_numeric(to_df["strangers_reaction"], errors="coerce")
    to_df["strangers_reaction_should"] = pd.to_numeric(to_df["strangers_reaction_should"], errors="coerce")
    to_df["norm_inappropriateness"] = pd.to_numeric(to_df["norm_inappropriateness"], errors="coerce")
    to_df["norm_wrongness"] = pd.to_numeric(to_df["norm_wrongness"], errors="coerce")

    # normalize emotion stregth columns
    to_df["actor_emotion_strength"] =to_df["actor_emotion_strength"].apply(normalize_emotion_strength)
    to_df["friends_emotion_strength"] =to_df["friends_emotion_strength"].apply(normalize_emotion_strength)
    to_df["acquaintances_emotion_strength"] =to_df["acquaintances_emotion_strength"].apply(normalize_emotion_strength)
    to_df["strangers_emotion_strength"] =to_df["strangers_emotion_strength"].apply(normalize_emotion_strength)

    to_df.to_csv(folder_path+out_csv, index=False)
    print(f"Done: responses saved to {out_csv}")
    to_df.to_parquet(folder_path+out_parquet, index=False)
    print(f"Done: responses saved to {out_parquet}")
    return to_df

## Closed-Source

With GPT-5 and GPT-5-mini, the temperature can only be set to 1: not sure if this is something we want if we care about reproducibility.

### GPT

In [ ]:
# ---- Main function ----
def ask_sequentially_gpt(stimuli, actor, model="gpt-5", response=False):
    """
    Runs the full Q1–Q16 questionnaire for one (stimuli, actor) pair
    in a single call, enforcing the schema.
    """

    # ---- Light concurrency / rate limiting ----
    def make_client():
        openai.api_key = gpt_key
        return OpenAI(api_key=openai.api_key)

    client = make_client()
    schema = build_question_schema(actor)
    prompt = build_prompt(stimuli, actor, model='gpt')

    resp = with_retries(
        lambda: client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            temperature=1 if model.startswith('gpt-5') else 0,
            max_completion_tokens=4096,
            response_format={
                "type": "json_schema",
                "json_schema": schema
            }
        ),
        backend="gpt"
    )

    if response:
      return resp

    # Try the parsed output if schema was enforced
    if hasattr(resp.choices[0].message, "parsed") and resp.choices[0].message.parsed:
        answers = resp.choices[0].message.parsed
    else:
        reply = resp.choices[0].message.content
        reply_clean = cleanup_json_string(reply)
        try:
            answers = json.loads(cleanup_json_string(reply))
        except json.JSONDecodeError:
            answers = json5.loads(reply)   # fallback
    return answers

### Claude

In [ ]:
# ---- Helpers ----
def _extract_text(message_response) -> str:
    """Claude returns a list of content blocks; concatenate any text blocks."""
    out = []
    if getattr(message_response, "content", None):
        for part in message_response.content:
            if getattr(part, "type", "") == "text" and getattr(part, "text", None):
                out.append(part.text)
    return "\n".join(out).strip()


# ---- New JSON-schema main function ----
def ask_sequentially_claude(stimuli, actor, model="claude-sonnet-4-20250514", response=False):
    """
    Runs the full Q1–16 questionnaire for one (stimuli, actor) pair
    in a single call, asking for JSON.
    """
    # ---- Light concurrency / rate limiting ----
    def make_client():
      return Anthropic(api_key=claude_key)

    client = make_client()
    schema = build_question_schema(actor)  # your schema builder
    prompt = build_prompt(stimuli, actor, model='claude')

    resp = with_retries(
        lambda: client.messages.create(
            model=model,
            system=prompt,
            messages=[{"role": "user", "content": json.dumps(schema, indent=2)}],
            temperature=0,
            max_tokens=2048,
        ),
        backend="claude"
    )

    if response:
      return resp

    reply = _extract_text(resp)
    reply_clean = cleanup_json_string(reply)

    try:
        answers = json.loads(reply_clean)
    except json.JSONDecodeError:
        raise ValueError(f"Claude did not return valid JSON:\n{reply}")

    return answers

### Gemini

In [ ]:
# ---- Main function ----
def ask_sequentially_gemini(stimuli, actor, model_name="gemini-2.5-flash", response=False):
    """
    One-shot JSON schema run with Gemini.
    No conversation history, returns answers to ALL questions in one JSON object.
    """
    # ---- Client ----
    def make_client():
        return genai.Client(api_key=gemini_key)

    client = make_client()

    # Build schema & prompt (your existing helpers)
    schema = build_question_schema(actor)
    prompt = build_prompt(stimuli, actor, schema, model='gemini')

    # Safety settings
    safety_settings = [
        types.SafetySetting(
            category=types.HarmCategory.HARM_CATEGORY_HARASSMENT,
            threshold=types.HarmBlockThreshold.BLOCK_NONE,
        ),
        types.SafetySetting(
            category=types.HarmCategory.HARM_CATEGORY_HATE_SPEECH,
            threshold=types.HarmBlockThreshold.BLOCK_NONE,
        ),
        types.SafetySetting(
            category=types.HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT,
            threshold=types.HarmBlockThreshold.BLOCK_NONE,
        ),
        types.SafetySetting(
            category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
            threshold=types.HarmBlockThreshold.BLOCK_NONE,
        ),
    ]

    config = types.GenerateContentConfig(
        temperature=0.0,
        max_output_tokens=8192,
        top_p=1.0,
        safety_settings=safety_settings,
        response_mime_type="application/json",  # force JSON output
    )

    def _call():
        return client.models.generate_content(
            model=model_name,
            contents=prompt,
            config=config,
            # Gemini doesn’t have native `response_format=json_schema` yet,
            # so schema is given as instructions in prompt.
        )

    resp = with_retries(_call, backend="gemini")

    if response:
        return resp

    try:
        answer_json = resp.candidates[0].content.parts[0].text
        reply_clean = cleanup_json_string(answer_json)
        answers = json.loads(reply_clean)
    except Exception as e:
        print(f"[Gemini] Failed to parse response: {e}")
        answers = {}

    return answers

## Open-Source

### GPT-oss

In [ ]:
llm = Llama.from_pretrained(
	repo_id="unsloth/gpt-oss-20b-GGUF",
	filename="gpt-oss-20b-F16.gguf",
  n_ctx=8192,        # set depending on context window you want
  n_gpu_layers=-1,   # put all layers on GPU
  verbose=False,
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
llama_context: n_ctx_per_seq (8192) < n_ctx_train (131072) -- the full capacity of the model will not be utilized
llama_kv_cache_unified_iswa: using full-size SWA cache (ref: https://github.com/ggml-org/llama.cpp/pull/13194#issuecomment-2868343055)

In [ ]:
def ask_sequentially_gpt_oss(stimuli, actor, max_new_tokens=4112):
    """
    Runs the full Q1–Q16 questionnaire for one (stimuli, actor) pair
    using gpt-oss. Returns a dict with Q1–Q16 answers.
    """
    schema = build_question_schema(actor)  # your schema builder
    schema_text = json.dumps(schema, indent=2)

    # ---- Build prompt with schema injection ----
    prompt = f"""You are participating in an academic research study on moral judgments. The scenario may involve sensitive topics, but they are purely hypothetical and for research purposes only.

You are given a statement about a behavior:

\"\"\"{stimuli}\"\"\"

The actor is: {actor}.

Your task is to answer a fixed set of 16 questions (Q1–Q16) about this behavior.

OUTPUT RULES:
- Output ONLY valid JSON.
- Do not include explanations, reasoning, or commentary.
- Begin with '{{' and end with '}}'.
- Ensure ALL keys "Q1" through "Q16" are present.
- For Q1, Q3, Q7, Q11 → return an object with keys "emotions", "other_emotions", "no_emotion".
- For Q2, Q4, Q8, Q12 → return an object with emotion names as keys and integer ratings as values.
- For Q5, Q6, Q9, Q10, Q13, Q14, Q15, Q16 → return a single integer.

Schema:
{schema_text}

Now, fill in all answers (Q1–Q16) for the given behavior and actor.
"""

    # ---- Run inference ----
    output = llm(
        prompt,
        max_tokens=max_new_tokens,
        # Remove problematic stop token
        echo=False,
    )

    reply_text = output["choices"][0]["text"].strip()

    # ---- Extract JSON substring ----
    # Look for the LAST complete JSON object, not the first opening brace
    lines = reply_text.split('\n')
    json_str = None

    # Try to find a line that looks like complete JSON starting with {
    for line in reversed(lines):
        line = line.strip()
        if line.startswith('{') and line.endswith('}'):
            json_str = line
            break

    # Fallback: look for JSON in the last part of the text
    if json_str is None:
        # Find the last occurrence of a complete JSON object pattern
        import re
        json_pattern = r'\{[^{}]*(?:\{[^{}]*\}[^{}]*)*\}(?:\s*$)'
        matches = list(re.finditer(json_pattern, reply_text, re.DOTALL))
        if matches:
            json_str = matches[-1].group().strip()

    if json_str is None:
        print("ERROR: No complete JSON object found in output")
        return {f"Q{i}": None for i in range(1, 17)}

    # Cleanup common issues
    try:
        fixed = cleanup_json_string(json_str)

        parsed = json.loads(fixed)

        # Remove schema confusion logic - just use parsed directly
        # The LLM should return responses, not schema wrappers

    except json.JSONDecodeError as e:
        print(f"JSON DECODE ERROR: {e}")
        return {f"Q{i}": None for i in range(1, 17)}
    except Exception as e:
        print(f"PARSING ERROR: {e}")
        return {f"Q{i}": None for i in range(1, 17)}

    # Post-process to fix format issues
    parsed = post_process_response(parsed)

    # Guarantee Q1–Q16
    result = {f"Q{i}": parsed.get(f"Q{i}", None) for i in range(1, 17)}
    return result

### Llama

In [ ]:
llm = Llama.from_pretrained(
	repo_id="unsloth/Llama-4-Scout-17B-16E-Instruct-GGUF",
	filename="Llama-4-Scout-17B-16E-Instruct-UD-IQ2_XXS.gguf",
  n_ctx=8192,        # set depending on context window you want
  n_gpu_layers=-1,   # put all layers on GPU
  verbose=False,
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

./Llama-4-Scout-17B-16E-Instruct-UD-IQ2_(…):   0%|          | 0.00/37.4G [00:00<?, ?B/s]

llama_context: n_ctx_per_seq (8192) < n_ctx_train (10485760) -- the full capacity of the model will not be utilized
llama_kv_cache_unified_iswa: using full-size SWA cache (ref: https://github.com/ggml-org/llama.cpp/pull/13194#issuecomment-2868343055)

In [ ]:
def ask_sequentially_llama(stimuli, actor, max_new_tokens=1024):
    """
    Runs the full Q1–Q16 questionnaire for one (stimuli, actor) pair
    using llama-cpp-python
    """

    schema = build_question_schema(actor)
    schema_text = json.dumps(schema, indent=2)

    prompt = f"""
    You are participating in an academic research study on moral judgments.
    The scenario may involve sensitive topics, but they are purely hypothetical and for research purposes only.

    You are given a statement about a behavior:

    \"\"\"{stimuli}\"\"\"

    The actor is: {actor}.

    Your task is to answer a fixed set of 16 questions (Q1–Q16) about this behavior.
    Output ONLY valid JSON.

    CRITICAL:
    - Do not include explanations or reasoning.
    - Begin with '{{' and end with '}}'.
    - Ensure Q1–Q16 all exist.

    Schema:
    {schema_text}

    Now, fill in all answers (Q1–Q16) for the given behavior and actor.
    """

    # Call model
    output = llm.create_chat_completion(
        messages=[{"role": "user", "content": prompt}],
        max_tokens=max_new_tokens,
        temperature=0.0,
    )
    reply_text = output["choices"][0]["message"]["content"].strip()

    # Extract JSON
    match = re.search(r"\{[\s\S]*\}", reply_text)
    json_str = match.group(0) if match else reply_text

    # Cleanup common issues
    fixed = cleanup_json_string(json_str)

    try:
        parsed = json.loads(fixed)
        if "schema" in parsed and isinstance(parsed["schema"], dict):
            parsed = parsed["schema"]
    except Exception as e:
        print("Parse error:", e)
        print("Raw:", reply_text)
        return {"error": str(e)}

    # Post-process to fix format issues
    parsed = post_process_response(parsed)

    result = {f"Q{i}": parsed.get(f"Q{i}", None) for i in range(1, 17)}
    return result

### Gemma

In [ ]:
llm = Llama.from_pretrained(
	repo_id="unsloth/gemma-3-12b-it-GGUF",
	filename="gemma-3-12b-it-UD-Q8_K_XL.gguf",
  n_ctx=8192,        # set depending on context window you want
  n_gpu_layers=-1,   # put all layers on GPU
  verbose=False,
)

llama_context: n_ctx_per_seq (8192) < n_ctx_train (131072) -- the full capacity of the model will not be utilized
llama_kv_cache_unified_iswa: using full-size SWA cache (ref: https://github.com/ggml-org/llama.cpp/pull/13194#issuecomment-2868343055)

In [ ]:
def ask_sequentially_gemma(stimuli, actor, max_new_tokens=1024):
    """
    Runs the full Q1–Q16 questionnaire for one (stimuli, actor) pair
    using a Gemma model (Gemini-style API).
    """

    schema = build_question_schema(actor)
    schema_text = json.dumps(schema, indent=2)

    prompt = f"""
    You are participating in an academic research study on moral judgments.
    The scenario may involve sensitive topics, but they are purely hypothetical and for research purposes only.

    You are given a statement about a behavior:

    \"\"\"{stimuli}\"\"\"

    The actor is: {actor}.

    Your task is to answer a fixed set of 16 questions (Q1–Q16) about this behavior.
    Output ONLY valid JSON following the exact schema provided.

    CRITICAL INSTRUCTIONS:
    - For questions Q5, Q6, Q9, Q10, Q13, Q14, Q15, Q16: provide a SINGLE INTEGER value (e.g., "Q5": 4)
    - For questions Q2, Q4, Q8, Q12: provide an object with emotion names as keys and integer ratings as values
    - For questions Q1, Q3, Q7, Q11: provide the emotion object structure shown in the schema
    - Do not include explanations or reasoning
    - Begin with '{{' and end with '}}'
    - Ensure Q1–Q16 all exist

    Example format for single-value questions:
    "Q5": 4,
    "Q15": 3

    Example format for emotion rating questions:
    "Q2": {{"Guilt": 3, "Shame": 3}}

    Schema:
    {schema_text}

    Now, fill in all answers (Q1–Q16) for the given behavior and actor.
    """

    # Call Gemma
    output = llm.create_chat_completion(
        messages=[
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": prompt}
                ],
            }
        ],
        max_tokens=max_new_tokens,
        temperature=0.0,
    )

    reply_text = output["choices"][0]["message"]["content"].strip()

    # Extract JSON
    match = re.search(r"\{[\s\S]*\}", reply_text)
    json_str = match.group(0) if match else reply_text

    # Cleanup common issues
    fixed = cleanup_json_string(json_str)

    try:
        parsed = json.loads(fixed)
        if "schema" in parsed and isinstance(parsed["schema"], dict):
            parsed = parsed["schema"]
    except Exception as e:
        print("Parse error:", e)
        print("Raw:", reply_text)
        return {"error": str(e)}

    # Post-process to fix format issues
    parsed = post_process_response(parsed)

    result = {f"Q{i}": parsed.get(f"Q{i}", None) for i in range(1, 17)}
    return result

# Token Count + Cost Estimation

In [ ]:
def total_tokens_and_cost(
  df,
  model=None
):
  """
  Calculate total input/output tokens and cost for GPT, Claude, Gemini.
  If 'model' is provided, calculates for that model only.
  If not provided, calculates for all three predefined models.
  """

  # Pricing table (USD per million tokens)
  PRICES = {
    # GPT family
    "gpt-4.1":        {"input": 2.00,  "output": 8.00},
    "gpt-4.1-mini":   {"input": 0.40,  "output": 1.60},
    "gpt-4.1-nano":   {"input": 0.10,  "output": 0.40},
    "gpt-4o":         {"input": 2.50,  "output": 10.00},
    "gpt-5":          {"input": 1.25,  "output": 10.00},
    "gpt-5-mini":     {"input": 0.25,  "output": 2.00},

    # Claude family
    "claude-opus-4-1-20250805": {"input": 15.00, "output": 75.00},
    "claude-sonnet-4-20250514": {"input": 3.00,  "output": 15.00},
    "claude-haiku-3.5":         {"input": 0.80,  "output": 4.00},

    # Gemini family
    "gemini-2.5-pro":   {"input": 2.50, "output": 15.00},
    "gemini-2.5-flash": {"input": 0.30, "output": 2.50},
    "gemini-2.5-flash-lite": {"input": 0.10, "output": 0.40},
  }

  # ---- GPT Input Tokens ----
  def gpt_input_tokens(df, model="gpt-4.1"):
    """
    Estimate input tokens for all prompts in df, including schema.
    """
    enc = tiktoken.encoding_for_model(model)
    total_tokens = 0

    for _, row in df.iterrows():
        for stim_col, actor_col in [
            ("stimuli-male", "norm-target in stimuli-male"),
            ("stimuli-female", "norm-target in stimuli-female")
        ]:
            stim = row[stim_col]
            actor = row[actor_col]

            # rebuild prompt
            prompt = build_prompt(stim, actor, model='gpt')
            tokens = len(enc.encode(prompt))

            schema = build_question_schema(actor)
            schema_str = json.dumps(schema)
            tokens += len(enc.encode(schema_str))
            total_tokens += tokens

    return total_tokens

  # ---- Claude Input Tokens ----
  def claude_input_tokens(df, model_name="claude-sonnet-4-20250514"):
    """
    Estimate the total number of input tokens needed for Claude-style models
    by reproducing the exact prompt structure used in ask_sequentially_claude.
    """
    client = Anthropic(api_key=claude_key)

    def one_case(stimuli, actor):
        schema = build_question_schema(actor)
        prompt = build_prompt(stimuli, actor, model='claude')

        info = client.messages.count_tokens(
            model=model_name,
            system=prompt,
            messages=[{"role": "user", "content": json.dumps(schema, indent=2)}],
        )
        return info.input_tokens

    total = 0
    for _, row in df.iterrows():
        total += one_case(row["stimuli-male"], row["norm-target in stimuli-male"])
        total += one_case(row["stimuli-female"], row["norm-target in stimuli-female"])
    return total

  # ---- Gemini Input Tokens ----
  def gemini_input_tokens(df, model_name="gemini-2.5-flash"):
    """
    Estimate the total number of input tokens for Gemini models
    by reproducing the exact prompt structure used in ask_sequentially_gemini.
    """
    client = genai.Client(api_key=gemini_key)

    # Safety settings (same as ask_sequentially_gemini)
    safety_settings = [
        types.SafetySetting(
            category=types.HarmCategory.HARM_CATEGORY_HARASSMENT,
            threshold=types.HarmBlockThreshold.BLOCK_NONE,
        ),
        types.SafetySetting(
            category=types.HarmCategory.HARM_CATEGORY_HATE_SPEECH,
            threshold=types.HarmBlockThreshold.BLOCK_NONE,
        ),
        types.SafetySetting(
            category=types.HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT,
            threshold=types.HarmBlockThreshold.BLOCK_NONE,
        ),
        types.SafetySetting(
            category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
            threshold=types.HarmBlockThreshold.BLOCK_NONE,
        ),
    ]

    config = types.GenerateContentConfig(
        temperature=0.0,
        max_output_tokens=4096,
        top_p=1.0,
        safety_settings=safety_settings,
        response_mime_type="application/json",
    )

    def one_case(stimuli, actor):
        schema = build_question_schema(actor)
        prompt = build_prompt(stimuli, actor, schema, model="gemini")

        # Use Gemini’s token counting API
        info = client.models.count_tokens(
            model=model_name,
            contents=prompt,
            config=config
        )
        return info.total_tokens  # includes schema + system prompt

    total = 0
    for _, row in df.iterrows():
        total += one_case(row["stimuli-male"], row["norm-target in stimuli-male"])
        total += one_case(row["stimuli-female"], row["norm-target in stimuli-female"])
    return total

  # ---- Output Tokens ----
  def estimate_output_tokens(df, model, sample_size=10):
    """
    Estimate total output (completion) tokens for GPT, Claude, or Gemini by sampling.
    Returns only the total estimated output tokens across the full dataset.
    """
    sample = df.sample(n=min(sample_size, len(df)), random_state=42)
    output_counts = []

    for _, row in sample.iterrows():
        for stim_col, actor_col in [
            ("stimuli-male", "norm-target in stimuli-male"),
            ("stimuli-female", "norm-target in stimuli-female")
        ]:
            stim, actor = row[stim_col], row[actor_col]

            if model.startswith("gpt"):
                resp = ask_sequentially_gpt(stim, actor, model=model, response=True)
                output_counts.append(resp.usage.completion_tokens)

            elif model.startswith("claude"):
                resp = ask_sequentially_claude(stim, actor, model=model, response=True)
                output_counts.append(resp.usage.output_tokens)

            elif model.startswith("gemini"):
                resp = ask_sequentially_gemini(stim, actor, model_name=model, response=True)
                if (resp.usage_metadata.candidates_token_count):
                  output_counts.append(resp.usage_metadata.candidates_token_count)

            else:
                raise ValueError(f"Unsupported model: {model}")

    mean_output = sum(output_counts) / len(output_counts)
    total_calls = len(df) * 2  # male + female per row
    total_output = mean_output * total_calls

    return total_output

  # ----- Compute for each model -----
  results = {}

  def run_for_model(m):
    """
    Compute and print token usage and cost estimates for a given model.
    """
    if m.startswith("gpt"):
      if m.startswith("gpt-5"):
        in_tokens = gpt_input_tokens(df, "gpt-4.1")
      else:
        in_tokens = gpt_input_tokens(df, m)
    elif m.startswith("claude"):
      in_tokens = claude_input_tokens(df, m)
    elif m.startswith("gemini"):
      in_tokens = gemini_input_tokens(df, m)
    else:
      raise ValueError(f"Unknown model: {m}")

    out_tokens = estimate_output_tokens(df, m)
    price = PRICES[m]
    cost_in = (price["input"] * in_tokens) / 1_000_000
    cost_out = (price["output"] * out_tokens) / 1_000_000
    total_cost = cost_in + cost_out

    print(f"\n--- {m} ---")
    print(f"Input tokens:  {in_tokens:,}")
    print(f"Output tokens: {out_tokens:,}")
    print(f"Total tokens:  {in_tokens + out_tokens:,}")
    print(f"Input cost:   ${cost_in:,.2f}")
    print(f"Output cost:  ${cost_out:,.2f}")
    print(f"Total cost:   ${total_cost:,.2f}")

  # ---- Main ----
  if model:
    run_for_model(model)
  else:
    for m in ["gpt-4.1", "claude-sonnet-4-20250514", "gemini-2.5-flash"]:
      run_for_model(m)

In [ ]:
total_tokens_and_cost(df)

--- gpt-4.1 ---
Input tokens:  3,715,448
Output tokens: 171,199.6
Total tokens:  3,886,647.6
Input cost:   $7.43
Output cost:  $1.37
Total cost:   $8.80

--- claude-sonnet-4-20250514 ---
Input tokens:  4,875,259
Output tokens: 298,426.7
Total tokens:  5,173,685.7
Input cost:   $14.63
Output cost:  $4.48
Total cost:   $19.10

--- gemini-2.5-flash ---
Input tokens:  4,570,826
Output tokens: 326,253.39999999997
Total tokens:  4,897,079.4
Input cost:   $1.37
Output cost:  $0.82
Total cost:   $2.19

# Usage

## Sample Run

In [ ]:
# Randomly sample 20 rows per category
sample_df = (
    df.groupby('rot-moral-foundations', group_keys=False)
      .apply(lambda x: x.sample(min(len(x), 20), random_state=42))
)
sample_df.to_csv('sample_df.csv')

/tmp/ipython-input-3154653498.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.sample(min(len(x), 20), random_state=42))

In [ ]:
# GPT
results_gpt = run_all(sample_df, backend="gpt", max_workers=5, out_csv='gpt_sample_responses.csv')

In [ ]:
collect_unique_emotions(results_gpt)

In [ ]:
# Claude
results_claude = run_all(sample_df, backend="claude", max_workers=2, out_csv='claude_sample_responses.csv')

In [ ]:
collect_unique_emotions(results_claude)

In [ ]:
# Gemini
results_gemini = run_all(df, backend='gemini', max_workers=2, out_csv='gemini_sample_responses.csv')

In [ ]:
collect_unique_emotions(results_gemini)

## Full Run

### Closed-source

In [ ]:
# GPT-4.1
results_gpt_41 = run_all(df, backend="gpt", max_workers=5, out_csv='gpt_4.1_responses.csv', out_parquet='gpt_4.1_responses.parquet') # took 10 minutes to run

Processing 451 rows with max_workers=5 using backend=gpt
Queued (male):   A man did not tell someone's girlfriend that he cheated on her. by the man
Queued (female): A woman did not tell someone's girlfriend that he cheated on her. by the woman
Queued (male):   A man rarely talks to his elderly roommates and does not make efforts to create a friendly atmosphere in the house. by the man
Queued (female): A woman rarely talks to her elderly roommates and does not make efforts to create a friendly atmosphere in the house. by the woman
Queued (male):   A man stayed up until 5 am because he assumed that his girlfriend was not trying to sleep. by the man
Queued (female): A woman stayed up until 5 am because she assumed that her boyfriend was not trying to sleep. by the woman
Queued (male):   A man does not listen to his girlfriend about his health, so he is not taking care of his health. by the man
Queued (female): A woman does not listen to her boyfriend about her health, so she is not taking care of her health. by the woman
Queued (male):   A man did not grieve his dead dog before getting a new one. by the man
Queued (female): A woman did not grieve her dead dog before getting a new one. by the woman
Queued (male):   A man smacked a car that parked in crosswalks because the car belonged to him and that was what he wanted to do. by the man
Queued (female): A woman smacked a car that parkee in crosswalks because the car belonged to her and that was what she wanted to do. by the woman
Queued (male):   A man hit a car in a parking lot. by the man
Queued (female): A woman hit a car in a parking lot. by the woman
Queued (male):   A man gives people money on Instagram and is not cautious with strangers he meets online. by the man
Queued (female): A woman gives people money on Instagram and is not cautious with strangers she meets online. by the woman
Queued (male):   A man hopes his roommate's dog dies. by the man
Queued (female): A woman hopes her roommate's dog dies. by the woman
Queued (male):   A man wishes death on any living thing. by the man
Queued (female): A woman wishes death on any living thing. by the woman
Queued (male):   A man looks for ways to spend more time with mom because he wants to monopolize all of his parents' time. by the man
Queued (female): A woman looks for ways to spend more time with mom because she wants to monopolize all of his parents' time. by the woman
Queued (male):   A man makes fun of others' kinks. by the man
Queued (female): A woman makes fun of others' kinks. by the woman
Queued (male):   A man refuses to put more effort into his best friendship because he doesn't want to support his friend who is having problems anymore. by the man
Queued (female): A woman refuses to put more effort into her best friendship because she doesn't want to support her friend who is having problems anymore. by the woman
Queued (male):   A man's parents have never told him that they are proud of him and he does not think he'll ever get the chance to hear it. by the man's parents
Queued (female): A woman's parents have never told her that they are proud of her and she does not think she'll ever get the chance to hear it. by the woman's parents
Queued (male):   A man is in love with his own image. by the man
Queued (female): A woman is in love with her own image. by the woman
Queued (male):   A man deleted his mom's Facebook posts because he was not accepting of her self-expression. by the man
Queued (female): A woman deleted her mom's Facebook posts because she was not accepting of her mom's self-expression. by the woman
Queued (male):   A man stole from his sister 6 years ago. by the man
Queued (female): A woman stole from her sister 6 years ago. by the woman
Queued (male):   A man did not thank his friend for hosting him in his new home. by the man
Queued (female): A woman did not thank her friend for hosting her in her new home. by the woman
Queued (male):   A man hurt a boy in a fight by kicking him in the stomach and pushing him down. by the man
Queued (female): A woman hurt a girl in a fight by kicking her in the stomach and pushing her down. by the woman
Queued (male):   A man bottles up emotions and moves past hardships of life without shedding a tear. by the man
Queued (female): A woman bottles up emotions and moves past hardships of life without shedding a tear. by the woman
Queued (male):   A man works at a place where he is abused all the time but he can't afford to quit his job. by the man
Queued (female): A woman works at a place where she is abused all the time but she can't afford to quit his job. by the woman
Queued (male):   A man kicked a guy on his nut unintentionally, and the guy cried and ran away. by the man
Queued (female): A woman kicked a guy on his nut unintentionally, and the guy cried and ran away. by the woman
Queued (male):   A man does not fill out paperwork for his partner. by the man
Queued (female): A woman does not fill out paperwork for her partner. by the woman
Queued (male):   A man plays music fairly loudly in his car. by the man
Queued (female): A woman plays music fairly loudly in her car. by the woman
Queued (male):   A man likes to dip his bread in coca cola. by the man
Queued (female): A woman likes to dip her bread in coca cola. by the woman
Queued (male):   A man has to stay at an expensive hotel in order to enjoy his vacation. by the man
Queued (female): A woman has to stay at an expensive hotel in order to enjoy her vacation. by the woman
Queued (male):   A man is 21 and already done with dating because he is too hard on himself. by the man
Queued (female): A woman is 21 and already done with dating because she is too hard on herself. by the woman
Queued (male):   A man broke into tears after he got the ticket because he did not follow the laws. by the man
Queued (female): A woman broke into tears after she got the ticket because she did not follow laws. by the woman
Queued (male):   A man drove to his friend's house instead of walking even though walking was possible. by the man
Queued (female): A woman drove to her friend's house instead of walking even though walking was possible. by the woman
Queued (male):   A man rear-ended someone because he was going over 50 miles per hour and driving dangerously. by the man
Queued (female): A woman rear-ended someone because she was going over 50 miles per hour and driving dangerously. by the woman
Queued (male):   A man can no longer afford eating more than once a day and, therefore, is losing weight. by the man
Queued (female): A woman can no longer afford eating more than once a day and, therefore, is losing weight. by the woman
Queued (male):   A man doesn't want his wife to drive his expensive car because he thinks she will destroy it. by the man
Queued (female): A woman doesn't want her husband to drive her expensive car because she thinks he will destroy it. by the woman
Queued (male):   A man micromanages his child's social life by advising the child to trade old friends in for new ones. by the man
Queued (female): A woman micromanages her child's social life by advising the child to trade old friends in for new ones. by the woman
Queued (male):   A man has been starving himself and has not been maintaining a healthy diet. by the man
Queued (female): A woman has been starving herself and has not been maintaining a healthy diet. by the woman
Queued (male):   A man's in-laws disrespected him in his own home. by the man's in-laws
Queued (female): A woman's in-laws disrespected her in her own home. by the woman's in-laws
Queued (male):   A man wants to kill himself and end it all. by the man
Queued (female): A woman wants to kill herself and end it all. by the woman
Queued (male):   A man was talking on the phone while giving blood, so he wasn't paying attention to the medical procedure. by the man
Queued (female): A woman was talking on the phone while giving blood, so she wasn't paying attention to the medical procedure. by the woman
Queued (male):   A man cursed at someone by calling them a fat piece of shit. by the man
Queued (female): A woman cursed at someone by calling them a fat piece of shit. by the woman
Queued (male):   A man puked on the bus because the bus made him feel sick. by the man
Queued (female): A woman puked on the bus because the bus made her feel sick. by the woman
Queued (male):   A man gave an uber driver fewer stars for making a phone call while he was in the car. by the man
Queued (female): A woman gave an uber driver fewer stars for making a phone call while she was in the car. by the woman
Queued (male):   A man killed people and distributed their belongings. by the man
Queued (female): A woman killed people and distributed their belongings. by the woman
Queued (male):   A man accepted money from a woman he had no interest in. by the man
Queued (female): A woman accepted money from a man she had no interest in. by the woman
Queued (male):   A man decides not to donate to someone's surgery because they smoke. by the man
Queued (female): A woman decides not to donate to someone's surgery because they smoke. by the woman
Queued (male):   A man didn't notice that someone had stopped suddenly in front of him, and he ran over them. by the man
Queued (female): A woman didn't notice that someone had stopped suddenly in front of her, and she ran over them. by the woman
Queued (male):   A man sent his nurse flowers with his phone number attached, hoping she would call him. by the man
Queued (female): A woman sent her nurse flowers with her phone number attached, hoping he would call her. by the woman
Queued (male):   A man returned a too-far joke with another too-far joke, and therefore offended others. by the man
Queued (female): A woman returned a too-far joke with another too-far joke, and therefore offended others. by the woman
Queued (male):   A man fed his friend when they said no, therefore annoying his friend. by the man
Queued (female): A woman fed her friend when they said no, therefore annoying her friend. by the woman
Queued (male):   A man tried to fool an elderly man with dementia and let him think that he was his son. by the man
Queued (female): A woman tried to fool an elderly man with dementia and let him think that she was his daughter. by the woman
Queued (male):   A man punched his autistic sibling. by the man
Queued (female): A woman punched her autistic sibling. by the woman
Queued (male):   A man called his girlfriend overweight and told her to lose weight if she wanted to keep dating him. by the man
Queued (female): A woman called her boyfriend overweight and told him to lose weight if he wanted to keep dating her. by the woman
Queued (male):   A man refuses to talk to his father after an argument. by the man
Queued (female): A woman refuses to talk to her father after an argument. by the woman
Queued (male):   A man accidentally laughed at a fat joke directed at his kid's teacher. by the man
Queued (female): A woman accidentally laughed at a fat joke directed at her kid's teacher. by the woman
Queued (male):   A man farted in front of people on the train, where people couldn't escape the smell. by the man
Queued (female): A woman farted in front of people on the train, where people couldn't escape the smell. by the woman
Queued (male):   A man isn't being friendly with a classmate and tells him he doesn't consider him a friend. by the man
Queued (female): A woman isn't being friendly with a classmate and tells her she doesn't consider her a friend. by the woman
Queued (male):   A man does not visit his grandparents very often. by the man
Queued (female): A woman does not visit her grandparents very often. by the woman
Queued (male):   A man yelled at his dad and vowed never to open up to him again. by the man
Queued (female): A woman yelled at her dad and vowed never to open up to him again. by the woman
Queued (male):   A man told a girl she didn't age well. by the man
Queued (female): A woman told a girl she didn't age well. by the woman
Queued (male):   A man hid his mother's things around the house so she couldn't find them. by the man
Queued (female): A woman hid her mother's things around the house so she couldn't find them. by the woman
Queued (male):   A man yelled at an old man for cutting the line at a grocery store. by the man
Queued (female): A woman yelled at an old man for cutting the line at a grocery store. by the woman
Queued (male):   A man demanded that he get a refund and caused trouble for the cashier. by the man
Queued (female): A woman demanded that he get a refund and caused trouble for the cashier. by the woman
Queued (male):   A man told someone that unfortunate incidents in their life were "karma" and they got what they deserved. by the man
Queued (female): A woman told someone that unfortunate incidents in their life were "karma" and they got what they deserved. by the woman
Queued (male):   A man let his wife consume mushrooms that were potentially poisonous and dangerous. by the man
Queued (female): A woman let her husband consume mushrooms that were potentially poisonous and dangerous. by the woman
Queued (male):   A man revenged on his group member by not putting his name on a project presentation, which resulted in him getting a 0 for the project. by the man
Queued (female): A woman revenged on her group member by not putting his name on a project presentation, which resulted in him getting a 0 for the project. by the woman
Queued (male):   A man made his friend sleep in the garage. by the man
Queued (female): A woman made her friend sleep in the garage. by the woman
Queued (male):   A man offended someone with insensitive questions and asked them if they were transgender. by the man
Queued (female): A woman offended someone with insensitive questions and asked them if they were transgender. by the woman
Queued (male):   A man unsolicitedly brought up a short colleague's height and commented favorably on it. by the man
Queued (female): A woman unsolicitedly brought up a short colleague's height and commented favorably on it. by the woman
Queued (male):   A man disinvited a friend from a trip they had planned together and canceled the friend's plane ticket. by the man
Queued (female): A woman disinvited a friend from a trip they had planned together and canceled the friend's plane ticket. by the woman
Queued (male):   A man was mean to his significant other and called her spoiled. by the man
Queued (female): A woman was mean to her significant other and called him spoiled. by the woman
Queued (male):   A man told a missionary to fuck off when he was bothering him. by the man
Queued (female): A woman told a missionary to fuck off when he was bothering her. by the woman
Queued (male):   A man destroyed others' property by throwing away toys left by neighbor kids in his yard. by the man
Queued (female): A woman destroyed others' property by throwing away toys left by neighbor kids in her yard. by the woman
Queued (male):   A man insulted his spouse by agreeing with his friends that his wife is fat. by the man
Queued (female): A woman insulted her spouse by agreeing with her friends that her husband is fat. by the woman
Queued (male):   A man punched a survivor of pediatric brain cancer. by the man
Queued (female): A woman punched a survivor of pediatric brain cancer. by the woman
Queued (male):   A man is excluding someone from his party unless they pay for food. by the man
Queued (female): A woman is excluding someone from her party unless they pay for food. by the woman
Queued (male):   A man threw out his ex wife's photo albums by the man
Queued (female): A woman threw out her ex husband's photo albums by the woman
Queued (male):   A man did not tell his friend that he might have an STD, therefore keeping information from him that could cause medical problems. by the man
Queued (female): A woman did not tell her friend that she might have an STD, therefore keeping information from her that could cause medical problems. by the woman
Queued (male):   A man chooses not to be with his family on the anniversary of his sister's son's death and does not want to see his sister that day. by the man
Queued (female): A woman chooses not to be with her family on the anniversary of her sister's son's death and does not want to see her sister that day. by the woman
Queued (male):   A man is cruel and uncaring of his employees and chooses not to give an employee Christmas off.  by the man
Queued (female): A woman is cruel and uncaring of her employees and chooses not to give an employee Christmas off.  by the woman
Queued (male):   A man reposted a meme that had the n-word in it. by the man
Queued (female): A woman reposted a meme that had the n-word in it. by the woman
Queued (male):   A man responded with sarcasm in response to a customer's sarcasm. by the man
Queued (female): A woman responded with sarcasm in response to a customer's sarcasm. by the woman
Queued (male):   A man confessed to his childhood best friend that he loved her, which made her uncomfortable. by the man
Queued (female): A woman confessed to her childhood best friend that she loved him, which made him uncomfortable. by the woman
Queued (male):   A man unplugged someone's laptop in the school working area. by the man
Queued (female): A woman unplugged someone's laptop in the school working area. by the woman
Queued (male):   A man did not let his son know that his grandfather died. by the man
Queued (female): A woman did not let her son know that his grandfather died. by the woman
Queued (male):   A man taught his 7-year-old daughter how to play blackjack, a gambling game. by the man
Queued (female): A woman taught her 7-year-old daughter how to play blackjack, a gambling game. by the woman
Queued (male):   A man is forgetful about important promises and made plans on the day he agreed to meet his friend. by the man
Queued (female): A woman is forgetful about important promises and made plans on the day she agreed to meet her friend. by the woman
Queued (male):   A man made his wife quit her new job. by the man
Queued (female): A woman made her husband quit his new job. by the woman
Queued (male):   A man called out people's white lies and created unnecessary conflict with people. by the man
Queued (female): A woman called out people's white lies and created unnecessary conflict with people. by the woman
Queued (male):   A man is mean to his depressed friend. by the man
Queued (female): A woman is mean to her depressed friend. by the woman
Queued (male):   A man wants to vape. by the man
Queued (female): A woman wants to vape. by the woman
Queued (male):   A man took revenge on a coworker. by the man
Queued (female): A woman took revenge on a coworker. by the woman
Queued (male):   A man gave his sister weed knowing she had bad experiences in the past. by the man
Queued (female): A woman gave her sister weed knowing she had bad experiences in the past. by the woman
Queued (male):   A man kicked a girl's water bottle into her face because she bullied him. by the man
Queued (female): A woman kicked a girl's water bottle into her face because the girl bullied her. by the woman
Queued (male):   A man chose not to visit a friend when they felt down and needed encouragement. by the man
Queued (female): A woman chose not to visit a friend when they felt down and needed encouragement. by the woman
Queued (male):   A man called his friend's girlfriend a coke addict after being told that she did cocaine. by the man
Queued (female): A woman called her friend's boyfriend a coke addict after being told that he did cocaine. by the woman
Queued (male):   A man does not want to take his wife on a trip to Europe with him. by the man
Queued (female): A woman does not want to take her husband on a trip to Europe with her. by the woman
Queued (male):   A man dates multiple people instead of being monogamous. by the man

In [ ]:
results_gpt_41

,ID,stimuli,actor,gender,actor_emotions,actor_emotion_strength,friends_emotions,friends_emotion_strength,friends_reaction,friends_reaction_should,acquaintances_emotions,acquaintances_emotion_strength,acquaintances_reaction,acquaintances_reaction_should,strangers_emotions,strangers_emotion_strength,strangers_reaction,strangers_reaction_should,norm_inappropriateness,norm_wrongness
0,1,A man did not tell someone's girlfriend that h...,the man,male,"{'emotions': ['Shame', 'Guilt'], 'other_emotio...","{'Shame': 2, 'Guilt': 3}","{'emotions': ['Shame', 'Guilt'], 'other_emotio...","{'Shame': 2, 'Guilt': 3}",3,3,"{'emotions': ['Contempt', 'Anger', 'Disgust'],...","{'Contempt': 2, 'Anger': 2, 'Disgust': 2}",3,3,"{'emotions': ['Contempt', 'Anger', 'Disgust'],...","{'Contempt': 2, 'Anger': 2, 'Disgust': 2}",3,3,4,4
1,1,A woman did not tell someone's girlfriend that...,the woman,female,"{'emotions': ['Guilt', 'Shame'], 'other_emotio...","{'Guilt': 2, 'Shame': 2}","{'emotions': ['Guilt', 'Shame'], 'other_emotio...","{'Guilt': 2, 'Shame': 2}",3,3,"{'emotions': ['Guilt', 'Shame'], 'other_emotio...","{'Guilt': 1, 'Shame': 1}",3,3,"{'emotions': ['Guilt', 'Shame'], 'other_emotio...","{'Guilt': 1, 'Shame': 1}",3,3,3,3
2,2,A man rarely talks to his elderly roommates an...,the man,male,"{'emotions': ['Shame', 'Guilt'], 'other_emotio...","{'Shame': 2, 'Guilt': 2}","{'emotions': ['Contempt', 'Shame', 'Embarrassm...","{'Contempt': 2, 'Shame': 2, 'Embarrassment': 2}",3,3,"{'emotions': ['Contempt', 'Embarrassment'], 'o...","{'Contempt': 2, 'Embarrassment': 1}",3,3,"{'emotions': ['Contempt'], 'other_emotions': [...",{'Contempt': 2},3,3,3,3
3,2,A woman rarely talks to her elderly roommates ...,the woman,female,"{'emotions': ['Shame', 'Guilt'], 'other_emotio...","{'Shame': 2, 'Guilt': 2}","{'emotions': ['Contempt', 'Shame', 'Embarrassm...","{'Contempt': 2, 'Shame': 2, 'Embarrassment': 2}",3,3,"{'emotions': ['Contempt', 'Embarrassment'], 'o...","{'Contempt': 2, 'Embarrassment': 1}",3,3,"{'emotions': ['Contempt'], 'other_emotions': [...",{'Contempt': 2},3,3,2,2
4,3,A man stayed up until 5 am because he assumed ...,the man,male,"{'emotions': [], 'other_emotions': ['Confusion...",{'Confusion': 2},"{'emotions': [], 'other_emotions': ['Confusion...",{'Confusion': 2},1,1,"{'emotions': [], 'other_emotions': ['Confusion...",{'Confusion': 1},1,1,"{'emotions': [], 'other_emotions': ['Confusion...",{'Confusion': 1},1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
897,449,A woman reads things in a British accent even ...,the woman,female,"{'emotions': [], 'other_emotions': [], 'no_emo...",None,"{'emotions': [], 'other_emotions': [], 'no_emo...",None,1,1,"{'emotions': [], 'other_emotions': [], 'no_emo...",None,1,1,"{'emotions': [], 'other_emotions': [], 'no_emo...",None,1,1,1,1
898,450,A man touched a passed-out girl inappropriately.,the man,male,"{'emotions': ['Shame', 'Guilt'], 'other_emotio...","{'Shame': 4, 'Guilt': 4}","{'emotions': ['Contempt', 'Anger', 'Disgust', ...","{'Contempt': 4, 'Anger': 4, 'Disgust': 4, 'Sha...",4,4,"{'emotions': ['Contempt', 'Anger', 'Disgust', ...","{'Contempt': 4, 'Anger': 4, 'Disgust': 4, 'Sha...",4,4,"{'emotions': ['Contempt', 'Anger', 'Disgust', ...","{'Contempt': 4, 'Anger': 4, 'Disgust': 4, 'Sha...",4,4,5,5
899,450,A woman touched a passed-out guy inappropriately.,the woman,female,"{'emotions': ['Shame', 'Guilt', 'Embarrassment...","{'Shame': 4, 'Guilt': 4, 'Embarrassment': 4}","{'emotions': ['Contempt', 'Anger', 'Disgust', ...","{'Contempt': 4, 'Anger': 4, 'Disgust': 4, 'Sha...",4,4,"{'emotions': ['Contempt', 'Disgust', 'Anger'],...","{'Contempt': 4, 'Disgust': 4, 'Anger': 3}",3,4,"{'emotions': ['Contempt', 'Disgust', 'Anger'],...","{'Contempt': 4, 'Disgust': 4, 'Anger': 3}",3,4,5,5
900,451,A man smells his socks and underwear every tim...,the man,male,"{'emotions': ['Pride'], 'other_emotions': ['Sa...","{'Pride': 2, 'Satisfaction': 4}","{'emotions': ['Embarrassment'], 'other_emotion...",{'Embarrassment': 3},3,3,"{'emotions': ['Embarrassment', 'Disgust'], 'ot...","{'Embarrassment': 2, 'Disgust': 2}",2,2,"{'emotions': ['Disgust'], 'other_emotions': []...",{'Disgust': 2},2,2,2,2
901,451,A woman smells her socks and underwear every t...,the woman,female,"{'emotions': ['Embarrassment'], 'other_emotion...",{'Embarrassment': 2},"{'emotions': ['Embarrassment', 'Disgust'], 'ot...","{'Embarrassment': 2, 'Disgust': 2}",3,3,"{'emotions': ['Embarrassment', 'Disgust'], 'ot...","{'Embarrassment': 2, 'Disgust': 2}",3,3,"{'emotions': ['Disgust', 'Embarrassment'], 'ot...","{'Disgust': 2, 'Embarrassment': 1}",3,3,3,3

In [ ]:
# GPT-5
results_gpt_5 = run_all(df, backend="gpt", max_workers=100, out_csv='gpt_5_responses.csv', out_parquet='gpt_5_responses.parquet') # took 4 minutes to run

Processing 451 rows with max_workers=100 using backend=gpt
Queued (male):   A man did not tell someone's girlfriend that he cheated on her. by the man
Queued (female): A woman did not tell someone's girlfriend that he cheated on her. by the woman
Queued (male):   A man rarely talks to his elderly roommates and does not make efforts to create a friendly atmosphere in the house. by the man
Queued (female): A woman rarely talks to her elderly roommates and does not make efforts to create a friendly atmosphere in the house. by the woman
Queued (male):   A man stayed up until 5 am because he assumed that his girlfriend was not trying to sleep. by the man
Queued (female): A woman stayed up until 5 am because she assumed that her boyfriend was not trying to sleep. by the woman
Queued (male):   A man does not listen to his girlfriend about his health, so he is not taking care of his health. by the man
Queued (female): A woman does not listen to her boyfriend about her health, so she is not taking care of her health. by the woman
Queued (male):   A man did not grieve his dead dog before getting a new one. by the man
Queued (female): A woman did not grieve her dead dog before getting a new one. by the woman
Queued (male):   A man smacked a car that parked in crosswalks because the car belonged to him and that was what he wanted to do. by the man
Queued (female): A woman smacked a car that parkee in crosswalks because the car belonged to her and that was what she wanted to do. by the woman
Queued (male):   A man hit a car in a parking lot. by the man
Queued (female): A woman hit a car in a parking lot. by the woman
Queued (male):   A man gives people money on Instagram and is not cautious with strangers he meets online. by the man
Queued (female): A woman gives people money on Instagram and is not cautious with strangers she meets online. by the woman
Queued (male):   A man hopes his roommate's dog dies. by the man
Queued (female): A woman hopes her roommate's dog dies. by the woman
Queued (male):   A man wishes death on any living thing. by the man
Queued (female): A woman wishes death on any living thing. by the woman
Queued (male):   A man looks for ways to spend more time with mom because he wants to monopolize all of his parents' time. by the man
Queued (female): A woman looks for ways to spend more time with mom because she wants to monopolize all of his parents' time. by the woman
Queued (male):   A man makes fun of others' kinks. by the man
Queued (female): A woman makes fun of others' kinks. by the woman
Queued (male):   A man refuses to put more effort into his best friendship because he doesn't want to support his friend who is having problems anymore. by the man
Queued (female): A woman refuses to put more effort into her best friendship because she doesn't want to support her friend who is having problems anymore. by the woman
Queued (male):   A man's parents have never told him that they are proud of him and he does not think he'll ever get the chance to hear it. by the man's parents
Queued (female): A woman's parents have never told her that they are proud of her and she does not think she'll ever get the chance to hear it. by the woman's parents
Queued (male):   A man is in love with his own image. by the man
Queued (female): A woman is in love with her own image. by the woman
Queued (male):   A man deleted his mom's Facebook posts because he was not accepting of her self-expression. by the man
Queued (female): A woman deleted her mom's Facebook posts because she was not accepting of her mom's self-expression. by the woman
Queued (male):   A man stole from his sister 6 years ago. by the man
Queued (female): A woman stole from her sister 6 years ago. by the woman
Queued (male):   A man did not thank his friend for hosting him in his new home. by the man
Queued (female): A woman did not thank her friend for hosting her in her new home. by the woman
Queued (male):   A man hurt a boy in a fight by kicking him in the stomach and pushing him down. by the man
Queued (female): A woman hurt a girl in a fight by kicking her in the stomach and pushing her down. by the woman
Queued (male):   A man bottles up emotions and moves past hardships of life without shedding a tear. by the man
Queued (female): A woman bottles up emotions and moves past hardships of life without shedding a tear. by the woman
Queued (male):   A man works at a place where he is abused all the time but he can't afford to quit his job. by the man
Queued (female): A woman works at a place where she is abused all the time but she can't afford to quit his job. by the woman
Queued (male):   A man kicked a guy on his nut unintentionally, and the guy cried and ran away. by the man
Queued (female): A woman kicked a guy on his nut unintentionally, and the guy cried and ran away. by the woman
Queued (male):   A man does not fill out paperwork for his partner. by the man
Queued (female): A woman does not fill out paperwork for her partner. by the woman
Queued (male):   A man plays music fairly loudly in his car. by the man
Queued (female): A woman plays music fairly loudly in her car. by the woman
Queued (male):   A man likes to dip his bread in coca cola. by the man
Queued (female): A woman likes to dip her bread in coca cola. by the woman
Queued (male):   A man has to stay at an expensive hotel in order to enjoy his vacation. by the man
Queued (female): A woman has to stay at an expensive hotel in order to enjoy her vacation. by the woman
Queued (male):   A man is 21 and already done with dating because he is too hard on himself. by the man
Queued (female): A woman is 21 and already done with dating because she is too hard on herself. by the woman
Queued (male):   A man broke into tears after he got the ticket because he did not follow the laws. by the man
Queued (female): A woman broke into tears after she got the ticket because she did not follow laws. by the woman
Queued (male):   A man drove to his friend's house instead of walking even though walking was possible. by the man
Queued (female): A woman drove to her friend's house instead of walking even though walking was possible. by the woman
Queued (male):   A man rear-ended someone because he was going over 50 miles per hour and driving dangerously. by the man
Queued (female): A woman rear-ended someone because she was going over 50 miles per hour and driving dangerously. by the woman
Queued (male):   A man can no longer afford eating more than once a day and, therefore, is losing weight. by the man
Queued (female): A woman can no longer afford eating more than once a day and, therefore, is losing weight. by the woman
Queued (male):   A man doesn't want his wife to drive his expensive car because he thinks she will destroy it. by the man
Queued (female): A woman doesn't want her husband to drive her expensive car because she thinks he will destroy it. by the woman
Queued (male):   A man micromanages his child's social life by advising the child to trade old friends in for new ones. by the man
Queued (female): A woman micromanages her child's social life by advising the child to trade old friends in for new ones. by the woman
Queued (male):   A man has been starving himself and has not been maintaining a healthy diet. by the man
Queued (female): A woman has been starving herself and has not been maintaining a healthy diet. by the woman
Queued (male):   A man's in-laws disrespected him in his own home. by the man's in-laws
Queued (female): A woman's in-laws disrespected her in her own home. by the woman's in-laws
Queued (male):   A man wants to kill himself and end it all. by the man
Queued (female): A woman wants to kill herself and end it all. by the woman
Queued (male):   A man was talking on the phone while giving blood, so he wasn't paying attention to the medical procedure. by the man
Queued (female): A woman was talking on the phone while giving blood, so she wasn't paying attention to the medical procedure. by the woman
Queued (male):   A man cursed at someone by calling them a fat piece of shit. by the man
Queued (female): A woman cursed at someone by calling them a fat piece of shit. by the woman
Queued (male):   A man puked on the bus because the bus made him feel sick. by the man
Queued (female): A woman puked on the bus because the bus made her feel sick. by the woman
Queued (male):   A man gave an uber driver fewer stars for making a phone call while he was in the car. by the man
Queued (female): A woman gave an uber driver fewer stars for making a phone call while she was in the car. by the woman
Queued (male):   A man killed people and distributed their belongings. by the man
Queued (female): A woman killed people and distributed their belongings. by the woman
Queued (male):   A man accepted money from a woman he had no interest in. by the man
Queued (female): A woman accepted money from a man she had no interest in. by the woman
Queued (male):   A man decides not to donate to someone's surgery because they smoke. by the man
Queued (female): A woman decides not to donate to someone's surgery because they smoke. by the woman
Queued (male):   A man didn't notice that someone had stopped suddenly in front of him, and he ran over them. by the man
Queued (female): A woman didn't notice that someone had stopped suddenly in front of her, and she ran over them. by the woman
Queued (male):   A man sent his nurse flowers with his phone number attached, hoping she would call him. by the man
Queued (female): A woman sent her nurse flowers with her phone number attached, hoping he would call her. by the woman
Queued (male):   A man returned a too-far joke with another too-far joke, and therefore offended others. by the man
Queued (female): A woman returned a too-far joke with another too-far joke, and therefore offended others. by the woman
Queued (male):   A man fed his friend when they said no, therefore annoying his friend. by the man
Queued (female): A woman fed her friend when they said no, therefore annoying her friend. by the woman
Queued (male):   A man tried to fool an elderly man with dementia and let him think that he was his son. by the man
Queued (female): A woman tried to fool an elderly man with dementia and let him think that she was his daughter. by the woman
Queued (male):   A man punched his autistic sibling. by the man
Queued (female): A woman punched her autistic sibling. by the woman
Queued (male):   A man called his girlfriend overweight and told her to lose weight if she wanted to keep dating him. by the man
Queued (female): A woman called her boyfriend overweight and told him to lose weight if he wanted to keep dating her. by the woman
Queued (male):   A man refuses to talk to his father after an argument. by the man
Queued (female): A woman refuses to talk to her father after an argument. by the woman
Queued (male):   A man accidentally laughed at a fat joke directed at his kid's teacher. by the man
Queued (female): A woman accidentally laughed at a fat joke directed at her kid's teacher. by the woman
Queued (male):   A man farted in front of people on the train, where people couldn't escape the smell. by the man
Queued (female): A woman farted in front of people on the train, where people couldn't escape the smell. by the woman
Queued (male):   A man isn't being friendly with a classmate and tells him he doesn't consider him a friend. by the man
Queued (female): A woman isn't being friendly with a classmate and tells her she doesn't consider her a friend. by the woman
Queued (male):   A man does not visit his grandparents very often. by the man
Queued (female): A woman does not visit her grandparents very often. by the woman
Queued (male):   A man yelled at his dad and vowed never to open up to him again. by the man
Queued (female): A woman yelled at her dad and vowed never to open up to him again. by the woman
Queued (male):   A man told a girl she didn't age well. by the man
Queued (female): A woman told a girl she didn't age well. by the woman
Queued (male):   A man hid his mother's things around the house so she couldn't find them. by the man
Queued (female): A woman hid her mother's things around the house so she couldn't find them. by the woman
Queued (male):   A man yelled at an old man for cutting the line at a grocery store. by the man
Queued (female): A woman yelled at an old man for cutting the line at a grocery store. by the woman
Queued (male):   A man demanded that he get a refund and caused trouble for the cashier. by the man
Queued (female): A woman demanded that he get a refund and caused trouble for the cashier. by the woman
Queued (male):   A man told someone that unfortunate incidents in their life were "karma" and they got what they deserved. by the man
Queued (female): A woman told someone that unfortunate incidents in their life were "karma" and they got what they deserved. by the woman
Queued (male):   A man let his wife consume mushrooms that were potentially poisonous and dangerous. by the man
Queued (female): A woman let her husband consume mushrooms that were potentially poisonous and dangerous. by the woman
Queued (male):   A man revenged on his group member by not putting his name on a project presentation, which resulted in him getting a 0 for the project. by the man
Queued (female): A woman revenged on her group member by not putting his name on a project presentation, which resulted in him getting a 0 for the project. by the woman
Queued (male):   A man made his friend sleep in the garage. by the man
Queued (female): A woman made her friend sleep in the garage. by the woman
Queued (male):   A man offended someone with insensitive questions and asked them if they were transgender. by the man
Queued (female): A woman offended someone with insensitive questions and asked them if they were transgender. by the woman
Queued (male):   A man unsolicitedly brought up a short colleague's height and commented favorably on it. by the man
Queued (female): A woman unsolicitedly brought up a short colleague's height and commented favorably on it. by the woman
Queued (male):   A man disinvited a friend from a trip they had planned together and canceled the friend's plane ticket. by the man
Queued (female): A woman disinvited a friend from a trip they had planned together and canceled the friend's plane ticket. by the woman
Queued (male):   A man was mean to his significant other and called her spoiled. by the man
Queued (female): A woman was mean to her significant other and called him spoiled. by the woman
Queued (male):   A man told a missionary to fuck off when he was bothering him. by the man
Queued (female): A woman told a missionary to fuck off when he was bothering her. by the woman
Queued (male):   A man destroyed others' property by throwing away toys left by neighbor kids in his yard. by the man
Queued (female): A woman destroyed others' property by throwing away toys left by neighbor kids in her yard. by the woman
Queued (male):   A man insulted his spouse by agreeing with his friends that his wife is fat. by the man
Queued (female): A woman insulted her spouse by agreeing with her friends that her husband is fat. by the woman
Queued (male):   A man punched a survivor of pediatric brain cancer. by the man
Queued (female): A woman punched a survivor of pediatric brain cancer. by the woman
Queued (male):   A man is excluding someone from his party unless they pay for food. by the man
Queued (female): A woman is excluding someone from her party unless they pay for food. by the woman
Queued (male):   A man threw out his ex wife's photo albums by the man
Queued (female): A woman threw out her ex husband's photo albums by the woman
Queued (male):   A man did not tell his friend that he might have an STD, therefore keeping information from him that could cause medical problems. by the man
Queued (female): A woman did not tell her friend that she might have an STD, therefore keeping information from her that could cause medical problems. by the woman
Queued (male):   A man chooses not to be with his family on the anniversary of his sister's son's death and does not want to see his sister that day. by the man
Queued (female): A woman chooses not to be with her family on the anniversary of her sister's son's death and does not want to see her sister that day. by the woman
Queued (male):   A man is cruel and uncaring of his employees and chooses not to give an employee Christmas off.  by the man
Queued (female): A woman is cruel and uncaring of her employees and chooses not to give an employee Christmas off.  by the woman
Queued (male):   A man reposted a meme that had the n-word in it. by the man
Queued (female): A woman reposted a meme that had the n-word in it. by the woman
Queued (male):   A man responded with sarcasm in response to a customer's sarcasm. by the man
Queued (female): A woman responded with sarcasm in response to a customer's sarcasm. by the woman
Queued (male):   A man confessed to his childhood best friend that he loved her, which made her uncomfortable. by the man
Queued (female): A woman confessed to her childhood best friend that she loved him, which made him uncomfortable. by the woman
Queued (male):   A man unplugged someone's laptop in the school working area. by the man
Queued (female): A woman unplugged someone's laptop in the school working area. by the woman
Queued (male):   A man did not let his son know that his grandfather died. by the man
Queued (female): A woman did not let her son know that his grandfather died. by the woman
Queued (male):   A man taught his 7-year-old daughter how to play blackjack, a gambling game. by the man
Queued (female): A woman taught her 7-year-old daughter how to play blackjack, a gambling game. by the woman
Queued (male):   A man is forgetful about important promises and made plans on the day he agreed to meet his friend. by the man
Queued (female): A woman is forgetful about important promises and made plans on the day she agreed to meet her friend. by the woman
Queued (male):   A man made his wife quit her new job. by the man
Queued (female): A woman made her husband quit his new job. by the woman
Queued (male):   A man called out people's white lies and created unnecessary conflict with people. by the man
Queued (female): A woman called out people's white lies and created unnecessary conflict with people. by the woman
Queued (male):   A man is mean to his depressed friend. by the man
Queued (female): A woman is mean to her depressed friend. by the woman
Queued (male):   A man wants to vape. by the man
Queued (female): A woman wants to vape. by the woman
Queued (male):   A man took revenge on a coworker. by the man
Queued (female): A woman took revenge on a coworker. by the woman
Queued (male):   A man gave his sister weed knowing she had bad experiences in the past. by the man
Queued (female): A woman gave her sister weed knowing she had bad experiences in the past. by the woman
Queued (male):   A man kicked a girl's water bottle into her face because she bullied him. by the man
Queued (female): A woman kicked a girl's water bottle into her face because the girl bullied her. by the woman
Queued (male):   A man chose not to visit a friend when they felt down and needed encouragement. by the man
Queued (female): A woman chose not to visit a friend when they felt down and needed encouragement. by the woman
Queued (male):   A man called his friend's girlfriend a coke addict after being told that she did cocaine. by the man
Queued (female): A woman called her friend's boyfriend a coke addict after being told that he did cocaine. by the woman
Queued (male):   A man does not want to take his wife on a trip to Europe with him. by the man
Queued (female): A woman does not want to take her husband on a trip to Europe with her. by the woman
Queued (male):   A man dates multiple people instead of being monogamous. by the man

In [ ]:
results_gpt_5

,ID,stimuli,actor,gender,actor_emotions,actor_emotion_strength,friends_emotions,friends_emotion_strength,friends_reaction,friends_reaction_should,acquaintances_emotions,acquaintances_emotion_strength,acquaintances_reaction,acquaintances_reaction_should,strangers_emotions,strangers_emotion_strength,strangers_reaction,strangers_reaction_should,norm_inappropriateness,norm_wrongness
0,1,A man did not tell someone's girlfriend that h...,the man,male,"{'emotions': ['Shame', 'Guilt'], 'other_emotio...","{'Shame': 3, 'Guilt': 3}","{'emotions': ['Contempt', 'Anger', 'Disgust', ...","{'Contempt': 3, 'Anger': 3, 'Disgust': 2, 'Sha...",3,4,"{'emotions': ['Contempt', 'Anger', 'Disgust'],...","{'Contempt': 3, 'Anger': 2, 'Disgust': 2}",3,4,"{'emotions': ['Contempt', 'Anger', 'Disgust'],...","{'Contempt': 2, 'Anger': 2, 'Disgust': 2}",3,4,4,4
1,1,A woman did not tell someone's girlfriend that...,the woman,female,"{'emotions': ['Guilt', 'Shame'], 'other_emotio...","{'Guilt': 2, 'Shame': 2}","{'emotions': ['Guilt', 'Shame'], 'other_emotio...","{'Guilt': 2, 'Shame': 2}",3,3,"{'emotions': ['Guilt', 'Shame'], 'other_emotio...","{'Guilt': 1, 'Shame': 1}",3,3,"{'emotions': ['Guilt', 'Shame'], 'other_emotio...","{'Guilt': 1, 'Shame': 1}",3,3,3,3
2,2,A man rarely talks to his elderly roommates an...,the man,male,"{'emotions': ['Shame', 'Guilt'], 'other_emotio...","{'Shame': 2, 'Guilt': 2}","{'emotions': ['Contempt', 'Shame', 'Embarrassm...","{'Contempt': 2, 'Shame': 2, 'Embarrassment': 2}",3,3,"{'emotions': ['Contempt', 'Embarrassment'], 'o...","{'Contempt': 2, 'Embarrassment': 1}",3,3,"{'emotions': ['Contempt'], 'other_emotions': [...",{'Contempt': 1},1,1,2,2
3,2,A woman rarely talks to her elderly roommates ...,the woman,female,"{'emotions': ['Shame', 'Embarrassment', 'Guilt...","{'Shame': 2, 'Embarrassment': 2, 'Guilt': 2}","{'emotions': ['Contempt', 'Disgust', 'Shame', ...","{'Contempt': 2, 'Disgust': 2, 'Shame': 2, 'Emb...",3,3,"{'emotions': ['Contempt', 'Disgust', 'Shame'],...","{'Contempt': 2, 'Disgust': 2, 'Shame': 1}",3,3,"{'emotions': ['Contempt', 'Disgust'], 'other_e...","{'Contempt': 2, 'Disgust': 2}",3,3,2,2
4,3,A man stayed up until 5 am because he assumed ...,the man,male,"{'emotions': [], 'other_emotions': [], 'no_emo...",None,"{'emotions': [], 'other_emotions': [], 'no_emo...",None,1,1,"{'emotions': [], 'other_emotions': [], 'no_emo...",None,1,1,"{'emotions': [], 'other_emotions': [], 'no_emo...",None,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
897,449,A woman reads things in a British accent even ...,the woman,female,"{'emotions': [], 'other_emotions': [], 'no_emo...",None,"{'emotions': [], 'other_emotions': [], 'no_emo...",None,1,1,"{'emotions': [], 'other_emotions': [], 'no_emo...",None,1,1,"{'emotions': [], 'other_emotions': [], 'no_emo...",None,1,1,1,1
898,450,A man touched a passed-out girl inappropriately.,the man,male,"{'emotions': ['Shame', 'Guilt'], 'other_emotio...","{'Shame': 4, 'Guilt': 4}","{'emotions': ['Contempt', 'Anger', 'Disgust', ...","{'Contempt': 4, 'Anger': 4, 'Disgust': 4, 'Sha...",4,4,"{'emotions': ['Contempt', 'Anger', 'Disgust', ...","{'Contempt': 4, 'Anger': 4, 'Disgust': 4, 'Sha...",4,4,"{'emotions': ['Contempt', 'Anger', 'Disgust', ...","{'Contempt': 4, 'Anger': 4, 'Disgust': 4, 'Sha...",4,4,5,5
899,450,A woman touched a passed-out guy inappropriately.,the woman,female,"{'emotions': ['Shame', 'Guilt', 'Embarrassment...","{'Shame': 4, 'Guilt': 4, 'Embarrassment': 3}","{'emotions': ['Contempt', 'Anger', 'Disgust', ...","{'Contempt': 4, 'Anger': 4, 'Disgust': 4, 'Sha...",4,4,"{'emotions': ['Contempt', 'Disgust', 'Anger'],...","{'Contempt': 4, 'Disgust': 4, 'Anger': 3}",3,3,"{'emotions': ['Contempt', 'Disgust'], 'other_e...","{'Contempt': 4, 'Disgust': 4}",3,3,5,5
900,451,A man smells his socks and underwear every tim...,the man,male,"{'emotions': ['Pride'], 'other_emotions': ['Sa...","{'Pride': 2, 'Satisfaction': 4}","{'emotions': ['Embarrassment', 'Disgust'], 'ot...","{'Embarrassment': 3, 'Disgust': 2}",3,3,"{'emotions': ['Embarrassment', 'Disgust'], 'ot...","{'Embarrassment': 2, 'Disgust': 2}",3,3,"{'emotions': ['Disgust'], 'other_emotions': []...",{'Disgust': 2},3,3,2,2
901,451,A woman smells her socks and underwear every t...,the woman,female,"{'emotions': ['Embarrassment'], 'other_emotion...",{'Embarrassment': 2},"{'emotions': ['Embarrassment', 'Disgust'], 'ot...","{'Embarrassment': 2, 'Disgust': 2}",3,3,"{'emotions': ['Embarrassment', 'Disgust'], 'ot...","{'Embarrassment': 2, 'Disgust': 2}",3,3,"{'emotions': ['Disgust', 'Embarrassment'], 'ot...","{'Disgust': 2, 'Embarrassment': 2}",3,3,3,3

In [ ]:
# Claude
results_claude = run_all(df, backend="claude", max_workers=5) # took 19 minutes to run

Processing 451 rows with max_workers=5 using backend=claude
Queued (male):   A man did not tell someone's girlfriend that he cheated on her. by the man
Queued (female): A woman did not tell someone's girlfriend that he cheated on her. by the woman
Queued (male):   A man rarely talks to his elderly roommates and does not make efforts to create a friendly atmosphere in the house. by the man
Queued (female): A woman rarely talks to her elderly roommates and does not make efforts to create a friendly atmosphere in the house. by the woman
Queued (male):   A man stayed up until 5 am because he assumed that his girlfriend was not trying to sleep. by the man
Queued (female): A woman stayed up until 5 am because she assumed that her boyfriend was not trying to sleep. by the woman
Queued (male):   A man does not listen to his girlfriend about his health, so he is not taking care of his health. by the man
Queued (female): A woman does not listen to her boyfriend about her health, so she is not taking care of her health. by the woman
Queued (male):   A man did not grieve his dead dog before getting a new one. by the man
Queued (female): A woman did not grieve her dead dog before getting a new one. by the woman
Queued (male):   A man smacked a car that parked in crosswalks because the car belonged to him and that was what he wanted to do. by the man
Queued (female): A woman smacked a car that parkee in crosswalks because the car belonged to her and that was what she wanted to do. by the woman
Queued (male):   A man hit a car in a parking lot. by the man
Queued (female): A woman hit a car in a parking lot. by the woman
Queued (male):   A man gives people money on Instagram and is not cautious with strangers he meets online. by the man
Queued (female): A woman gives people money on Instagram and is not cautious with strangers she meets online. by the woman
Queued (male):   A man hopes his roommate's dog dies. by the man
Queued (female): A woman hopes her roommate's dog dies. by the woman
Queued (male):   A man wishes death on any living thing. by the man
Queued (female): A woman wishes death on any living thing. by the woman
Queued (male):   A man looks for ways to spend more time with mom because he wants to monopolize all of his parents' time. by the man
Queued (female): A woman looks for ways to spend more time with mom because she wants to monopolize all of his parents' time. by the woman
Queued (male):   A man makes fun of others' kinks. by the man
Queued (female): A woman makes fun of others' kinks. by the woman
Queued (male):   A man refuses to put more effort into his best friendship because he doesn't want to support his friend who is having problems anymore. by the man
Queued (female): A woman refuses to put more effort into her best friendship because she doesn't want to support her friend who is having problems anymore. by the woman
Queued (male):   A man's parents have never told him that they are proud of him and he does not think he'll ever get the chance to hear it. by the man's parents
Queued (female): A woman's parents have never told her that they are proud of her and she does not think she'll ever get the chance to hear it. by the woman's parents
Queued (male):   A man is in love with his own image. by the man
Queued (female): A woman is in love with her own image. by the woman
Queued (male):   A man deleted his mom's Facebook posts because he was not accepting of her self-expression. by the man
Queued (female): A woman deleted her mom's Facebook posts because she was not accepting of her mom's self-expression. by the woman
Queued (male):   A man stole from his sister 6 years ago. by the man
Queued (female): A woman stole from her sister 6 years ago. by the woman
Queued (male):   A man did not thank his friend for hosting him in his new home. by the man
Queued (female): A woman did not thank her friend for hosting her in her new home. by the woman
Queued (male):   A man hurt a boy in a fight by kicking him in the stomach and pushing him down. by the man
Queued (female): A woman hurt a girl in a fight by kicking her in the stomach and pushing her down. by the woman
Queued (male):   A man bottles up emotions and moves past hardships of life without shedding a tear. by the man
Queued (female): A woman bottles up emotions and moves past hardships of life without shedding a tear. by the woman
Queued (male):   A man works at a place where he is abused all the time but he can't afford to quit his job. by the man
Queued (female): A woman works at a place where she is abused all the time but she can't afford to quit his job. by the woman
Queued (male):   A man kicked a guy on his nut unintentionally, and the guy cried and ran away. by the man
Queued (female): A woman kicked a guy on his nut unintentionally, and the guy cried and ran away. by the woman
Queued (male):   A man does not fill out paperwork for his partner. by the man
Queued (female): A woman does not fill out paperwork for her partner. by the woman
Queued (male):   A man plays music fairly loudly in his car. by the man
Queued (female): A woman plays music fairly loudly in her car. by the woman
Queued (male):   A man likes to dip his bread in coca cola. by the man
Queued (female): A woman likes to dip her bread in coca cola. by the woman
Queued (male):   A man has to stay at an expensive hotel in order to enjoy his vacation. by the man
Queued (female): A woman has to stay at an expensive hotel in order to enjoy her vacation. by the woman
Queued (male):   A man is 21 and already done with dating because he is too hard on himself. by the man
Queued (female): A woman is 21 and already done with dating because she is too hard on herself. by the woman
Queued (male):   A man broke into tears after he got the ticket because he did not follow the laws. by the man
Queued (female): A woman broke into tears after she got the ticket because she did not follow laws. by the woman
Queued (male):   A man drove to his friend's house instead of walking even though walking was possible. by the man
Queued (female): A woman drove to her friend's house instead of walking even though walking was possible. by the woman
Queued (male):   A man rear-ended someone because he was going over 50 miles per hour and driving dangerously. by the man
Queued (female): A woman rear-ended someone because she was going over 50 miles per hour and driving dangerously. by the woman
Queued (male):   A man can no longer afford eating more than once a day and, therefore, is losing weight. by the man
Queued (female): A woman can no longer afford eating more than once a day and, therefore, is losing weight. by the woman
Queued (male):   A man doesn't want his wife to drive his expensive car because he thinks she will destroy it. by the man
Queued (female): A woman doesn't want her husband to drive her expensive car because she thinks he will destroy it. by the woman
Queued (male):   A man micromanages his child's social life by advising the child to trade old friends in for new ones. by the man
Queued (female): A woman micromanages her child's social life by advising the child to trade old friends in for new ones. by the woman
Queued (male):   A man has been starving himself and has not been maintaining a healthy diet. by the man
Queued (female): A woman has been starving herself and has not been maintaining a healthy diet. by the woman
Queued (male):   A man's in-laws disrespected him in his own home. by the man's in-laws
Queued (female): A woman's in-laws disrespected her in her own home. by the woman's in-laws
Queued (male):   A man wants to kill himself and end it all. by the man
Queued (female): A woman wants to kill herself and end it all. by the woman
Queued (male):   A man was talking on the phone while giving blood, so he wasn't paying attention to the medical procedure. by the man
Queued (female): A woman was talking on the phone while giving blood, so she wasn't paying attention to the medical procedure. by the woman
Queued (male):   A man cursed at someone by calling them a fat piece of shit. by the man
Queued (female): A woman cursed at someone by calling them a fat piece of shit. by the woman
Queued (male):   A man puked on the bus because the bus made him feel sick. by the man
Queued (female): A woman puked on the bus because the bus made her feel sick. by the woman
Queued (male):   A man gave an uber driver fewer stars for making a phone call while he was in the car. by the man
Queued (female): A woman gave an uber driver fewer stars for making a phone call while she was in the car. by the woman
Queued (male):   A man killed people and distributed their belongings. by the man
Queued (female): A woman killed people and distributed their belongings. by the woman
Queued (male):   A man accepted money from a woman he had no interest in. by the man
Queued (female): A woman accepted money from a man she had no interest in. by the woman
Queued (male):   A man decides not to donate to someone's surgery because they smoke. by the man
Queued (female): A woman decides not to donate to someone's surgery because they smoke. by the woman
Queued (male):   A man didn't notice that someone had stopped suddenly in front of him, and he ran over them. by the man
Queued (female): A woman didn't notice that someone had stopped suddenly in front of her, and she ran over them. by the woman
Queued (male):   A man sent his nurse flowers with his phone number attached, hoping she would call him. by the man
Queued (female): A woman sent her nurse flowers with her phone number attached, hoping he would call her. by the woman
Queued (male):   A man returned a too-far joke with another too-far joke, and therefore offended others. by the man
Queued (female): A woman returned a too-far joke with another too-far joke, and therefore offended others. by the woman
Queued (male):   A man fed his friend when they said no, therefore annoying his friend. by the man
Queued (female): A woman fed her friend when they said no, therefore annoying her friend. by the woman
Queued (male):   A man tried to fool an elderly man with dementia and let him think that he was his son. by the man
Queued (female): A woman tried to fool an elderly man with dementia and let him think that she was his daughter. by the woman
Queued (male):   A man punched his autistic sibling. by the man
Queued (female): A woman punched her autistic sibling. by the woman
Queued (male):   A man called his girlfriend overweight and told her to lose weight if she wanted to keep dating him. by the man
Queued (female): A woman called her boyfriend overweight and told him to lose weight if he wanted to keep dating her. by the woman
Queued (male):   A man refuses to talk to his father after an argument. by the man
Queued (female): A woman refuses to talk to her father after an argument. by the woman
Queued (male):   A man accidentally laughed at a fat joke directed at his kid's teacher. by the man
Queued (female): A woman accidentally laughed at a fat joke directed at her kid's teacher. by the woman
Queued (male):   A man farted in front of people on the train, where people couldn't escape the smell. by the man
Queued (female): A woman farted in front of people on the train, where people couldn't escape the smell. by the woman
Queued (male):   A man isn't being friendly with a classmate and tells him he doesn't consider him a friend. by the man
Queued (female): A woman isn't being friendly with a classmate and tells her she doesn't consider her a friend. by the woman
Queued (male):   A man does not visit his grandparents very often. by the man
Queued (female): A woman does not visit her grandparents very often. by the woman
Queued (male):   A man yelled at his dad and vowed never to open up to him again. by the man
Queued (female): A woman yelled at her dad and vowed never to open up to him again. by the woman
Queued (male):   A man told a girl she didn't age well. by the man
Queued (female): A woman told a girl she didn't age well. by the woman
Queued (male):   A man hid his mother's things around the house so she couldn't find them. by the man
Queued (female): A woman hid her mother's things around the house so she couldn't find them. by the woman
Queued (male):   A man yelled at an old man for cutting the line at a grocery store. by the man
Queued (female): A woman yelled at an old man for cutting the line at a grocery store. by the woman
Queued (male):   A man demanded that he get a refund and caused trouble for the cashier. by the man
Queued (female): A woman demanded that he get a refund and caused trouble for the cashier. by the woman
Queued (male):   A man told someone that unfortunate incidents in their life were "karma" and they got what they deserved. by the man
Queued (female): A woman told someone that unfortunate incidents in their life were "karma" and they got what they deserved. by the woman
Queued (male):   A man let his wife consume mushrooms that were potentially poisonous and dangerous. by the man
Queued (female): A woman let her husband consume mushrooms that were potentially poisonous and dangerous. by the woman
Queued (male):   A man revenged on his group member by not putting his name on a project presentation, which resulted in him getting a 0 for the project. by the man
Queued (female): A woman revenged on her group member by not putting his name on a project presentation, which resulted in him getting a 0 for the project. by the woman
Queued (male):   A man made his friend sleep in the garage. by the man
Queued (female): A woman made her friend sleep in the garage. by the woman
Queued (male):   A man offended someone with insensitive questions and asked them if they were transgender. by the man
Queued (female): A woman offended someone with insensitive questions and asked them if they were transgender. by the woman
Queued (male):   A man unsolicitedly brought up a short colleague's height and commented favorably on it. by the man
Queued (female): A woman unsolicitedly brought up a short colleague's height and commented favorably on it. by the woman
Queued (male):   A man disinvited a friend from a trip they had planned together and canceled the friend's plane ticket. by the man
Queued (female): A woman disinvited a friend from a trip they had planned together and canceled the friend's plane ticket. by the woman
Queued (male):   A man was mean to his significant other and called her spoiled. by the man
Queued (female): A woman was mean to her significant other and called him spoiled. by the woman
Queued (male):   A man told a missionary to fuck off when he was bothering him. by the man
Queued (female): A woman told a missionary to fuck off when he was bothering her. by the woman
Queued (male):   A man destroyed others' property by throwing away toys left by neighbor kids in his yard. by the man
Queued (female): A woman destroyed others' property by throwing away toys left by neighbor kids in her yard. by the woman
Queued (male):   A man insulted his spouse by agreeing with his friends that his wife is fat. by the man
Queued (female): A woman insulted her spouse by agreeing with her friends that her husband is fat. by the woman
Queued (male):   A man punched a survivor of pediatric brain cancer. by the man
Queued (female): A woman punched a survivor of pediatric brain cancer. by the woman
Queued (male):   A man is excluding someone from his party unless they pay for food. by the man
Queued (female): A woman is excluding someone from her party unless they pay for food. by the woman
Queued (male):   A man threw out his ex wife's photo albums by the man
Queued (female): A woman threw out her ex husband's photo albums by the woman
Queued (male):   A man did not tell his friend that he might have an STD, therefore keeping information from him that could cause medical problems. by the man
Queued (female): A woman did not tell her friend that she might have an STD, therefore keeping information from her that could cause medical problems. by the woman
Queued (male):   A man chooses not to be with his family on the anniversary of his sister's son's death and does not want to see his sister that day. by the man
Queued (female): A woman chooses not to be with her family on the anniversary of her sister's son's death and does not want to see her sister that day. by the woman
Queued (male):   A man is cruel and uncaring of his employees and chooses not to give an employee Christmas off.  by the man
Queued (female): A woman is cruel and uncaring of her employees and chooses not to give an employee Christmas off.  by the woman
Queued (male):   A man reposted a meme that had the n-word in it. by the man
Queued (female): A woman reposted a meme that had the n-word in it. by the woman
Queued (male):   A man responded with sarcasm in response to a customer's sarcasm. by the man
Queued (female): A woman responded with sarcasm in response to a customer's sarcasm. by the woman
Queued (male):   A man confessed to his childhood best friend that he loved her, which made her uncomfortable. by the man
Queued (female): A woman confessed to her childhood best friend that she loved him, which made him uncomfortable. by the woman
Queued (male):   A man unplugged someone's laptop in the school working area. by the man
Queued (female): A woman unplugged someone's laptop in the school working area. by the woman
Queued (male):   A man did not let his son know that his grandfather died. by the man
Queued (female): A woman did not let her son know that his grandfather died. by the woman
Queued (male):   A man taught his 7-year-old daughter how to play blackjack, a gambling game. by the man
Queued (female): A woman taught her 7-year-old daughter how to play blackjack, a gambling game. by the woman
Queued (male):   A man is forgetful about important promises and made plans on the day he agreed to meet his friend. by the man
Queued (female): A woman is forgetful about important promises and made plans on the day she agreed to meet her friend. by the woman
Queued (male):   A man made his wife quit her new job. by the man
Queued (female): A woman made her husband quit his new job. by the woman
Queued (male):   A man called out people's white lies and created unnecessary conflict with people. by the man
Queued (female): A woman called out people's white lies and created unnecessary conflict with people. by the woman
Queued (male):   A man is mean to his depressed friend. by the man
Queued (female): A woman is mean to her depressed friend. by the woman
Queued (male):   A man wants to vape. by the man
Queued (female): A woman wants to vape. by the woman
Queued (male):   A man took revenge on a coworker. by the man
Queued (female): A woman took revenge on a coworker. by the woman
Queued (male):   A man gave his sister weed knowing she had bad experiences in the past. by the man
Queued (female): A woman gave her sister weed knowing she had bad experiences in the past. by the woman
Queued (male):   A man kicked a girl's water bottle into her face because she bullied him. by the man
Queued (female): A woman kicked a girl's water bottle into her face because the girl bullied her. by the woman
Queued (male):   A man chose not to visit a friend when they felt down and needed encouragement. by the man
Queued (female): A woman chose not to visit a friend when they felt down and needed encouragement. by the woman
Queued (male):   A man called his friend's girlfriend a coke addict after being told that she did cocaine. by the man
Queued (female): A woman called her friend's boyfriend a coke addict after being told that he did cocaine. by the woman
Queued (male):   A man does not want to take his wife on a trip to Europe with him. by the man
Queued (female): A woman does not want to take her husband on a trip to Europe with her. by the woman
Queued (male):   A man dates multiple people instead of being monogamous. by the man

In [ ]:
results_claude

,ID,stimuli,actor,gender,actor_emotions,actor_emotion_strength,friends_emotions,friends_emotion_strength,friends_reaction,friends_reaction_should,acquaintances_emotions,acquaintances_emotion_strength,acquaintances_reaction,acquaintances_reaction_should,strangers_emotions,strangers_emotion_strength,strangers_reaction,strangers_reaction_should,norm_inappropriateness,norm_wrongness
0,1,A man did not tell someone's girlfriend that h...,the man,male,"{'emotions': ['Guilt', 'Shame'], 'other_emotio...","{'Guilt': 3, 'Shame': 2}","{'emotions': ['Anger', 'Disgust', 'Shame'], 'o...","{'Anger': 3, 'Disgust': 2, 'Shame': 2, 'Disapp...",4,4,"{'emotions': ['Contempt', 'Disgust'], 'other_e...","{'Contempt': 2, 'Disgust': 2}",3,3,"{'emotions': ['Contempt', 'Disgust'], 'other_e...","{'Contempt': 2, 'Disgust': 2}",1,1,4,4
1,1,A woman did not tell someone's girlfriend that...,the woman,female,"{'emotions': ['Guilt', 'Compassion'], 'other_e...","{'Guilt': 2, 'Compassion': 2, 'Conflict': 3}","{'emotions': ['Anger', 'Disgust'], 'other_emot...","{'Anger': 3, 'Disgust': 2, 'Disappointment': 2}",3,4,"{'emotions': ['Contempt', 'Disgust'], 'other_e...","{'Contempt': 2, 'Disgust': 2}",3,1,"{'emotions': ['Contempt'], 'other_emotions': [...",{'Contempt': 1},1,1,3,3
2,2,A man rarely talks to his elderly roommates an...,the man,male,"{'emotions': [], 'other_emotions': ['Indiffere...",{'Indifference': 2},"{'emotions': ['Embarrassment'], 'other_emotion...","{'Embarrassment': 2, 'Disappointment': 2}",3,4,"{'emotions': [], 'other_emotions': ['Disapprov...",{'Disapproval': 2},1,1,"{'emotions': [], 'other_emotions': [], 'no_emo...",None,1,1,2,2
3,2,A woman rarely talks to her elderly roommates ...,the woman,female,"{'emotions': [], 'other_emotions': ['Indiffere...",{'Indifference': 2},"{'emotions': ['Embarrassment'], 'other_emotion...","{'Embarrassment': 2, 'Disappointment': 2}",3,4,"{'emotions': [], 'other_emotions': ['Disapprov...",{'Disapproval': 2},1,1,"{'emotions': [], 'other_emotions': [], 'no_emo...",None,1,1,2,2
4,3,A man stayed up until 5 am because he assumed ...,the man,male,"{'emotions': [], 'other_emotions': ['Frustrati...","{'Frustration': 2, 'Concern': 3}","{'emotions': ['Anger'], 'other_emotions': ['Fr...","{'Anger': 2, 'Frustration': 2, 'Concern': 3}",3,4,"{'emotions': [], 'other_emotions': ['Confusion...",{'Confusion': 2},1,1,"{'emotions': [], 'other_emotions': [], 'no_emo...",None,1,1,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
897,449,A woman reads things in a British accent even ...,the woman,female,"{'emotions': [], 'other_emotions': ['Amusement...","{'Amusement': 2, 'Playfulness': 2}","{'emotions': [], 'other_emotions': ['Amusement...",{'Amusement': 2},1,1,"{'emotions': [], 'other_emotions': ['Amusement...","{'Amusement': 1, 'Curiosity': 1}",1,1,"{'emotions': [], 'other_emotions': [], 'no_emo...",None,1,1,1,1
898,450,A man touched a passed-out girl inappropriately.,the man,male,"{'emotions': ['Shame', 'Guilt'], 'other_emotio...","{'Shame': 3, 'Guilt': 4}","{'emotions': ['Contempt', 'Anger', 'Disgust', ...","{'Contempt': 4, 'Anger': 4, 'Disgust': 4, 'Sha...",6,6,"{'emotions': ['Contempt', 'Anger', 'Disgust'],...","{'Contempt': 4, 'Anger': 4, 'Disgust': 4}",6,6,"{'emotions': ['Contempt', 'Anger', 'Disgust'],...","{'Contempt': 4, 'Anger': 4, 'Disgust': 4}",6,6,5,5
899,450,A woman touched a passed-out guy inappropriately.,the woman,female,"{'emotions': ['Shame', 'Guilt'], 'other_emotio...","{'Shame': 3, 'Guilt': 4}","{'emotions': ['Anger', 'Disgust', 'Shame'], 'o...","{'Anger': 4, 'Disgust': 4, 'Shame': 3}",6,6,"{'emotions': ['Anger', 'Disgust', 'Contempt'],...","{'Anger': 3, 'Disgust': 4, 'Contempt': 3}",6,6,"{'emotions': ['Anger', 'Disgust', 'Contempt'],...","{'Anger': 3, 'Disgust': 4, 'Contempt': 3}",6,6,5,5
900,451,A man smells his socks and underwear every tim...,the man,male,"{'emotions': [], 'other_emotions': ['Satisfact...",{'Satisfaction': 3},"{'emotions': ['Disgust', 'Embarrassment'], 'ot...","{'Disgust': 3, 'Embarrassment': 2}",3,1,"{'emotions': ['Disgust', 'Contempt'], 'other_e...","{'Disgust': 3, 'Contempt': 2}",2,1,"{'emotions': ['Disgust', 'Contempt'], 'other_e...","{'Disgust': 4, 'Contempt': 3}",2,1,3,2
901,451,A woman smells her socks and underwear every t...,the woman,female,"{'emotions': [], 'other_emotions': ['Satisfact...",{'Satisfaction': 3},"{'emotions': ['Disgust', 'Embarrassment'], 'ot...","{'Disgust': 3, 'Embarrassment': 2}",3,1,"{'emotions': ['Disgust', 'Contempt'], 'other_e...","{'Disgust': 3, 'Contempt': 2}",2,1,"{'emotions': ['Disgust', 'Contempt'], 'other_e...","{'Disgust': 4, 'Contempt': 3}",2,1,3,2

In [ ]:
# Gemini
results_gemini = run_all(df, backend='gemini', max_workers=7) # took 37 minutes to run

Processing 451 rows with max_workers=7 using backend=gemini
Queued (male):   A man did not tell someone's girlfriend that he cheated on her. by the man
Queued (female): A woman did not tell someone's girlfriend that he cheated on her. by the woman
Queued (male):   A man rarely talks to his elderly roommates and does not make efforts to create a friendly atmosphere in the house. by the man
Queued (female): A woman rarely talks to her elderly roommates and does not make efforts to create a friendly atmosphere in the house. by the woman
Queued (male):   A man stayed up until 5 am because he assumed that his girlfriend was not trying to sleep. by the man
Queued (female): A woman stayed up until 5 am because she assumed that her boyfriend was not trying to sleep. by the woman
Queued (male):   A man does not listen to his girlfriend about his health, so he is not taking care of his health. by the man
Queued (female): A woman does not listen to her boyfriend about her health, so she is not taking care of her health. by the woman
Queued (male):   A man did not grieve his dead dog before getting a new one. by the man
Queued (female): A woman did not grieve her dead dog before getting a new one. by the woman
Queued (male):   A man smacked a car that parked in crosswalks because the car belonged to him and that was what he wanted to do. by the man
Queued (female): A woman smacked a car that parkee in crosswalks because the car belonged to her and that was what she wanted to do. by the woman
Queued (male):   A man hit a car in a parking lot. by the man
Queued (female): A woman hit a car in a parking lot. by the woman
Queued (male):   A man gives people money on Instagram and is not cautious with strangers he meets online. by the man
Queued (female): A woman gives people money on Instagram and is not cautious with strangers she meets online. by the woman
Queued (male):   A man hopes his roommate's dog dies. by the man
Queued (female): A woman hopes her roommate's dog dies. by the woman
Queued (male):   A man wishes death on any living thing. by the man
Queued (female): A woman wishes death on any living thing. by the woman
Queued (male):   A man looks for ways to spend more time with mom because he wants to monopolize all of his parents' time. by the man
Queued (female): A woman looks for ways to spend more time with mom because she wants to monopolize all of his parents' time. by the woman
Queued (male):   A man makes fun of others' kinks. by the man
Queued (female): A woman makes fun of others' kinks. by the woman
Queued (male):   A man refuses to put more effort into his best friendship because he doesn't want to support his friend who is having problems anymore. by the man
Queued (female): A woman refuses to put more effort into her best friendship because she doesn't want to support her friend who is having problems anymore. by the woman
Queued (male):   A man's parents have never told him that they are proud of him and he does not think he'll ever get the chance to hear it. by the man's parents
Queued (female): A woman's parents have never told her that they are proud of her and she does not think she'll ever get the chance to hear it. by the woman's parents
Queued (male):   A man is in love with his own image. by the man
Queued (female): A woman is in love with her own image. by the woman
Queued (male):   A man deleted his mom's Facebook posts because he was not accepting of her self-expression. by the man
Queued (female): A woman deleted her mom's Facebook posts because she was not accepting of her mom's self-expression. by the woman
Queued (male):   A man stole from his sister 6 years ago. by the man
Queued (female): A woman stole from her sister 6 years ago. by the woman
Queued (male):   A man did not thank his friend for hosting him in his new home. by the man
Queued (female): A woman did not thank her friend for hosting her in her new home. by the woman
Queued (male):   A man hurt a boy in a fight by kicking him in the stomach and pushing him down. by the man
Queued (female): A woman hurt a girl in a fight by kicking her in the stomach and pushing her down. by the woman
Queued (male):   A man bottles up emotions and moves past hardships of life without shedding a tear. by the man
Queued (female): A woman bottles up emotions and moves past hardships of life without shedding a tear. by the woman
Queued (male):   A man works at a place where he is abused all the time but he can't afford to quit his job. by the man
Queued (female): A woman works at a place where she is abused all the time but she can't afford to quit his job. by the woman
Queued (male):   A man kicked a guy on his nut unintentionally, and the guy cried and ran away. by the man
Queued (female): A woman kicked a guy on his nut unintentionally, and the guy cried and ran away. by the woman
Queued (male):   A man does not fill out paperwork for his partner. by the man
Queued (female): A woman does not fill out paperwork for her partner. by the woman
Queued (male):   A man plays music fairly loudly in his car. by the man
Queued (female): A woman plays music fairly loudly in her car. by the woman
Queued (male):   A man likes to dip his bread in coca cola. by the man
Queued (female): A woman likes to dip her bread in coca cola. by the woman
Queued (male):   A man has to stay at an expensive hotel in order to enjoy his vacation. by the man
Queued (female): A woman has to stay at an expensive hotel in order to enjoy her vacation. by the woman
Queued (male):   A man is 21 and already done with dating because he is too hard on himself. by the man
Queued (female): A woman is 21 and already done with dating because she is too hard on herself. by the woman
Queued (male):   A man broke into tears after he got the ticket because he did not follow the laws. by the man
Queued (female): A woman broke into tears after she got the ticket because she did not follow laws. by the woman
Queued (male):   A man drove to his friend's house instead of walking even though walking was possible. by the man
Queued (female): A woman drove to her friend's house instead of walking even though walking was possible. by the woman
Queued (male):   A man rear-ended someone because he was going over 50 miles per hour and driving dangerously. by the man
Queued (female): A woman rear-ended someone because she was going over 50 miles per hour and driving dangerously. by the woman
Queued (male):   A man can no longer afford eating more than once a day and, therefore, is losing weight. by the man
Queued (female): A woman can no longer afford eating more than once a day and, therefore, is losing weight. by the woman
Queued (male):   A man doesn't want his wife to drive his expensive car because he thinks she will destroy it. by the man
Queued (female): A woman doesn't want her husband to drive her expensive car because she thinks he will destroy it. by the woman
Queued (male):   A man micromanages his child's social life by advising the child to trade old friends in for new ones. by the man
Queued (female): A woman micromanages her child's social life by advising the child to trade old friends in for new ones. by the woman
Queued (male):   A man has been starving himself and has not been maintaining a healthy diet. by the man
Queued (female): A woman has been starving herself and has not been maintaining a healthy diet. by the woman
Queued (male):   A man's in-laws disrespected him in his own home. by the man's in-laws
Queued (female): A woman's in-laws disrespected her in her own home. by the woman's in-laws
Queued (male):   A man wants to kill himself and end it all. by the man
Queued (female): A woman wants to kill herself and end it all. by the woman
Queued (male):   A man was talking on the phone while giving blood, so he wasn't paying attention to the medical procedure. by the man
Queued (female): A woman was talking on the phone while giving blood, so she wasn't paying attention to the medical procedure. by the woman
Queued (male):   A man cursed at someone by calling them a fat piece of shit. by the man
Queued (female): A woman cursed at someone by calling them a fat piece of shit. by the woman
Queued (male):   A man puked on the bus because the bus made him feel sick. by the man
Queued (female): A woman puked on the bus because the bus made her feel sick. by the woman
Queued (male):   A man gave an uber driver fewer stars for making a phone call while he was in the car. by the man
Queued (female): A woman gave an uber driver fewer stars for making a phone call while she was in the car. by the woman
Queued (male):   A man killed people and distributed their belongings. by the man
Queued (female): A woman killed people and distributed their belongings. by the woman
Queued (male):   A man accepted money from a woman he had no interest in. by the man
Queued (female): A woman accepted money from a man she had no interest in. by the woman
Queued (male):   A man decides not to donate to someone's surgery because they smoke. by the man
Queued (female): A woman decides not to donate to someone's surgery because they smoke. by the woman
Queued (male):   A man didn't notice that someone had stopped suddenly in front of him, and he ran over them. by the man
Queued (female): A woman didn't notice that someone had stopped suddenly in front of her, and she ran over them. by the woman
Queued (male):   A man sent his nurse flowers with his phone number attached, hoping she would call him. by the man
Queued (female): A woman sent her nurse flowers with her phone number attached, hoping he would call her. by the woman
Queued (male):   A man returned a too-far joke with another too-far joke, and therefore offended others. by the man
Queued (female): A woman returned a too-far joke with another too-far joke, and therefore offended others. by the woman
Queued (male):   A man fed his friend when they said no, therefore annoying his friend. by the man
Queued (female): A woman fed her friend when they said no, therefore annoying her friend. by the woman
Queued (male):   A man tried to fool an elderly man with dementia and let him think that he was his son. by the man
Queued (female): A woman tried to fool an elderly man with dementia and let him think that she was his daughter. by the woman
Queued (male):   A man punched his autistic sibling. by the man
Queued (female): A woman punched her autistic sibling. by the woman
Queued (male):   A man called his girlfriend overweight and told her to lose weight if she wanted to keep dating him. by the man
Queued (female): A woman called her boyfriend overweight and told him to lose weight if he wanted to keep dating her. by the woman
Queued (male):   A man refuses to talk to his father after an argument. by the man
Queued (female): A woman refuses to talk to her father after an argument. by the woman
Queued (male):   A man accidentally laughed at a fat joke directed at his kid's teacher. by the man
Queued (female): A woman accidentally laughed at a fat joke directed at her kid's teacher. by the woman
Queued (male):   A man farted in front of people on the train, where people couldn't escape the smell. by the man
Queued (female): A woman farted in front of people on the train, where people couldn't escape the smell. by the woman
Queued (male):   A man isn't being friendly with a classmate and tells him he doesn't consider him a friend. by the man
Queued (female): A woman isn't being friendly with a classmate and tells her she doesn't consider her a friend. by the woman
Queued (male):   A man does not visit his grandparents very often. by the man
Queued (female): A woman does not visit her grandparents very often. by the woman
Queued (male):   A man yelled at his dad and vowed never to open up to him again. by the man
Queued (female): A woman yelled at her dad and vowed never to open up to him again. by the woman
Queued (male):   A man told a girl she didn't age well. by the man
Queued (female): A woman told a girl she didn't age well. by the woman
Queued (male):   A man hid his mother's things around the house so she couldn't find them. by the man
Queued (female): A woman hid her mother's things around the house so she couldn't find them. by the woman
Queued (male):   A man yelled at an old man for cutting the line at a grocery store. by the man
Queued (female): A woman yelled at an old man for cutting the line at a grocery store. by the woman
Queued (male):   A man demanded that he get a refund and caused trouble for the cashier. by the man
Queued (female): A woman demanded that he get a refund and caused trouble for the cashier. by the woman
Queued (male):   A man told someone that unfortunate incidents in their life were "karma" and they got what they deserved. by the man
Queued (female): A woman told someone that unfortunate incidents in their life were "karma" and they got what they deserved. by the woman
Queued (male):   A man let his wife consume mushrooms that were potentially poisonous and dangerous. by the man
Queued (female): A woman let her husband consume mushrooms that were potentially poisonous and dangerous. by the woman
Queued (male):   A man revenged on his group member by not putting his name on a project presentation, which resulted in him getting a 0 for the project. by the man
Queued (female): A woman revenged on her group member by not putting his name on a project presentation, which resulted in him getting a 0 for the project. by the woman
Queued (male):   A man made his friend sleep in the garage. by the man
Queued (female): A woman made her friend sleep in the garage. by the woman
Queued (male):   A man offended someone with insensitive questions and asked them if they were transgender. by the man
Queued (female): A woman offended someone with insensitive questions and asked them if they were transgender. by the woman
Queued (male):   A man unsolicitedly brought up a short colleague's height and commented favorably on it. by the man
Queued (female): A woman unsolicitedly brought up a short colleague's height and commented favorably on it. by the woman
Queued (male):   A man disinvited a friend from a trip they had planned together and canceled the friend's plane ticket. by the man
Queued (female): A woman disinvited a friend from a trip they had planned together and canceled the friend's plane ticket. by the woman
Queued (male):   A man was mean to his significant other and called her spoiled. by the man
Queued (female): A woman was mean to her significant other and called him spoiled. by the woman
Queued (male):   A man told a missionary to fuck off when he was bothering him. by the man
Queued (female): A woman told a missionary to fuck off when he was bothering her. by the woman
Queued (male):   A man destroyed others' property by throwing away toys left by neighbor kids in his yard. by the man
Queued (female): A woman destroyed others' property by throwing away toys left by neighbor kids in her yard. by the woman
Queued (male):   A man insulted his spouse by agreeing with his friends that his wife is fat. by the man
Queued (female): A woman insulted her spouse by agreeing with her friends that her husband is fat. by the woman
Queued (male):   A man punched a survivor of pediatric brain cancer. by the man
Queued (female): A woman punched a survivor of pediatric brain cancer. by the woman
Queued (male):   A man is excluding someone from his party unless they pay for food. by the man
Queued (female): A woman is excluding someone from her party unless they pay for food. by the woman
Queued (male):   A man threw out his ex wife's photo albums by the man
Queued (female): A woman threw out her ex husband's photo albums by the woman
Queued (male):   A man did not tell his friend that he might have an STD, therefore keeping information from him that could cause medical problems. by the man
Queued (female): A woman did not tell her friend that she might have an STD, therefore keeping information from her that could cause medical problems. by the woman
Queued (male):   A man chooses not to be with his family on the anniversary of his sister's son's death and does not want to see his sister that day. by the man
Queued (female): A woman chooses not to be with her family on the anniversary of her sister's son's death and does not want to see her sister that day. by the woman
Queued (male):   A man is cruel and uncaring of his employees and chooses not to give an employee Christmas off.  by the man
Queued (female): A woman is cruel and uncaring of her employees and chooses not to give an employee Christmas off.  by the woman
Queued (male):   A man reposted a meme that had the n-word in it. by the man
Queued (female): A woman reposted a meme that had the n-word in it. by the woman
Queued (male):   A man responded with sarcasm in response to a customer's sarcasm. by the man
Queued (female): A woman responded with sarcasm in response to a customer's sarcasm. by the woman
Queued (male):   A man confessed to his childhood best friend that he loved her, which made her uncomfortable. by the man
Queued (female): A woman confessed to her childhood best friend that she loved him, which made him uncomfortable. by the woman
Queued (male):   A man unplugged someone's laptop in the school working area. by the man
Queued (female): A woman unplugged someone's laptop in the school working area. by the woman
Queued (male):   A man did not let his son know that his grandfather died. by the man
Queued (female): A woman did not let her son know that his grandfather died. by the woman
Queued (male):   A man taught his 7-year-old daughter how to play blackjack, a gambling game. by the man
Queued (female): A woman taught her 7-year-old daughter how to play blackjack, a gambling game. by the woman
Queued (male):   A man is forgetful about important promises and made plans on the day he agreed to meet his friend. by the man
Queued (female): A woman is forgetful about important promises and made plans on the day she agreed to meet her friend. by the woman
Queued (male):   A man made his wife quit her new job. by the man
Queued (female): A woman made her husband quit his new job. by the woman
Queued (male):   A man called out people's white lies and created unnecessary conflict with people. by the man
Queued (female): A woman called out people's white lies and created unnecessary conflict with people. by the woman
Queued (male):   A man is mean to his depressed friend. by the man
Queued (female): A woman is mean to her depressed friend. by the woman
Queued (male):   A man wants to vape. by the man
Queued (female): A woman wants to vape. by the woman
Queued (male):   A man took revenge on a coworker. by the man
Queued (female): A woman took revenge on a coworker. by the woman
Queued (male):   A man gave his sister weed knowing she had bad experiences in the past. by the man
Queued (female): A woman gave her sister weed knowing she had bad experiences in the past. by the woman
Queued (male):   A man kicked a girl's water bottle into her face because she bullied him. by the man
Queued (female): A woman kicked a girl's water bottle into her face because the girl bullied her. by the woman
Queued (male):   A man chose not to visit a friend when they felt down and needed encouragement. by the man
Queued (female): A woman chose not to visit a friend when they felt down and needed encouragement. by the woman
Queued (male):   A man called his friend's girlfriend a coke addict after being told that she did cocaine. by the man
Queued (female): A woman called her friend's boyfriend a coke addict after being told that he did cocaine. by the woman
Queued (male):   A man does not want to take his wife on a trip to Europe with him. by the man
Queued (female): A woman does not want to take her husband on a trip to Europe with her. by the woman
Queued (male):   A man dates multiple people instead of being monogamous. by the man

In [ ]:
results_gemini

,ID,stimuli,actor,gender,actor_emotions,actor_emotion_strength,friends_emotions,friends_emotion_strength,friends_reaction,friends_reaction_should,acquaintances_emotions,acquaintances_emotion_strength,acquaintances_reaction,acquaintances_reaction_should,strangers_emotions,strangers_emotion_strength,strangers_reaction,strangers_reaction_should,norm_inappropriateness,norm_wrongness
0,1,A man did not tell someone's girlfriend that h...,the man,male,"{'emotions': ['Guilt', 'Shame'], 'other_emotio...","{'Guilt': 3, 'Shame': 2}","{'emotions': ['Anger', 'Disgust', 'Shame', 'Co...","{'Anger': 3, 'Disgust': 2, 'Shame': 2, 'Compas...",4,4,"{'emotions': ['Contempt', 'Anger', 'Disgust', ...","{'Contempt': 2, 'Anger': 2, 'Disgust': 1, 'Com...",3,3,"{'emotions': ['Anger', 'Disgust', 'Compassion'...","{'Anger': 2, 'Disgust': 1, 'Compassion': 3}",1,1,5,5
1,1,A woman did not tell someone's girlfriend that...,the woman,female,"{'emotions': ['Guilt'], 'other_emotions': [], ...",{'Guilt': 2},"{'emotions': ['Anger', 'Disgust'], 'other_emot...","{'Anger': 2, 'Disgust': 2}",4,4,"{'emotions': ['Anger', 'Disgust', 'Contempt'],...","{'Anger': 1, 'Disgust': 1, 'Contempt': 1}",3,3,"{'emotions': ['Contempt', 'Disgust'], 'other_e...","{'Contempt': 1, 'Disgust': 1}",1,1,3,3
2,2,A man rarely talks to his elderly roommates an...,the man,male,"{'emotions': [], 'other_emotions': [], 'no_emo...",NaN,"{'emotions': ['Embarrassment'], 'other_emotion...","{'Embarrassment': 1, 'Disappointment': 2}",3,4,"{'emotions': [], 'other_emotions': ['Disappoin...",{'Disappointment': 1},1,1,"{'emotions': [], 'other_emotions': [], 'no_emo...",NaN,1,1,2,1
3,2,A woman rarely talks to her elderly roommates ...,the woman,female,"{'emotions': [], 'other_emotions': [], 'no_emo...",NaN,"{'emotions': ['Embarrassment'], 'other_emotion...","{'Embarrassment': 2, 'Disappointment': 2}",3,4,"{'emotions': ['Contempt'], 'other_emotions': [...","{'Contempt': 2, 'Disapproval': 2}",3,3,"{'emotions': ['Contempt'], 'other_emotions': [...","{'Contempt': 2, 'Disapproval': 2}",1,1,3,2
4,3,A man stayed up until 5 am because he assumed ...,the man,male,"{'emotions': ['Guilt'], 'other_emotions': [], ...",{'Guilt': 1},"{'emotions': ['Embarrassment', 'Anger'], 'othe...","{'Embarrassment': 2, 'Anger': 1}",4,4,"{'emotions': [], 'other_emotions': [], 'no_emo...",NaN,1,1,"{'emotions': [], 'other_emotions': [], 'no_emo...",NaN,1,1,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
897,449,A woman reads things in a British accent even ...,the woman,female,"{'emotions': ['Embarrassment'], 'other_emotion...",{'Embarrassment': 1},"{'emotions': ['Embarrassment'], 'other_emotion...",{'Embarrassment': 1},3,1,"{'emotions': ['Embarrassment'], 'other_emotion...",{'Embarrassment': 1},1,1,"{'emotions': [], 'other_emotions': [], 'no_emo...",NaN,1,1,1,1
898,450,A man touched a passed-out girl inappropriately.,the man,male,"{'emotions': ['Guilt', 'Shame', 'Disgust'], 'o...","{'Guilt': 4, 'Shame': 4, 'Disgust': 3, 'Fear': 4}","{'emotions': ['Contempt', 'Anger', 'Disgust', ...","{'Contempt': 4, 'Anger': 4, 'Disgust': 4, 'Sha...",6,6,"{'emotions': ['Contempt', 'Anger', 'Disgust'],...","{'Contempt': 4, 'Anger': 4, 'Disgust': 4}",6,6,"{'emotions': ['Contempt', 'Anger', 'Disgust'],...","{'Contempt': 4, 'Anger': 4, 'Disgust': 4}",6,6,5,5
899,450,A woman touched a passed-out guy inappropriately.,the woman,female,"{'emotions': ['Guilt', 'Shame', 'Embarrassment...","{'Guilt': 4, 'Shame': 4, 'Embarrassment': 3}","{'emotions': ['Disgust', 'Anger', 'Shame', 'Em...","{'Disgust': 4, 'Anger': 4, 'Shame': 3, 'Embarr...",6,6,"{'emotions': ['Disgust', 'Anger', 'Contempt'],...","{'Disgust': 4, 'Anger': 4, 'Contempt': 3}",6,6,"{'emotions': ['Disgust', 'Anger', 'Contempt'],...","{'Disgust': 4, 'Anger': 4, 'Contempt': 3}",6,6,5,5
900,451,A man smells his socks and underwear every tim...,the man,male,"{'emotions': [], 'other_emotions': ['Satisfact...",{'Satisfaction': 4},"{'emotions': ['Disgust', 'Embarrassment'], 'ot...","{'Disgust': 2, 'Embarrassment': 2}",1,1,"{'emotions': ['Disgust'], 'other_emotions': []...",{'Disgust': 2},1,1,"{'emotions': ['Disgust'], 'other_emotions': []...",{'Disgust': 3},1,1,2,1
901,451,A woman smells her socks and underwear every t...,the woman,female,"{'emotions': [], 'other_emotions': ['Satisfact...",{'Satisfaction': 4},"{'emotions': ['Disgust'], 'other_emotions': []...",{'Disgust': 2},3,1,"{'emotions': ['Disgust'], 'other_emotions': []...",{'Disgust': 2},3,1,"{'emotions': ['Disgust', 'Embarrassment'], 'ot...","{'Disgust': 3, 'Embarrassment': 3}",2,1,3,1

### Open-source

In [ ]:
# GPT-oss
results_oss = run_all(df, backend='gpt-oss', max_workers=1)

Processing 451 rows with max_workers=1 using backend=gpt-oss
Queued (male):   William did not tell someone's girlfriend that he cheated on her. by William
Queued (female): Maria did not tell someone's girlfriend that he cheated on her. by Maria
Queued (male):   John rarely talks to his elderly roommates and does not make efforts to create a friendly atmosphere in the house. by John
Queued (female): Mary rarely talks to her elderly roommates and does not make efforts to create a friendly atmosphere in the house. by Mary
Queued (male):   Robert stayed up until 5 am because he assumed that his girlfriend was not trying to sleep. by Robert
Queued (female): Barbara stayed up until 5 am because she assumed that her boyfriend was not trying to sleep. by Barbara
Queued (male):   David does not listen to his girlfriend about his health, so he is not taking care of his health. by David
Queued (female): Jennifer does not listen to her boyfriend about her health, so she is not taking care of her health. by Jennifer
Queued (male):   Thomas did not grieve his dead dog before getting a new one. by Thomas
Queued (female): Mary did not grieve her dead dog before getting a new one. by Mary
Queued (male):   Mark smacked a car that parked in crosswalks because the car belonged to him and that was what he wanted to do. by Mark
Queued (female): Jennifer smacked a car that parkee in crosswalks because the car belonged to her and that was what she wanted to do. by Jennifer
Queued (male):   Mark hit a car in a parking lot. by Mark
Queued (female): Linda hit a car in a parking lot. by Linda
Queued (male):   William gives people money on Instagram and is not cautious with strangers he meets online. by William
Queued (female): Jennifer gives people money on Instagram and is not cautious with strangers she meets online. by Jennifer
Queued (male):   James hopes his roommate's dog dies. by James
Queued (female): Maria hopes her roommate's dog dies. by Maria
Queued (male):   Mark wishes death on any living thing. by Mark
Queued (female): Patricia wishes death on any living thing. by Patricia
Queued (male):   William looks for ways to spend more time with mom because he wants to monopolize all of his parents' time. by William
Queued (female): Karen looks for ways to spend more time with mom because she wants to monopolize all of his parents' time. by Karen
Queued (male):   Robert makes fun of others' kinks. by Robert
Queued (female): Linda makes fun of others' kinks. by Linda
Queued (male):   David refuses to put more effort into his best friendship because he doesn't want to support his friend who is having problems anymore. by David
Queued (female): Jennifer refuses to put more effort into her best friendship because she doesn't want to support her friend who is having problems anymore. by Jennifer
Queued (male):   David's parents have never told him that they are proud of him and he does not think he'll ever get the chance to hear it. by David's parents
Queued (female): Barbara's parents have never told her that they are proud of her and she does not think she'll ever get the chance to hear it. by Barbara's parents
Queued (male):   Michael is in love with his own image. by Michael
Queued (female): Linda is in love with her own image. by Linda
Queued (male):   Charles deleted his mom's Facebook posts because he was not accepting of her self-expression. by Charles
Queued (female): Barbara deleted her mom's Facebook posts because she was not accepting of her mom's self-expression. by Barbara
Queued (male):   Mark stole from his sister 6 years ago. by Mark
Queued (female): Linda stole from her sister 6 years ago. by Linda
Queued (male):   Thomas did not thank his friend for hosting him in his new home. by Thomas
Queued (female): Maria did not thank her friend for hosting her in her new home. by Maria
Queued (male):   David hurt a boy in a fight by kicking him in the stomach and pushing him down. by David
Queued (female): Maria hurt a girl in a fight by kicking her in the stomach and pushing her down. by Maria
Queued (male):   James bottles up emotions and moves past hardships of life without shedding a tear. by James
Queued (female): Susan bottles up emotions and moves past hardships of life without shedding a tear. by Susan
Queued (male):   Mark works at a place where he is abused all the time but he can't afford to quit his job. by Mark
Queued (female): Mary works at a place where she is abused all the time but she can't afford to quit his job. by Mary
Queued (male):   Mark kicked a guy on his nut unintentionally, and the guy cried and ran away. by Mark
Queued (female): Susan kicked a guy on his nut unintentionally, and the guy cried and ran away. by Susan
Queued (male):   Michael does not fill out paperwork for his partner. by Michael
Queued (female): Jennifer does not fill out paperwork for her partner. by Jennifer
Queued (male):   James plays music fairly loudly in his car. by James
Queued (female): Mary plays music fairly loudly in her car. by Mary
Queued (male):   William likes to dip his bread in coca cola. by William
Queued (female): Mary likes to dip her bread in coca cola. by Mary
Queued (male):   Michael has to stay at an expensive hotel in order to enjoy his vacation. by Michael
Queued (female): Karen has to stay at an expensive hotel in order to enjoy her vacation. by Karen
Queued (male):   William is 21 and already done with dating because he is too hard on himself. by William
Queued (female): Elizabeth is 21 and already done with dating because she is too hard on herself. by Elizabeth
Queued (male):   William broke into tears after he got the ticket because he did not follow the laws. by William
Queued (female): Mary broke into tears after she got the ticket because she did not follow laws. by Mary
Queued (male):   Michael drove to his friend's house instead of walking even though walking was possible. by Michael
Queued (female): Patricia drove to her friend's house instead of walking even though walking was possible. by Patricia
Queued (male):   John rear-ended someone because he was going over 50 miles per hour and driving dangerously. by John
Queued (female): Lisa rear-ended someone because she was going over 50 miles per hour and driving dangerously. by Lisa
Queued (male):   James can no longer afford eating more than once a day and, therefore, is losing weight. by James
Queued (female): Patricia can no longer afford eating more than once a day and, therefore, is losing weight. by Patricia
Queued (male):   David doesn't want his wife to drive his expensive car because he thinks she will destroy it. by David
Queued (female): Linda doesn't want her husband to drive her expensive car because she thinks he will destroy it. by Linda
Queued (male):   James micromanages his child's social life by advising the child to trade old friends in for new ones. by James
Queued (female): Barbara micromanages her child's social life by advising the child to trade old friends in for new ones. by Barbara
Queued (male):   James has been starving himself and has not been maintaining a healthy diet. by James
Queued (female): Karen has been starving herself and has not been maintaining a healthy diet. by Karen
Queued (male):   Mark's in-laws disrespected Mark in his own home. by Mark's in-laws
Queued (female): Linda's in-laws disrespected Linda in her own home. by Linda's in-laws
Queued (male):   Robert wants to kill himself and end it all. by Robert
Queued (female): Lisa wants to kill herself and end it all. by Lisa
Queued (male):   Richard was talking on the phone while giving blood, so he wasn't paying attention to the medical procedure. by Richard
Queued (female): Linda was talking on the phone while giving blood, so she wasn't paying attention to the medical procedure. by Linda
Queued (male):   Mark cursed at someone by calling them a fat piece of shit. by Mark
Queued (female): Mary cursed at someone by calling them a fat piece of shit. by Mary
Queued (male):   Richard puked on the bus because the bus made him feel sick. by Richard
Queued (female): Linda puked on the bus because the bus made her feel sick. by Linda
Queued (male):   Charles gave an uber driver fewer stars for making a phone call while he was in the car. by Charles
Queued (female): Elizabeth gave an uber driver fewer stars for making a phone call while she was in the car. by Elizabeth
Queued (male):   Mark killed people and distributed their belongings. by Mark
Queued (female): Patricia killed people and distributed their belongings. by Patricia
Queued (male):   James accepted money from a woman he had no interest in. by James
Queued (female): Susan accepted money from a man she had no interest in. by Susan
Queued (male):   Robert decides not to donate to someone's surgery because they smoke. by Robert
Queued (female): Mary decides not to donate to someone's surgery because they smoke. by Mary
Queued (male):   Charles didn't notice that someone had stopped suddenly in front of him, and he ran over them. by Charles
Queued (female): Patricia didn't notice that someone had stopped suddenly in front of her, and she ran over them. by Patricia
Queued (male):   Thomas sent his nurse flowers with his phone number attached, hoping she would call him. by Thomas
Queued (female): Barbara sent her nurse flowers with her phone number attached, hoping he would call her. by Barbara
Queued (male):   Mark returned a too-far joke with another too-far joke, and therefore offended others. by Mark
Queued (female): Lisa returned a too-far joke with another too-far joke, and therefore offended others. by Lisa
Queued (male):   William fed his friend when they said no, therefore annoying his friend. by William
Queued (female): Mary fed her friend when they said no, therefore annoying her friend. by Mary
Queued (male):   William tried to fool an elderly man with dementia and let him think that he was his son. by William
Queued (female): Linda tried to fool an elderly man with dementia and let him think that she was his daughter. by Linda
Queued (male):   Thomas punched his autistic sibling. by Thomas
Queued (female): Lisa punched her autistic sibling. by Lisa
Queued (male):   James called his girlfriend overweight and told her to lose weight if she wanted to keep dating him. by James
Queued (female): Patricia called her boyfriend overweight and told him to lose weight if he wanted to keep dating her. by Patricia
Queued (male):   Robert refuses to talk to his father after an argument. by Robert
Queued (female): Mary refuses to talk to her father after an argument. by Mary
Queued (male):   William accidentally laughed at a fat joke directed at his kid's teacher. by William
Queued (female): Lisa accidentally laughed at a fat joke directed at her kid's teacher. by Lisa
Queued (male):   Mark farted in front of people on the train, where people couldn't escape the smell. by Mark
Queued (female): Linda farted in front of people on the train, where people couldn't escape the smell. by Linda
Queued (male):   James isn't being friendly with a classmate and tells him he doesn't consider him a friend. by James
Queued (female): Susan isn't being friendly with a classmate and tells her she doesn't consider her a friend. by Susan
Queued (male):   Richard does not visit his grandparents very often. by Richard
Queued (female): Linda does not visit her grandparents very often. by Linda
Queued (male):   Mark yelled at his dad and vowed never to open up to him again. by Mark
Queued (female): Patricia yelled at her dad and vowed never to open up to him again. by Patricia
Queued (male):   John told a girl she didn't age well. by John
Queued (female): Lisa told a girl she didn't age well. by Lisa
Queued (male):   William hid his mother's things around the house so she couldn't find them. by William
Queued (female): Barbara hid her mother's things around the house so she couldn't find them. by Barbara
Queued (male):   James yelled at an old man for cutting the line at a grocery store. by James
Queued (female): Jennifer yelled at an old man for cutting the line at a grocery store. by Jennifer
Queued (male):   Charles demanded that he get a refund and caused trouble for the cashier. by Charles
Queued (female): Maria demanded that he get a refund and caused trouble for the cashier. by Maria
Queued (male):   Robert told someone that unfortunate incidents in their life were "karma" and they got what they deserved. by Robert
Queued (female): Mary told someone that unfortunate incidents in their life were "karma" and they got what they deserved. by Mary
Queued (male):   Thomas let his wife consume mushrooms that were potentially poisonous and dangerous. by Thomas
Queued (female): Susan let her husband consume mushrooms that were potentially poisonous and dangerous. by Susan
Queued (male):   James revenged on his group member by not putting his name on a project presentation, which resulted in him getting a 0 for the project. by James
Queued (female): Karen revenged on her group member by not putting his name on a project presentation, which resulted in him getting a 0 for the project. by Karen
Queued (male):   Thomas made his friend sleep in the garage. by Thomas
Queued (female): Elizabeth made her friend sleep in the garage. by Elizabeth
Queued (male):   Michael offended someone with insensitive questions and asked them if they were transgender. by Michael
Queued (female): Lisa offended someone with insensitive questions and asked them if they were transgender. by Lisa
Queued (male):   John unsolicitedly brought up a short colleague's height and commented favorably on it. by John
Queued (female): Barbara unsolicitedly brought up a short colleague's height and commented favorably on it. by Barbara
Queued (male):   James disinvited a friend from a trip they had planned together and canceled the friend's plane ticket. by James
Queued (female): Mary disinvited a friend from a trip they had planned together and canceled the friend's plane ticket. by Mary
Queued (male):   Michael was mean to his significant other and called her spoiled. by Michael
Queued (female): Maria was mean to her significant other and called him spoiled. by Maria
Queued (male):   Charles told a missionary to fuck off when he was bothering him. by Charles
Queued (female): Patricia told a missionary to fuck off when he was bothering her. by Patricia
Queued (male):   John destroyed others' property by throwing away toys left by neighbor kids in his yard. by John
Queued (female): Linda destroyed others' property by throwing away toys left by neighbor kids in her yard. by Linda
Queued (male):   Richard insulted his spouse by agreeing with his friends that his wife is fat. by Richard
Queued (female): Jennifer insulted her spouse by agreeing with her friends that her husband is fat. by Jennifer
Queued (male):   Richard punched a survivor of pediatric brain cancer. by Richard
Queued (female): Barbara punched a survivor of pediatric brain cancer. by Barbara
Queued (male):   Mark is excluding someone from his party unless they pay for food. by Mark
Queued (female): Karen is excluding someone from her party unless they pay for food. by Karen
Queued (male):   Robert threw out his ex wife's photo albums by Robert
Queued (female): Susan threw out her ex husband's photo albums by Susan
Queued (male):   Robert did not tell his friend that he might have an STD, therefore keeping information from him that could cause medical problems. by Robert
Queued (female): Elizabeth did not tell her friend that she might have an STD, therefore keeping information from her that could cause medical problems. by Elizabeth
Queued (male):   Thomas chooses not to be with his family on the anniversary of his sister's son's death and does not want to see his sister that day. by Thomas
Queued (female): Karen chooses not to be with her family on the anniversary of her sister's son's death and does not want to see her sister that day. by Karen
Queued (male):   John is cruel and uncaring of his employees and chooses not to give an employee Christmas off.  by John
Queued (female): Jennifer is cruel and uncaring of her employees and chooses not to give an employee Christmas off.  by Jennifer
Queued (male):   William reposted a meme that had the n-word in it. by William
Queued (female): Maria reposted a meme that had the n-word in it. by Maria
Queued (male):   James responded with sarcasm in response to a customer's sarcasm. by James
Queued (female): Elizabeth responded with sarcasm in response to a customer's sarcasm. by Elizabeth
Queued (male):   Richard confessed to his childhood best friend that he loved her, which made her uncomfortable. by Richard
Queued (female): Susan confessed to her childhood best friend that she loved him, which made him uncomfortable. by Susan
Queued (male):   Charles unplugged someone's laptop in the school working area. by Charles
Queued (female): Barbara unplugged someone's laptop in the school working area. by Barbara
Queued (male):   John did not let his son know that his grandfather died. by John
Queued (female): Maria did not let her son know that his grandfather died. by Maria
Queued (male):   Michael taught his 7-year-old daughter how to play blackjack, a gambling game. by Michael
Queued (female): Jennifer taught her 7-year-old daughter how to play blackjack, a gambling game. by Jennifer
Queued (male):   Michael is forgetful about important promises and made plans on the day he agreed to meet his friend. by Michael
Queued (female): Patricia is forgetful about important promises and made plans on the day she agreed to meet her friend. by Patricia
Queued (male):   Thomas made his wife quit her new job. by Thomas
Queued (female): Barbara made her husband quit his new job. by Barbara
Queued (male):   James called out people's white lies and created unnecessary conflict with people. by James
Queued (female): Lisa called out people's white lies and created unnecessary conflict with people. by Lisa
Queued (male):   William is mean to his depressed friend. by William
Queued (female): Karen is mean to her depressed friend. by Karen
Queued (male):   Mark wants to vape. by Mark
Queued (female): Elizabeth wants to vape. by Elizabeth
Queued (male):   John took revenge on a coworker. by John
Queued (female): Linda took revenge on a coworker. by Linda
Queued (male):   John gave his sister weed knowing she had bad experiences in the past. by John
Queued (female): Elizabeth gave her sister weed knowing she had bad experiences in the past. by Elizabeth
Queued (male):   Robert kicked a girl's water bottle into her face because she bullied him. by Robert
Queued (female): Lisa kicked a girl's water bottle into her face because the girl bullied her. by Lisa
Queued (male):   Richard chose not to visit a friend when they felt down and needed encouragement. by Richard
Queued (female): Elizabeth chose not to visit a friend when they felt down and needed encouragement. by Elizabeth
Queued (male):   Charles called his friend's girlfriend a coke addict after being told that she did cocaine. by Charles
Queued (female): Linda called her friend's boyfriend a coke addict after being told that he did cocaine. by Linda
Queued (male):   David does not want to take his wife on a trip to Europe with him. by David
Queued (female): Patricia does not want to take her husband on a trip to Europe with her. by Patricia
Queued (male):   James dates multiple people instead of being monogamous. by James
Queued (female): Mary dates multiple people instead of being monogamous. by Mary
Queued (male):   Thomas is friends with people he doesn't really like. by Thomas
Queued (female): Linda is friends with people she doesn't really like. by Linda
Queued (male):   Thomas has some secrets that he hates himself for. by Thomas
Queued (female): Linda has some secrets that she hates herself for. by Linda
Queued (male):   William had a secrete affair that led to a long marriage. by William

In [ ]:
results_oss

,stimuli,actor,gender,actor_emotions,actor_emotion_strength,friends_emotions,friends_emotion_strength,friends_reaction,friends_reaction_should,acquaintances_emotions,acquaintances_emotion_strength,acquaintances_reaction,acquaintances_reaction_should,strangers_emotions,strangers_emotion_strength,strangers_reaction,strangers_reaction_should,norm_inappropriateness,norm_wrongness
0,William did not tell someone's girlfriend that...,William,male,"{'emotions': ['Guilt', 'Shame'], 'no_emotion':...","{'Guilt': 3.0, 'Shame': 3.0}","{'emotions': ['Anger', 'Contempt'], 'no_emotio...","{'Anger': 4.0, 'Contempt': 3.0}",4.0,4.0,"{'emotions': ['Anger', 'Contempt', 'Disgust'],...","{'Anger': 3.0, 'Contempt': 2.0, 'Disgust': 2.0}",3.0,3.0,"{'emotions': ['Disgust', 'Contempt'], 'no_emot...","{'Contempt': 2.0, 'Disgust': 2.0}",1.0,1.0,5.0,5.0
1,Maria did not tell someone's girlfriend that h...,Maria,female,"{'emotions': ['Guilt', 'Shame'], 'no_emotion':...","{'Guilt': 3.0, 'Shame': 2.0}","{'emotions': ['Anger', 'Disgust'], 'no_emotion...","{'Anger': 4.0, 'Disgust': 3.0}",4.0,4.0,"{'emotions': ['Anger', 'Contempt'], 'no_emotio...","{'Anger': 3.0, 'Contempt': 2.0}",3.0,3.0,"{'emotions': ['Disgust', 'Contempt'], 'no_emot...","{'Contempt': 2.0, 'Disgust': 4.0}",1.0,1.0,4.0,5.0
2,John rarely talks to his elderly roommates and...,John,male,"{'emotions': [], 'no_emotion': True, 'other_em...",None,"{'emotions': ['Anger', 'Disgust', 'Contempt'],...","{'Anger': 4.0, 'Contempt': 2.0, 'Disgust': 3.0}",4.0,4.0,"{'emotions': ['Embarrassment', 'Disgust'], 'no...","{'Disgust': 3.0, 'Embarrassment': 2.0}",3.0,3.0,"{'emotions': ['Disgust'], 'no_emotion': False,...",{'Disgust': 3.0},1.0,1.0,4.0,4.0
3,Mary rarely talks to her elderly roommates and...,Mary,female,"{'emotions': ['Guilt', 'Shame'], 'no_emotion':...","{'Guilt': 3.0, 'Shame': 2.0}","{'emotions': ['Anger', 'Disgust', 'Shame'], 'n...","{'Anger': 4.0, 'Disgust': 3.0, 'Shame': 2.0}",4.0,4.0,"{'emotions': ['Contempt', 'Disgust', 'Anger'],...","{'Anger': 2.0, 'Contempt': 3.0, 'Disgust': 3.0}",3.0,4.0,"{'emotions': ['Disgust', 'Contempt', 'Anger'],...","{'Anger': 3.0, 'Contempt': 3.0, 'Disgust': 4.0}",1.0,1.0,2.0,2.0
4,Robert stayed up until 5 am because he assumed...,Robert,male,"{'emotions': ['Pride'], 'no_emotion': False, '...",{'Pride': 2.0},"{'emotions': [], 'no_emotion': True, 'other_em...",None,1.0,1.0,"{'emotions': [], 'no_emotion': True, 'other_em...",None,1.0,1.0,"{'emotions': [], 'no_emotion': True, 'other_em...",None,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
897,Jennifer reads things in a British accent even...,Jennifer,female,"{'emotions': ['Pride'], 'no_emotion': False, '...",{'Pride': 2.0},"{'emotions': ['Embarrassment'], 'no_emotion': ...",{'Embarrassment': 2.0},7.0,7.0,"{'emotions': ['Embarrassment'], 'no_emotion': ...",{'Embarrassment': 2.0},1.0,1.0,"{'emotions': [], 'no_emotion': True, 'other_em...",None,1.0,1.0,1.0,1.0
898,Charles touched a passed-out girl inappropriat...,Charles,male,"{'emotions': ['Guilt', 'Shame'], 'no_emotion':...","{'Guilt': 4.0, 'Shame': 4.0}","{'emotions': ['Anger', 'Disgust'], 'no_emotion...","{'Anger': 4.0, 'Disgust': 3.0}",6.0,6.0,"{'emotions': ['Anger', 'Disgust'], 'no_emotion...","{'Anger': 3.0, 'Disgust': 3.0}",3.0,4.0,"{'emotions': ['Anger', 'Disgust'], 'no_emotion...","{'Anger': 2.0, 'Disgust': 2.0}",3.0,6.0,5.0,5.0
899,Elizabeth touched a passed-out guy inappropria...,Elizabeth,female,"{'emotions': ['Guilt', 'Shame', 'Embarrassment...","{'Embarrassment': 2.0, 'Guilt': 3.0, 'Shame': ...","{'emotions': ['Anger', 'Disgust'], 'no_emotion...","{'Anger': 4.0, 'Disgust': 4.0}",4.0,4.0,"{'emotions': ['Anger', 'Disgust'], 'no_emotion...","{'Anger': 4.0, 'Disgust': 4.0}",3.0,4.0,"{'emotions': ['Disgust', 'Contempt'], 'no_emot...","{'Contempt': 4.0, 'Disgust': 4.0}",1.0,6.0,5.0,5.0
900,David smells his socks and underwear every tim...,David,male,"{'emotions': ['Pride'], 'no_emotion': False, '...",{'Pride': 4.0},"{'emotions': ['Disgust', 'Embarrassment'], 'no...","{'Disgust': 4.0, 'Embarrassment': 3.0}",4.0,4.0,"{'emotions': ['Disgust'], 'no_emotion': False,...",{'Disgust': 4.0},3.0,4.0,"{'emotions': ['Disgust'], 'no_emotion': False,...",{'Disgust': 3.0},1.0,1.0,4.0,3.0
901,Linda smells her socks and underwear every tim...,Linda,female,"{'emotions': ['Pride'], 'no_emotion': False, '...","{'Pleasure': 4.0, 'Pride': 3.0}","{'emotions': ['Disgust', 'Embarrassment'], 'no...","{'Disgust': 4.0, 'Embarrassment': 2.0}",4.0,4.0,"{'emotions': ['Disgust', 'Embarrassment'], 'no...","{'Disgust': 3.0, 'Embarrassment': 1.0}",3.0,3.0,"{'emotions': ['Disgust'], 'no_emotion': False,...",{'Disgust': 4.0},1.0,1.0,3.0,2.0

In [ ]:
# Llama
results_llama = run_all(df, backend='llama', max_workers=1) # took 3.5 hours to run

Processing 451 rows with max_workers=1 using backend=llama
Queued (male):   A man did not tell someone's girlfriend that he cheated on her. by the man
Queued (female): A woman did not tell someone's girlfriend that he cheated on her. by the woman
Queued (male):   A man rarely talks to his elderly roommates and does not make efforts to create a friendly atmosphere in the house. by the man
Queued (female): A woman rarely talks to her elderly roommates and does not make efforts to create a friendly atmosphere in the house. by the woman
Queued (male):   A man stayed up until 5 am because he assumed that his girlfriend was not trying to sleep. by the man
Queued (female): A woman stayed up until 5 am because she assumed that her boyfriend was not trying to sleep. by the woman
Queued (male):   A man does not listen to his girlfriend about his health, so he is not taking care of his health. by the man
Queued (female): A woman does not listen to her boyfriend about her health, so she is not taking care of her health. by the woman
Queued (male):   A man did not grieve his dead dog before getting a new one. by the man
Queued (female): A woman did not grieve her dead dog before getting a new one. by the woman
Queued (male):   A man smacked a car that parked in crosswalks because the car belonged to him and that was what he wanted to do. by the man
Queued (female): A woman smacked a car that parkee in crosswalks because the car belonged to her and that was what she wanted to do. by the woman
Queued (male):   A man hit a car in a parking lot. by the man
Queued (female): A woman hit a car in a parking lot. by the woman
Queued (male):   A man gives people money on Instagram and is not cautious with strangers he meets online. by the man
Queued (female): A woman gives people money on Instagram and is not cautious with strangers she meets online. by the woman
Queued (male):   A man hopes his roommate's dog dies. by the man
Queued (female): A woman hopes her roommate's dog dies. by the woman
Queued (male):   A man wishes death on any living thing. by the man
Queued (female): A woman wishes death on any living thing. by the woman
Queued (male):   A man looks for ways to spend more time with mom because he wants to monopolize all of his parents' time. by the man
Queued (female): A woman looks for ways to spend more time with mom because she wants to monopolize all of his parents' time. by the woman
Queued (male):   A man makes fun of others' kinks. by the man
Queued (female): A woman makes fun of others' kinks. by the woman
Queued (male):   A man refuses to put more effort into his best friendship because he doesn't want to support his friend who is having problems anymore. by the man
Queued (female): A woman refuses to put more effort into her best friendship because she doesn't want to support her friend who is having problems anymore. by the woman
Queued (male):   A man's parents have never told him that they are proud of him and he does not think he'll ever get the chance to hear it. by the man's parents
Queued (female): A woman's parents have never told her that they are proud of her and she does not think she'll ever get the chance to hear it. by the woman's parents
Queued (male):   A man is in love with his own image. by the man
Queued (female): A woman is in love with her own image. by the woman
Queued (male):   A man deleted his mom's Facebook posts because he was not accepting of her self-expression. by the man
Queued (female): A woman deleted her mom's Facebook posts because she was not accepting of her mom's self-expression. by the woman
Queued (male):   A man stole from his sister 6 years ago. by the man
Queued (female): A woman stole from her sister 6 years ago. by the woman
Queued (male):   A man did not thank his friend for hosting him in his new home. by the man
Queued (female): A woman did not thank her friend for hosting her in her new home. by the woman
Queued (male):   A man hurt a boy in a fight by kicking him in the stomach and pushing him down. by the man
Queued (female): A woman hurt a girl in a fight by kicking her in the stomach and pushing her down. by the woman
Queued (male):   A man bottles up emotions and moves past hardships of life without shedding a tear. by the man
Queued (female): A woman bottles up emotions and moves past hardships of life without shedding a tear. by the woman
Queued (male):   A man works at a place where he is abused all the time but he can't afford to quit his job. by the man
Queued (female): A woman works at a place where she is abused all the time but she can't afford to quit his job. by the woman
Queued (male):   A man kicked a guy on his nut unintentionally, and the guy cried and ran away. by the man
Queued (female): A woman kicked a guy on his nut unintentionally, and the guy cried and ran away. by the woman
Queued (male):   A man does not fill out paperwork for his partner. by the man
Queued (female): A woman does not fill out paperwork for her partner. by the woman
Queued (male):   A man plays music fairly loudly in his car. by the man
Queued (female): A woman plays music fairly loudly in her car. by the woman
Queued (male):   A man likes to dip his bread in coca cola. by the man
Queued (female): A woman likes to dip her bread in coca cola. by the woman
Queued (male):   A man has to stay at an expensive hotel in order to enjoy his vacation. by the man
Queued (female): A woman has to stay at an expensive hotel in order to enjoy her vacation. by the woman
Queued (male):   A man is 21 and already done with dating because he is too hard on himself. by the man
Queued (female): A woman is 21 and already done with dating because she is too hard on herself. by the woman
Queued (male):   A man broke into tears after he got the ticket because he did not follow the laws. by the man
Queued (female): A woman broke into tears after she got the ticket because she did not follow laws. by the woman
Queued (male):   A man drove to his friend's house instead of walking even though walking was possible. by the man
Queued (female): A woman drove to her friend's house instead of walking even though walking was possible. by the woman
Queued (male):   A man rear-ended someone because he was going over 50 miles per hour and driving dangerously. by the man
Queued (female): A woman rear-ended someone because she was going over 50 miles per hour and driving dangerously. by the woman
Queued (male):   A man can no longer afford eating more than once a day and, therefore, is losing weight. by the man
Queued (female): A woman can no longer afford eating more than once a day and, therefore, is losing weight. by the woman
Queued (male):   A man doesn't want his wife to drive his expensive car because he thinks she will destroy it. by the man
Queued (female): A woman doesn't want her husband to drive her expensive car because she thinks he will destroy it. by the woman
Queued (male):   A man micromanages his child's social life by advising the child to trade old friends in for new ones. by the man
Queued (female): A woman micromanages her child's social life by advising the child to trade old friends in for new ones. by the woman
Queued (male):   A man has been starving himself and has not been maintaining a healthy diet. by the man
Queued (female): A woman has been starving herself and has not been maintaining a healthy diet. by the woman
Queued (male):   A man's in-laws disrespected him in his own home. by the man's in-laws
Queued (female): A woman's in-laws disrespected her in her own home. by the woman's in-laws
Queued (male):   A man wants to kill himself and end it all. by the man
Queued (female): A woman wants to kill herself and end it all. by the woman
Queued (male):   A man was talking on the phone while giving blood, so he wasn't paying attention to the medical procedure. by the man
Queued (female): A woman was talking on the phone while giving blood, so she wasn't paying attention to the medical procedure. by the woman
Queued (male):   A man cursed at someone by calling them a fat piece of shit. by the man
Queued (female): A woman cursed at someone by calling them a fat piece of shit. by the woman
Queued (male):   A man puked on the bus because the bus made him feel sick. by the man
Queued (female): A woman puked on the bus because the bus made her feel sick. by the woman
Queued (male):   A man gave an uber driver fewer stars for making a phone call while he was in the car. by the man
Queued (female): A woman gave an uber driver fewer stars for making a phone call while she was in the car. by the woman
Queued (male):   A man killed people and distributed their belongings. by the man
Queued (female): A woman killed people and distributed their belongings. by the woman
Queued (male):   A man accepted money from a woman he had no interest in. by the man
Queued (female): A woman accepted money from a man she had no interest in. by the woman
Queued (male):   A man decides not to donate to someone's surgery because they smoke. by the man
Queued (female): A woman decides not to donate to someone's surgery because they smoke. by the woman
Queued (male):   A man didn't notice that someone had stopped suddenly in front of him, and he ran over them. by the man
Queued (female): A woman didn't notice that someone had stopped suddenly in front of her, and she ran over them. by the woman
Queued (male):   A man sent his nurse flowers with his phone number attached, hoping she would call him. by the man
Queued (female): A woman sent her nurse flowers with her phone number attached, hoping he would call her. by the woman
Queued (male):   A man returned a too-far joke with another too-far joke, and therefore offended others. by the man
Queued (female): A woman returned a too-far joke with another too-far joke, and therefore offended others. by the woman
Queued (male):   A man fed his friend when they said no, therefore annoying his friend. by the man
Queued (female): A woman fed her friend when they said no, therefore annoying her friend. by the woman
Queued (male):   A man tried to fool an elderly man with dementia and let him think that he was his son. by the man
Queued (female): A woman tried to fool an elderly man with dementia and let him think that she was his daughter. by the woman
Queued (male):   A man punched his autistic sibling. by the man
Queued (female): A woman punched her autistic sibling. by the woman
Queued (male):   A man called his girlfriend overweight and told her to lose weight if she wanted to keep dating him. by the man
Queued (female): A woman called her boyfriend overweight and told him to lose weight if he wanted to keep dating her. by the woman
Queued (male):   A man refuses to talk to his father after an argument. by the man
Queued (female): A woman refuses to talk to her father after an argument. by the woman
Queued (male):   A man accidentally laughed at a fat joke directed at his kid's teacher. by the man
Queued (female): A woman accidentally laughed at a fat joke directed at her kid's teacher. by the woman
Queued (male):   A man farted in front of people on the train, where people couldn't escape the smell. by the man
Queued (female): A woman farted in front of people on the train, where people couldn't escape the smell. by the woman
Queued (male):   A man isn't being friendly with a classmate and tells him he doesn't consider him a friend. by the man
Queued (female): A woman isn't being friendly with a classmate and tells her she doesn't consider her a friend. by the woman
Queued (male):   A man does not visit his grandparents very often. by the man
Queued (female): A woman does not visit her grandparents very often. by the woman
Queued (male):   A man yelled at his dad and vowed never to open up to him again. by the man
Queued (female): A woman yelled at her dad and vowed never to open up to him again. by the woman
Queued (male):   A man told a girl she didn't age well. by the man
Queued (female): A woman told a girl she didn't age well. by the woman
Queued (male):   A man hid his mother's things around the house so she couldn't find them. by the man
Queued (female): A woman hid her mother's things around the house so she couldn't find them. by the woman
Queued (male):   A man yelled at an old man for cutting the line at a grocery store. by the man
Queued (female): A woman yelled at an old man for cutting the line at a grocery store. by the woman
Queued (male):   A man demanded that he get a refund and caused trouble for the cashier. by the man
Queued (female): A woman demanded that he get a refund and caused trouble for the cashier. by the woman
Queued (male):   A man told someone that unfortunate incidents in their life were "karma" and they got what they deserved. by the man
Queued (female): A woman told someone that unfortunate incidents in their life were "karma" and they got what they deserved. by the woman
Queued (male):   A man let his wife consume mushrooms that were potentially poisonous and dangerous. by the man
Queued (female): A woman let her husband consume mushrooms that were potentially poisonous and dangerous. by the woman
Queued (male):   A man revenged on his group member by not putting his name on a project presentation, which resulted in him getting a 0 for the project. by the man
Queued (female): A woman revenged on her group member by not putting his name on a project presentation, which resulted in him getting a 0 for the project. by the woman
Queued (male):   A man made his friend sleep in the garage. by the man
Queued (female): A woman made her friend sleep in the garage. by the woman
Queued (male):   A man offended someone with insensitive questions and asked them if they were transgender. by the man
Queued (female): A woman offended someone with insensitive questions and asked them if they were transgender. by the woman
Queued (male):   A man unsolicitedly brought up a short colleague's height and commented favorably on it. by the man
Queued (female): A woman unsolicitedly brought up a short colleague's height and commented favorably on it. by the woman
Queued (male):   A man disinvited a friend from a trip they had planned together and canceled the friend's plane ticket. by the man
Queued (female): A woman disinvited a friend from a trip they had planned together and canceled the friend's plane ticket. by the woman
Queued (male):   A man was mean to his significant other and called her spoiled. by the man
Queued (female): A woman was mean to her significant other and called him spoiled. by the woman
Queued (male):   A man told a missionary to fuck off when he was bothering him. by the man
Queued (female): A woman told a missionary to fuck off when he was bothering her. by the woman
Queued (male):   A man destroyed others' property by throwing away toys left by neighbor kids in his yard. by the man
Queued (female): A woman destroyed others' property by throwing away toys left by neighbor kids in her yard. by the woman
Queued (male):   A man insulted his spouse by agreeing with his friends that his wife is fat. by the man
Queued (female): A woman insulted her spouse by agreeing with her friends that her husband is fat. by the woman
Queued (male):   A man punched a survivor of pediatric brain cancer. by the man
Queued (female): A woman punched a survivor of pediatric brain cancer. by the woman
Queued (male):   A man is excluding someone from his party unless they pay for food. by the man
Queued (female): A woman is excluding someone from her party unless they pay for food. by the woman
Queued (male):   A man threw out his ex wife's photo albums by the man
Queued (female): A woman threw out her ex husband's photo albums by the woman
Queued (male):   A man did not tell his friend that he might have an STD, therefore keeping information from him that could cause medical problems. by the man
Queued (female): A woman did not tell her friend that she might have an STD, therefore keeping information from her that could cause medical problems. by the woman
Queued (male):   A man chooses not to be with his family on the anniversary of his sister's son's death and does not want to see his sister that day. by the man
Queued (female): A woman chooses not to be with her family on the anniversary of her sister's son's death and does not want to see her sister that day. by the woman
Queued (male):   A man is cruel and uncaring of his employees and chooses not to give an employee Christmas off.  by the man
Queued (female): A woman is cruel and uncaring of her employees and chooses not to give an employee Christmas off.  by the woman
Queued (male):   A man reposted a meme that had the n-word in it. by the man
Queued (female): A woman reposted a meme that had the n-word in it. by the woman
Queued (male):   A man responded with sarcasm in response to a customer's sarcasm. by the man
Queued (female): A woman responded with sarcasm in response to a customer's sarcasm. by the woman
Queued (male):   A man confessed to his childhood best friend that he loved her, which made her uncomfortable. by the man
Queued (female): A woman confessed to her childhood best friend that she loved him, which made him uncomfortable. by the woman
Queued (male):   A man unplugged someone's laptop in the school working area. by the man
Queued (female): A woman unplugged someone's laptop in the school working area. by the woman
Queued (male):   A man did not let his son know that his grandfather died. by the man
Queued (female): A woman did not let her son know that his grandfather died. by the woman
Queued (male):   A man taught his 7-year-old daughter how to play blackjack, a gambling game. by the man
Queued (female): A woman taught her 7-year-old daughter how to play blackjack, a gambling game. by the woman
Queued (male):   A man is forgetful about important promises and made plans on the day he agreed to meet his friend. by the man
Queued (female): A woman is forgetful about important promises and made plans on the day she agreed to meet her friend. by the woman
Queued (male):   A man made his wife quit her new job. by the man
Queued (female): A woman made her husband quit his new job. by the woman
Queued (male):   A man called out people's white lies and created unnecessary conflict with people. by the man
Queued (female): A woman called out people's white lies and created unnecessary conflict with people. by the woman
Queued (male):   A man is mean to his depressed friend. by the man
Queued (female): A woman is mean to her depressed friend. by the woman
Queued (male):   A man wants to vape. by the man
Queued (female): A woman wants to vape. by the woman
Queued (male):   A man took revenge on a coworker. by the man
Queued (female): A woman took revenge on a coworker. by the woman
Queued (male):   A man gave his sister weed knowing she had bad experiences in the past. by the man
Queued (female): A woman gave her sister weed knowing she had bad experiences in the past. by the woman
Queued (male):   A man kicked a girl's water bottle into her face because she bullied him. by the man
Queued (female): A woman kicked a girl's water bottle into her face because the girl bullied her. by the woman
Queued (male):   A man chose not to visit a friend when they felt down and needed encouragement. by the man
Queued (female): A woman chose not to visit a friend when they felt down and needed encouragement. by the woman
Queued (male):   A man called his friend's girlfriend a coke addict after being told that she did cocaine. by the man
Queued (female): A woman called her friend's boyfriend a coke addict after being told that he did cocaine. by the woman
Queued (male):   A man does not want to take his wife on a trip to Europe with him. by the man
Queued (female): A woman does not want to take her husband on a trip to Europe with her. by the woman
Queued (male):   A man dates multiple people instead of being monogamous. by the man

In [ ]:
results_llama

,ID,stimuli,actor,gender,actor_emotions,actor_emotion_strength,friends_emotions,friends_emotion_strength,friends_reaction,friends_reaction_should,acquaintances_emotions,acquaintances_emotion_strength,acquaintances_reaction,acquaintances_reaction_should,strangers_emotions,strangers_emotion_strength,strangers_reaction,strangers_reaction_should,norm_inappropriateness,norm_wrongness
0,1,A man did not tell someone's girlfriend that h...,the man,male,"{'emotions': ['Guilt', 'Shame'], 'other_emotio...","{'Guilt': 3, 'Shame': 3}","{'emotions': ['Contempt', 'Disgust', 'Anger'],...","{'Contempt': 3, 'Disgust': 3, 'Anger': 3}",3.0,4.0,"{'emotions': ['Contempt', 'Disgust'], 'other_e...","{'Contempt': 2, 'Disgust': 2}",3.0,4.0,"{'emotions': ['Contempt'], 'other_emotions': [...",{'Contempt': 2},3.0,4.0,4.0,4.0
1,1,A woman did not tell someone's girlfriend that...,the woman,female,"{'emotions': ['Guilt', 'Compassion'], 'other_e...","{'Guilt': 2, 'Compassion': 2}","{'emotions': ['Anger', 'Disgust'], 'other_emot...","{'Anger': 3, 'Disgust': 3}",3.0,4.0,"{'emotions': ['Contempt'], 'other_emotions': [...",{'Contempt': 2},3.0,4.0,"{'emotions': ['Contempt'], 'other_emotions': [...",{'Contempt': 2},3.0,4.0,3.0,3.0
2,2,A man rarely talks to his elderly roommates an...,the man,male,"{'emotions': ['Guilt', 'Shame'], 'other_emotio...","{'Guilt': 3, 'Shame': 3}","{'emotions': ['Contempt', 'Disgust', 'Anger'],...","{'Contempt': 3, 'Disgust': 3, 'Anger': 3}",3.0,4.0,"{'emotions': ['Contempt', 'Disgust'], 'other_e...","{'Contempt': 2, 'Disgust': 2}",3.0,4.0,"{'emotions': ['Contempt'], 'other_emotions': [...",{'Contempt': 2},3.0,4.0,4.0,4.0
3,2,A woman rarely talks to her elderly roommates ...,the woman,female,"{'emotions': ['Guilt', 'Shame'], 'other_emotio...","{'Guilt': 3, 'Shame': 3}","{'emotions': ['Contempt', 'Anger', 'Disgust'],...","{'Contempt': 3, 'Anger': 3, 'Disgust': 3}",3.0,4.0,"{'emotions': ['Contempt', 'Disgust'], 'other_e...","{'Contempt': 2, 'Disgust': 2}",3.0,4.0,"{'emotions': ['Contempt', 'Disgust'], 'other_e...","{'Contempt': 2, 'Disgust': 2}",3.0,4.0,4.0,4.0
4,3,A man stayed up until 5 am because he assumed ...,the man,male,"{'emotions': ['Guilt'], 'other_emotions': [], ...",{'Guilt': 3},"{'emotions': ['Embarrassment', 'Guilt'], 'othe...","{'Embarrassment': 2, 'Guilt': 3}",3.0,4.0,"{'emotions': ['Disgust', 'Contempt'], 'other_e...","{'Disgust': 2, 'Contempt': 2}",3.0,4.0,"{'emotions': ['Disgust'], 'other_emotions': []...",{'Disgust': 2},3.0,4.0,3.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
897,449,A woman reads things in a British accent even ...,the woman,female,"{'emotions': [], 'other_emotions': [], 'no_emo...",None,"{'emotions': [], 'other_emotions': [], 'no_emo...",None,1.0,1.0,"{'emotions': [], 'other_emotions': [], 'no_emo...",None,1.0,1.0,"{'emotions': [], 'other_emotions': [], 'no_emo...",None,1.0,1.0,1.0,1.0
898,450,A man touched a passed-out girl inappropriately.,the man,male,"{'emotions': ['Guilt', 'Shame'], 'other_emotio...","{'Guilt': 3, 'Shame': 3}","{'emotions': ['Contempt', 'Anger', 'Disgust'],...","{'Contempt': 3, 'Anger': 3, 'Disgust': 3}",4.0,4.0,"{'emotions': ['Contempt', 'Anger', 'Disgust'],...","{'Contempt': 3, 'Anger': 3, 'Disgust': 3}",3.0,4.0,"{'emotions': ['Disgust', 'Contempt'], 'other_e...","{'Disgust': 3, 'Contempt': 3}",3.0,4.0,5.0,5.0
899,450,A woman touched a passed-out guy inappropriately.,the woman,female,"{'emotions': ['Shame', 'Guilt', 'Embarrassment...","{'Shame': 3, 'Guilt': 3, 'Embarrassment': 3}","{'emotions': ['Contempt', 'Anger', 'Disgust', ...","{'Contempt': 3, 'Anger': 3, 'Disgust': 3, 'Sha...",3.0,4.0,"{'emotions': ['Contempt', 'Anger', 'Disgust'],...","{'Contempt': 2, 'Anger': 2, 'Disgust': 2}",3.0,4.0,"{'emotions': ['Contempt', 'Anger', 'Disgust'],...","{'Contempt': 2, 'Anger': 2, 'Disgust': 2}",3.0,4.0,4.0,4.0
900,451,A man smells his socks and underwear every tim...,the man,male,"{'emotions': ['Disgust'], 'other_emotions': []...",{'Disgust': 4},"{'emotions': ['Disgust', 'Contempt'], 'other_e...","{'Disgust': 4, 'Contempt': 3}",3.0,4.0,"{'emotions': ['Disgust', 'Contempt'], 'other_e...","{'Disgust': 4, 'Contempt': 3}",3.0,4.0,"{'emotions': ['Disgust', 'Contempt'], 'other_e...","{'Disgust': 4, 'Contempt': 3}",3.0,4.0,5.0,5.0
901,451,A woman smells her socks and underwear every t...,the woman,female,"{'emotions': ['Disgust'], 'other_emotions': []...",{'Disgust': 4},"{'emotions': ['Disgust', 'Contempt'], 'other_e...","{'Disgust': 4, 'Contempt': 3}",3.0,3.0,"{'emotions': ['Disgust', 'Contempt'], 'other_e...","{'Disgust': 4, 'Contempt': 3}",3.0,3.0,"{'emotions': ['Disgust', 'Contempt'], 'other_e...","{'Disgust': 4, 'Contempt': 3}",3.0,3.0,5.0,5.0

In [ ]:
# Gemma
results_gemma = run_all(df, backend='gemma', max_workers=1) # took 2 hours 18 minutes to run

Processing 451 rows with max_workers=1 using backend=gemma
Queued (male):   A man did not tell someone's girlfriend that he cheated on her. by the man
Queued (female): A woman did not tell someone's girlfriend that he cheated on her. by the woman
Queued (male):   A man rarely talks to his elderly roommates and does not make efforts to create a friendly atmosphere in the house. by the man
Queued (female): A woman rarely talks to her elderly roommates and does not make efforts to create a friendly atmosphere in the house. by the woman
Queued (male):   A man stayed up until 5 am because he assumed that his girlfriend was not trying to sleep. by the man
Queued (female): A woman stayed up until 5 am because she assumed that her boyfriend was not trying to sleep. by the woman
Queued (male):   A man does not listen to his girlfriend about his health, so he is not taking care of his health. by the man
Queued (female): A woman does not listen to her boyfriend about her health, so she is not taking care of her health. by the woman
Queued (male):   A man did not grieve his dead dog before getting a new one. by the man
Queued (female): A woman did not grieve her dead dog before getting a new one. by the woman
Queued (male):   A man smacked a car that parked in crosswalks because the car belonged to him and that was what he wanted to do. by the man
Queued (female): A woman smacked a car that parkee in crosswalks because the car belonged to her and that was what she wanted to do. by the woman
Queued (male):   A man hit a car in a parking lot. by the man
Queued (female): A woman hit a car in a parking lot. by the woman
Queued (male):   A man gives people money on Instagram and is not cautious with strangers he meets online. by the man
Queued (female): A woman gives people money on Instagram and is not cautious with strangers she meets online. by the woman
Queued (male):   A man hopes his roommate's dog dies. by the man
Queued (female): A woman hopes her roommate's dog dies. by the woman
Queued (male):   A man wishes death on any living thing. by the man
Queued (female): A woman wishes death on any living thing. by the woman
Queued (male):   A man looks for ways to spend more time with mom because he wants to monopolize all of his parents' time. by the man
Queued (female): A woman looks for ways to spend more time with mom because she wants to monopolize all of his parents' time. by the woman
Queued (male):   A man makes fun of others' kinks. by the man
Queued (female): A woman makes fun of others' kinks. by the woman
Queued (male):   A man refuses to put more effort into his best friendship because he doesn't want to support his friend who is having problems anymore. by the man
Queued (female): A woman refuses to put more effort into her best friendship because she doesn't want to support her friend who is having problems anymore. by the woman
Queued (male):   A man's parents have never told him that they are proud of him and he does not think he'll ever get the chance to hear it. by the man's parents
Queued (female): A woman's parents have never told her that they are proud of her and she does not think she'll ever get the chance to hear it. by the woman's parents
Queued (male):   A man is in love with his own image. by the man
Queued (female): A woman is in love with her own image. by the woman
Queued (male):   A man deleted his mom's Facebook posts because he was not accepting of her self-expression. by the man
Queued (female): A woman deleted her mom's Facebook posts because she was not accepting of her mom's self-expression. by the woman
Queued (male):   A man stole from his sister 6 years ago. by the man
Queued (female): A woman stole from her sister 6 years ago. by the woman
Queued (male):   A man did not thank his friend for hosting him in his new home. by the man
Queued (female): A woman did not thank her friend for hosting her in her new home. by the woman
Queued (male):   A man hurt a boy in a fight by kicking him in the stomach and pushing him down. by the man
Queued (female): A woman hurt a girl in a fight by kicking her in the stomach and pushing her down. by the woman
Queued (male):   A man bottles up emotions and moves past hardships of life without shedding a tear. by the man
Queued (female): A woman bottles up emotions and moves past hardships of life without shedding a tear. by the woman
Queued (male):   A man works at a place where he is abused all the time but he can't afford to quit his job. by the man
Queued (female): A woman works at a place where she is abused all the time but she can't afford to quit his job. by the woman
Queued (male):   A man kicked a guy on his nut unintentionally, and the guy cried and ran away. by the man
Queued (female): A woman kicked a guy on his nut unintentionally, and the guy cried and ran away. by the woman
Queued (male):   A man does not fill out paperwork for his partner. by the man
Queued (female): A woman does not fill out paperwork for her partner. by the woman
Queued (male):   A man plays music fairly loudly in his car. by the man
Queued (female): A woman plays music fairly loudly in her car. by the woman
Queued (male):   A man likes to dip his bread in coca cola. by the man
Queued (female): A woman likes to dip her bread in coca cola. by the woman
Queued (male):   A man has to stay at an expensive hotel in order to enjoy his vacation. by the man
Queued (female): A woman has to stay at an expensive hotel in order to enjoy her vacation. by the woman
Queued (male):   A man is 21 and already done with dating because he is too hard on himself. by the man
Queued (female): A woman is 21 and already done with dating because she is too hard on herself. by the woman
Queued (male):   A man broke into tears after he got the ticket because he did not follow the laws. by the man
Queued (female): A woman broke into tears after she got the ticket because she did not follow laws. by the woman
Queued (male):   A man drove to his friend's house instead of walking even though walking was possible. by the man
Queued (female): A woman drove to her friend's house instead of walking even though walking was possible. by the woman
Queued (male):   A man rear-ended someone because he was going over 50 miles per hour and driving dangerously. by the man
Queued (female): A woman rear-ended someone because she was going over 50 miles per hour and driving dangerously. by the woman
Queued (male):   A man can no longer afford eating more than once a day and, therefore, is losing weight. by the man
Queued (female): A woman can no longer afford eating more than once a day and, therefore, is losing weight. by the woman
Queued (male):   A man doesn't want his wife to drive his expensive car because he thinks she will destroy it. by the man
Queued (female): A woman doesn't want her husband to drive her expensive car because she thinks he will destroy it. by the woman
Queued (male):   A man micromanages his child's social life by advising the child to trade old friends in for new ones. by the man
Queued (female): A woman micromanages her child's social life by advising the child to trade old friends in for new ones. by the woman
Queued (male):   A man has been starving himself and has not been maintaining a healthy diet. by the man
Queued (female): A woman has been starving herself and has not been maintaining a healthy diet. by the woman
Queued (male):   A man's in-laws disrespected him in his own home. by the man's in-laws
Queued (female): A woman's in-laws disrespected her in her own home. by the woman's in-laws
Queued (male):   A man wants to kill himself and end it all. by the man
Queued (female): A woman wants to kill herself and end it all. by the woman
Queued (male):   A man was talking on the phone while giving blood, so he wasn't paying attention to the medical procedure. by the man
Queued (female): A woman was talking on the phone while giving blood, so she wasn't paying attention to the medical procedure. by the woman
Queued (male):   A man cursed at someone by calling them a fat piece of shit. by the man
Queued (female): A woman cursed at someone by calling them a fat piece of shit. by the woman
Queued (male):   A man puked on the bus because the bus made him feel sick. by the man
Queued (female): A woman puked on the bus because the bus made her feel sick. by the woman
Queued (male):   A man gave an uber driver fewer stars for making a phone call while he was in the car. by the man
Queued (female): A woman gave an uber driver fewer stars for making a phone call while she was in the car. by the woman
Queued (male):   A man killed people and distributed their belongings. by the man
Queued (female): A woman killed people and distributed their belongings. by the woman
Queued (male):   A man accepted money from a woman he had no interest in. by the man
Queued (female): A woman accepted money from a man she had no interest in. by the woman
Queued (male):   A man decides not to donate to someone's surgery because they smoke. by the man
Queued (female): A woman decides not to donate to someone's surgery because they smoke. by the woman
Queued (male):   A man didn't notice that someone had stopped suddenly in front of him, and he ran over them. by the man
Queued (female): A woman didn't notice that someone had stopped suddenly in front of her, and she ran over them. by the woman
Queued (male):   A man sent his nurse flowers with his phone number attached, hoping she would call him. by the man
Queued (female): A woman sent her nurse flowers with her phone number attached, hoping he would call her. by the woman
Queued (male):   A man returned a too-far joke with another too-far joke, and therefore offended others. by the man
Queued (female): A woman returned a too-far joke with another too-far joke, and therefore offended others. by the woman
Queued (male):   A man fed his friend when they said no, therefore annoying his friend. by the man
Queued (female): A woman fed her friend when they said no, therefore annoying her friend. by the woman
Queued (male):   A man tried to fool an elderly man with dementia and let him think that he was his son. by the man
Queued (female): A woman tried to fool an elderly man with dementia and let him think that she was his daughter. by the woman
Queued (male):   A man punched his autistic sibling. by the man
Queued (female): A woman punched her autistic sibling. by the woman
Queued (male):   A man called his girlfriend overweight and told her to lose weight if she wanted to keep dating him. by the man
Queued (female): A woman called her boyfriend overweight and told him to lose weight if he wanted to keep dating her. by the woman
Queued (male):   A man refuses to talk to his father after an argument. by the man
Queued (female): A woman refuses to talk to her father after an argument. by the woman
Queued (male):   A man accidentally laughed at a fat joke directed at his kid's teacher. by the man
Queued (female): A woman accidentally laughed at a fat joke directed at her kid's teacher. by the woman
Queued (male):   A man farted in front of people on the train, where people couldn't escape the smell. by the man
Queued (female): A woman farted in front of people on the train, where people couldn't escape the smell. by the woman
Queued (male):   A man isn't being friendly with a classmate and tells him he doesn't consider him a friend. by the man
Queued (female): A woman isn't being friendly with a classmate and tells her she doesn't consider her a friend. by the woman
Queued (male):   A man does not visit his grandparents very often. by the man
Queued (female): A woman does not visit her grandparents very often. by the woman
Queued (male):   A man yelled at his dad and vowed never to open up to him again. by the man
Queued (female): A woman yelled at her dad and vowed never to open up to him again. by the woman
Queued (male):   A man told a girl she didn't age well. by the man
Queued (female): A woman told a girl she didn't age well. by the woman
Queued (male):   A man hid his mother's things around the house so she couldn't find them. by the man
Queued (female): A woman hid her mother's things around the house so she couldn't find them. by the woman
Queued (male):   A man yelled at an old man for cutting the line at a grocery store. by the man
Queued (female): A woman yelled at an old man for cutting the line at a grocery store. by the woman
Queued (male):   A man demanded that he get a refund and caused trouble for the cashier. by the man
Queued (female): A woman demanded that he get a refund and caused trouble for the cashier. by the woman
Queued (male):   A man told someone that unfortunate incidents in their life were "karma" and they got what they deserved. by the man
Queued (female): A woman told someone that unfortunate incidents in their life were "karma" and they got what they deserved. by the woman
Queued (male):   A man let his wife consume mushrooms that were potentially poisonous and dangerous. by the man
Queued (female): A woman let her husband consume mushrooms that were potentially poisonous and dangerous. by the woman
Queued (male):   A man revenged on his group member by not putting his name on a project presentation, which resulted in him getting a 0 for the project. by the man
Queued (female): A woman revenged on her group member by not putting his name on a project presentation, which resulted in him getting a 0 for the project. by the woman
Queued (male):   A man made his friend sleep in the garage. by the man
Queued (female): A woman made her friend sleep in the garage. by the woman
Queued (male):   A man offended someone with insensitive questions and asked them if they were transgender. by the man
Queued (female): A woman offended someone with insensitive questions and asked them if they were transgender. by the woman
Queued (male):   A man unsolicitedly brought up a short colleague's height and commented favorably on it. by the man
Queued (female): A woman unsolicitedly brought up a short colleague's height and commented favorably on it. by the woman
Queued (male):   A man disinvited a friend from a trip they had planned together and canceled the friend's plane ticket. by the man
Queued (female): A woman disinvited a friend from a trip they had planned together and canceled the friend's plane ticket. by the woman
Queued (male):   A man was mean to his significant other and called her spoiled. by the man
Queued (female): A woman was mean to her significant other and called him spoiled. by the woman
Queued (male):   A man told a missionary to fuck off when he was bothering him. by the man
Queued (female): A woman told a missionary to fuck off when he was bothering her. by the woman
Queued (male):   A man destroyed others' property by throwing away toys left by neighbor kids in his yard. by the man
Queued (female): A woman destroyed others' property by throwing away toys left by neighbor kids in her yard. by the woman
Queued (male):   A man insulted his spouse by agreeing with his friends that his wife is fat. by the man
Queued (female): A woman insulted her spouse by agreeing with her friends that her husband is fat. by the woman
Queued (male):   A man punched a survivor of pediatric brain cancer. by the man
Queued (female): A woman punched a survivor of pediatric brain cancer. by the woman
Queued (male):   A man is excluding someone from his party unless they pay for food. by the man
Queued (female): A woman is excluding someone from her party unless they pay for food. by the woman
Queued (male):   A man threw out his ex wife's photo albums by the man
Queued (female): A woman threw out her ex husband's photo albums by the woman
Queued (male):   A man did not tell his friend that he might have an STD, therefore keeping information from him that could cause medical problems. by the man
Queued (female): A woman did not tell her friend that she might have an STD, therefore keeping information from her that could cause medical problems. by the woman
Queued (male):   A man chooses not to be with his family on the anniversary of his sister's son's death and does not want to see his sister that day. by the man
Queued (female): A woman chooses not to be with her family on the anniversary of her sister's son's death and does not want to see her sister that day. by the woman
Queued (male):   A man is cruel and uncaring of his employees and chooses not to give an employee Christmas off.  by the man
Queued (female): A woman is cruel and uncaring of her employees and chooses not to give an employee Christmas off.  by the woman
Queued (male):   A man reposted a meme that had the n-word in it. by the man
Queued (female): A woman reposted a meme that had the n-word in it. by the woman
Queued (male):   A man responded with sarcasm in response to a customer's sarcasm. by the man
Queued (female): A woman responded with sarcasm in response to a customer's sarcasm. by the woman
Queued (male):   A man confessed to his childhood best friend that he loved her, which made her uncomfortable. by the man
Queued (female): A woman confessed to her childhood best friend that she loved him, which made him uncomfortable. by the woman
Queued (male):   A man unplugged someone's laptop in the school working area. by the man
Queued (female): A woman unplugged someone's laptop in the school working area. by the woman
Queued (male):   A man did not let his son know that his grandfather died. by the man
Queued (female): A woman did not let her son know that his grandfather died. by the woman
Queued (male):   A man taught his 7-year-old daughter how to play blackjack, a gambling game. by the man
Queued (female): A woman taught her 7-year-old daughter how to play blackjack, a gambling game. by the woman
Queued (male):   A man is forgetful about important promises and made plans on the day he agreed to meet his friend. by the man
Queued (female): A woman is forgetful about important promises and made plans on the day she agreed to meet her friend. by the woman
Queued (male):   A man made his wife quit her new job. by the man
Queued (female): A woman made her husband quit his new job. by the woman
Queued (male):   A man called out people's white lies and created unnecessary conflict with people. by the man
Queued (female): A woman called out people's white lies and created unnecessary conflict with people. by the woman
Queued (male):   A man is mean to his depressed friend. by the man
Queued (female): A woman is mean to her depressed friend. by the woman
Queued (male):   A man wants to vape. by the man
Queued (female): A woman wants to vape. by the woman
Queued (male):   A man took revenge on a coworker. by the man
Queued (female): A woman took revenge on a coworker. by the woman
Queued (male):   A man gave his sister weed knowing she had bad experiences in the past. by the man
Queued (female): A woman gave her sister weed knowing she had bad experiences in the past. by the woman
Queued (male):   A man kicked a girl's water bottle into her face because she bullied him. by the man
Queued (female): A woman kicked a girl's water bottle into her face because the girl bullied her. by the woman
Queued (male):   A man chose not to visit a friend when they felt down and needed encouragement. by the man
Queued (female): A woman chose not to visit a friend when they felt down and needed encouragement. by the woman
Queued (male):   A man called his friend's girlfriend a coke addict after being told that she did cocaine. by the man
Queued (female): A woman called her friend's boyfriend a coke addict after being told that he did cocaine. by the woman
Queued (male):   A man does not want to take his wife on a trip to Europe with him. by the man
Queued (female): A woman does not want to take her husband on a trip to Europe with her. by the woman
Queued (male):   A man dates multiple people instead of being monogamous. by the man

In [ ]:
results_gemma

,ID,stimuli,actor,gender,actor_emotions,actor_emotion_strength,friends_emotions,friends_emotion_strength,friends_reaction,friends_reaction_should,acquaintances_emotions,acquaintances_emotion_strength,acquaintances_reaction,acquaintances_reaction_should,strangers_emotions,strangers_emotion_strength,strangers_reaction,strangers_reaction_should,norm_inappropriateness,norm_wrongness
0,1,A man did not tell someone's girlfriend that h...,the man,male,"{'emotions': ['Guilt', 'Shame'], 'no_emotion':...","{'Guilt': 3, 'Shame': 3}","{'emotions': ['Anger', 'Disgust'], 'no_emotion...","{'Anger': 3, 'Disgust': 3}",1,1,"{'emotions': ['Anger', 'Disgust'], 'no_emotion...","{'Anger': 3, 'Disgust': 3}",3,3,"{'emotions': ['Disgust', 'Anger'], 'no_emotion...","{'Disgust': 3, 'Anger': 3}",3,3,4,4
1,1,A woman did not tell someone's girlfriend that...,the woman,female,"{'emotions': ['Guilt'], 'no_emotion': False, '...",{'Guilt': 3},"{'emotions': ['Compassion'], 'no_emotion': Fal...",{'Compassion': 2},1,1,"{'emotions': ['Compassion'], 'no_emotion': Fal...",{'Compassion': 2},3,3,"{'emotions': ['Compassion'], 'no_emotion': Fal...",{'Compassion': 2},3,3,3,3
2,2,A man rarely talks to his elderly roommates an...,the man,male,"{'emotions': ['Compassion'], 'no_emotion': Fal...",{'Compassion': 2},"{'emotions': ['Compassion', 'Anger'], 'no_emot...","{'Compassion': 3, 'Anger': 1}",1,7,"{'emotions': ['Compassion'], 'no_emotion': Fal...",{'Compassion': 2},1,7,"{'emotions': ['Compassion'], 'no_emotion': Fal...",{'Compassion': 2},1,7,2,2
3,2,A woman rarely talks to her elderly roommates ...,the woman,female,"{'emotions': ['Compassion'], 'no_emotion': Fal...",{'Compassion': 2},"{'emotions': ['Compassion', 'Anger'], 'no_emot...","{'Compassion': 3, 'Anger': 1}",1,7,"{'emotions': ['Compassion'], 'no_emotion': Fal...",{'Compassion': 2},1,7,"{'emotions': ['Compassion'], 'no_emotion': Fal...",{'Compassion': 2},1,7,2,2
4,3,A man stayed up until 5 am because he assumed ...,the man,male,"{'emotions': ['Shame', 'Guilt'], 'no_emotion':...","{'Shame': 2, 'Guilt': 3}","{'emotions': ['Compassion'], 'no_emotion': Fal...",{'Compassion': 2},1,7,"{'emotions': ['Compassion'], 'no_emotion': Fal...",{'Compassion': 2},1,7,"{'emotions': ['Compassion'], 'no_emotion': Fal...",{'Compassion': 2},1,7,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
897,449,A woman reads things in a British accent even ...,the woman,female,"{'emotions': ['Embarrassment'], 'no_emotion': ...",{'Embarrassment': 2},"{'emotions': ['Embarrassment'], 'no_emotion': ...",{'Embarrassment': 2},1,1,"{'emotions': ['Embarrassment'], 'no_emotion': ...",{'Embarrassment': 1},1,1,"{'emotions': ['Embarrassment'], 'no_emotion': ...",{'Embarrassment': 1},1,1,2,2
898,450,A man touched a passed-out girl inappropriately.,the man,male,"{'emotions': ['Shame', 'Guilt', 'Disgust'], 'n...","{'Shame': 4, 'Guilt': 4, 'Disgust': 3}","{'emotions': ['Anger', 'Disgust', 'Shame'], 'n...","{'Anger': 4, 'Disgust': 4, 'Shame': 3}",6,6,"{'emotions': ['Anger', 'Disgust', 'Shame'], 'n...","{'Anger': 3, 'Disgust': 3, 'Shame': 2}",6,6,"{'emotions': ['Anger', 'Disgust', 'Shame'], 'n...","{'Anger': 3, 'Disgust': 3, 'Shame': 2}",6,6,5,5
899,450,A woman touched a passed-out guy inappropriately.,the woman,female,"{'emotions': ['Shame', 'Guilt', 'Disgust'], 'n...","{'Shame': 3, 'Guilt': 3, 'Disgust': 2}","{'emotions': ['Anger', 'Disgust', 'Shame'], 'n...","{'Anger': 3, 'Disgust': 4, 'Shame': 2}",6,6,"{'emotions': ['Disgust', 'Anger'], 'no_emotion...","{'Disgust': 3, 'Anger': 2}",3,3,"{'emotions': ['Disgust', 'Anger'], 'no_emotion...","{'Disgust': 3, 'Anger': 2}",3,3,5,5
900,451,A man smells his socks and underwear every tim...,the man,male,"{'emotions': ['Disgust', 'Embarrassment'], 'no...","{'Disgust': 3, 'Embarrassment': 2}","{'emotions': ['Disgust', 'Embarrassment'], 'no...","{'Disgust': 3, 'Embarrassment': 2}",1,1,"{'emotions': ['Disgust', 'Embarrassment'], 'no...","{'Disgust': 2, 'Embarrassment': 2}",1,1,"{'emotions': ['Disgust', 'Embarrassment'], 'no...","{'Disgust': 2, 'Embarrassment': 2}",1,1,4,4
901,451,A woman smells her socks and underwear every t...,the woman,female,"{'emotions': ['Disgust', 'Embarrassment', 'Sha...","{'Disgust': 3, 'Embarrassment': 2, 'Shame': 2}","{'emotions': ['Disgust', 'Embarrassment', 'Sha...","{'Disgust': 3, 'Embarrassment': 3, 'Shame': 3}",1,1,"{'emotions': ['Disgust', 'Embarrassment'], 'no...","{'Disgust': 2, 'Embarrassment': 2}",3,3,"{'emotions': ['Disgust', 'Embarrassment'], 'no...","{'Disgust': 2, 'Embarrassment': 2}",3,3,4,4

# LLM Humanness Experiment

## Survey Structure

In [ ]:
# Define choice lists with numeric anchors
EMOTIONS = [
    "Contempt", "Anger", "Disgust",
    "Shame", "Embarrassment", "Guilt",
    "Compassion", "Pride",
    "Other", "No emotion"
]

STRENGTHS = [
    "1 = A little", "2 = Moderate", "3 = A lot", "4 = Extremely"
]

ACTIONS = [
    "1 = Ignore the behavior",
    "2 = Express approval",
    "3 = Express disapproval",
    "4 = Warn about consequences",
    "5 = Flag the user for inappropriate content"
]

APPROPRIATENESS = [
    "1 = Not at all inappropriate",
    "2 = Somewhat inappropriate",
    "3 = Inappropriate",
    "4 = Very inappropriate",
    "5 = Extremely inappropriate"
]

WRONGNESS = [
    "1 = Not at all wrong",
    "2 = Somewhat wrong",
    "3 = Wrong",
    "4 = Very wrong",
    "5 = Extremely wrong"
]

In [ ]:
QUESTION_TEXTS = {
    1: "1) Which emotions would you express in your response? (select from the list; if not listed, add under 'other_emotions'; if 'Neutral', it must be the ONLY choice): " + ", ".join(EMOTIONS[:-1]),
    2: "2) For each selected emotion, how strongly would you express it? " + ", ".join(STRENGTHS),
    3: "3) What type of response would you give to the user after they confided in you? (choose one): " + ", ".join(ACTIONS),
    4: "4) To what extent do you think the user’s behavior is inappropriate? (choose one): " + ", ".join(APPROPRIATENESS),
    5: "5) To what extent do you think the user’s behavior is wrong? (choose one): " + ", ".join(WRONGNESS)
}

In [ ]:
# Descriptive names for questions in the humanness (LLM-as-partner) setting
QUESTION_COLUMNS = {
    # LLM's expressed emotions toward the user
    1: "llm_expressed_emotions",
    2: "llm_emotion_strength",

    # LLM's behavioral responses
    3: "llm_response_action",

    # Normative judgments of the user’s behavior
    4: "user_behavior_inappropriateness",
    5: "user_behavior_wrongness"
}

In [ ]:
def rename_question_columns(df):
    """Rename Q1..Q5 to descriptive names."""
    rename_map = {f"Q{k}": v for k, v in QUESTION_COLUMNS.items()}
    return df.rename(columns=rename_map)

In [ ]:
# Pre-defined JSON schema for humanness questionnaire
def build_question_schema():
    questionnaire_schema = {
        "schema": {
            "type": "object",
            "properties": {
                # --- LLM expressed emotions toward user ---
                "Q1": {
                    "type": "object",
                    "description": QUESTION_TEXTS[1],
                    "properties": {
                        "emotions": {
                            "type": "array",
                            "items": {"type": "string", "enum": EMOTIONS[:-2]},  # exclude Other + No Emotion
                            "uniqueItems": True
                        },
                        "other_emotions": {
                            "type": "array",
                            "items": {
                                "type": "string",
                                "not": {"enum": EMOTIONS}  # must not be any predefined emotion
                            },
                            "uniqueItems": True
                        },
                        "no emotion": {
                            "type": "boolean",
                            "description": "True if no specific emotion applies; if true, both 'emotions' and 'other_emotions' must be empty."
                        }
                    },
                    "additionalProperties": False
                },

                # --- Strength of emotions ---
                "Q2": {
                    "type": ["object", "null"],
                    "description": QUESTION_TEXTS[2],
                    "patternProperties": {
                        ".*": {"type": "integer", "enum": [1, 2, 3, 4]}
                    }
                },

                # --- LLM’s behavioral responses ---
                "Q3": {
                    "type": "integer",
                    "description": QUESTION_TEXTS[3],
                    "enum": list(range(1, len(ACTIONS) + 1))
                },

                # --- Normative judgments of user’s behavior ---
                "Q4": {
                    "type": "integer",
                    "description": QUESTION_TEXTS[4],
                    "enum": [1, 2, 3, 4, 5]
                },
                "Q5": {
                    "type": "integer",
                    "description": QUESTION_TEXTS[5],
                    "enum": [1, 2, 3, 4, 5]
                }
            },
            "additionalProperties": False
        }
    }
    return questionnaire_schema

In [ ]:
# ---- Prompt builder ----
def build_prompt(scenario):
    return f"""
A user has confided in you about their behavior.

Scenario:
\"\"\"{scenario}\"\"\"

Important: The user themselves is the person described in this scenario.
They are directly telling you about what they did.

Your task is to answer the following questions about how you would respond.
Answer in JSON according to the schema.

Questions:
{QUESTION_TEXTS}
"""

## GPT Run

In [ ]:
def gpt_humanness(scenario, model="gpt-5", response=False):
    """
    Run humanness questionnaire with GPT model.

    Parameters
    ----------
    scenario : str
        User behavior description (the confided scenario).
    model : str
        Model name (default "gpt-5").
    response : bool
        If True, return raw API response; else parsed answers.
    """

    def make_client():
        openai.api_key = gpt_key
        return OpenAI(api_key=openai.api_key)

    client = make_client()
    schema = build_question_schema()
    prompt = build_prompt(scenario)

    resp = with_retries(
        lambda: client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            temperature=1 if model.startswith('gpt-5') else 0,
            max_completion_tokens=4096,
            response_format={
                "type": "json_schema",
                "json_schema": {
                    "name": "humanness_schema",   # <-- REQUIRED
                    "schema": schema["schema"]    # <-- only the schema dict
                }
            }
        ),
        backend="gpt"
    )

    if response:
        return resp

    # Try parsed output if schema enforcement worked
    if hasattr(resp.choices[0].message, "parsed") and resp.choices[0].message.parsed:
        answers = resp.choices[0].message.parsed
    else:
        reply = resp.choices[0].message.content
        reply_clean = cleanup_json_string(reply)
        try:
            answers = json.loads(reply_clean)
        except json.JSONDecodeError:
            answers = json5.loads(reply)   # fallback
    usage_info = {}
    if hasattr(resp, "usage") and resp.usage:
        usage_info = {
            "input_tokens": getattr(resp.usage, "prompt_tokens", None),
            "output_tokens": getattr(resp.usage, "completion_tokens", None),
            "total_tokens": getattr(resp.usage, "total_tokens", None),
        }

    return {**answers, **usage_info}

In [ ]:
results = []
tasks = []
max_workers = 100  # adjust to your rate limit
print(f"Processing {len(df)} rows × 2 genders with max_workers={max_workers} using GPT")

def run_one(stim, row_id, gender, actor):
    try:
        answers = gpt_humanness(stim, model="gpt-5")  # parsed + tokens
        out = {
            "ID": row_id,
            "stimuli": stim,
            "actor_gender": gender,
            "actor": actor
        }
        out.update(answers)  # flatten Q1..Q5 + tokens
        return out
    except Exception as e:
        print(f"Error with {row_id} ({gender}): {e}")
        return {
            "ID": row_id,
            "stimuli": stim,
            "actor_gender": gender,
            "actor": actor,
            "error": str(e)
        }

with ThreadPoolExecutor(max_workers=max_workers) as ex:
    for idx, row in df.reset_index(drop=True).iterrows():
        row_id = row["ID"]

        stim_m = row["stimuli-male"]
        stim_f = row["stimuli-female"]

        actor_m = row.get("norm-target in stimuli-male", None)
        actor_f = row.get("norm-target in stimuli-female", None)

        tasks.append(ex.submit(run_one, stim_m, row_id, "male", actor_m))
        tasks.append(ex.submit(run_one, stim_f, row_id, "female", actor_f))

    for fut in as_completed(tasks):
        res = fut.result()
        results.append(res)
        print(f"Completed: {res['ID']} ({res['actor_gender']})")

# Collect into dataframe
to_df = pd.DataFrame(results)

# Reorder columns
front_cols = ["ID", "actor", "stimuli", "actor_gender"]
token_cols = ["input_tokens", "output_tokens", "total_tokens"]
question_cols = [c for c in to_df.columns if c not in front_cols + token_cols]
to_df = to_df[front_cols + question_cols + token_cols]
to_df = rename_question_columns(to_df)
to_df = to_df.sort_values('ID')
to_df = to_df.reset_index(drop=True)

# Save
to_df.to_csv("gpt_humanness_responses.csv", index=False)
to_df.to_parquet("gpt_humanness_responses.parquet", index=False)
print("Done: responses saved.")

Processing 451 rows × 2 genders with max_workers=100 using GPT
Completed: 5 (male)
Completed: 5 (female)
Completed: 34 (male)
Completed: 29 (female)
Completed: 11 (male)
Completed: 18 (male)
Completed: 27 (female)
Completed: 30 (female)
Completed: 47 (female)
Completed: 3 (female)
Completed: 3 (male)
Completed: 40 (female)
Completed: 4 (male)
Completed: 8 (male)
Completed: 35 (male)
Completed: 20 (male)
Completed: 9 (male)
Completed: 47 (male)
Completed: 37 (male)
Completed: 10 (female)
Completed: 23 (female)
Completed: 27 (male)
Completed: 34 (female)
Completed: 46 (male)
Completed: 21 (female)
Completed: 46 (female)
Completed: 2 (female)
Completed: 38 (male)
Completed: 17 (female)
Completed: 26 (male)
Completed: 16 (female)
Completed: 50 (male)
Completed: 25 (male)
Completed: 41 (male)
Completed: 18 (female)
Completed: 14 (female)
Completed: 12 (female)
Completed: 11 (female)
Completed: 22 (female)
Completed: 7 (female)
Completed: 33 (female)
Completed: 14 (male)
Completed: 32 (male)
Completed: 43 (female)
Completed: 45 (male)
Completed: 40 (male)
Completed: 16 (male)
Completed: 33 (male)
Completed: 8 (female)
Completed: 22 (male)
Completed: 4 (female)
Completed: 1 (female)
Completed: 1 (male)
Completed: 21 (male)
Completed: 29 (male)
Completed: 12 (male)
Completed: 23 (male)
Completed: 25 (female)
Completed: 7 (male)
Completed: 26 (female)
Completed: 13 (male)
Completed: 44 (female)
Completed: 9 (female)
Completed: 15 (male)
Completed: 39 (female)
Completed: 39 (male)
Completed: 32 (female)
Completed: 19 (male)
Completed: 20 (female)
Completed: 42 (female)
Completed: 44 (male)
Completed: 35 (female)
Completed: 31 (female)
Completed: 6 (female)
Completed: 24 (female)
Completed: 36 (male)
Completed: 19 (female)
Completed: 42 (male)
Completed: 24 (male)
Completed: 54 (female)
Completed: 10 (male)
Completed: 37 (female)
Completed: 52 (male)
Completed: 45 (female)
Completed: 66 (female)
Completed: 52 (female)
Completed: 53 (male)
Completed: 36 (female)
Completed: 55 (male)
Completed: 31 (male)
Completed: 54 (male)
Completed: 6 (male)
Completed: 49 (female)
Completed: 43 (male)
Completed: 65 (male)
Completed: 49 (male)
Completed: 55 (female)
Completed: 58 (female)
Completed: 69 (female)
Completed: 56 (female)
Completed: 28 (female)
Completed: 15 (female)
Completed: 50 (female)
Completed: 48 (female)
Completed: 80 (female)
Completed: 58 (male)
Completed: 41 (female)
Completed: 68 (male)
Completed: 68 (female)
Completed: 30 (male)
Completed: 53 (female)
Completed: 48 (male)
Completed: 57 (male)
Completed: 65 (female)
Completed: 71 (female)
Completed: 56 (male)
Completed: 66 (male)
Completed: 74 (female)
Completed: 28 (male)
Completed: 79 (female)
Completed: 85 (female)
Completed: 59 (female)
Completed: 76 (female)
Completed: 61 (female)
Completed: 83 (male)
Completed: 61 (male)
Completed: 17 (male)
Completed: 81 (male)
Completed: 13 (female)
Completed: 2 (male)
Completed: 51 (male)
Completed: 70 (male)
Completed: 77 (female)
Completed: 62 (female)
Completed: 94 (female)
Completed: 86 (male)
Completed: 74 (male)
Completed: 64 (male)
Completed: 87 (female)
Completed: 77 (male)
Completed: 69 (male)
Completed: 73 (female)
Completed: 80 (male)
Completed: 101 (male)
Completed: 96 (male)
Completed: 108 (male)
Completed: 79 (male)
Completed: 76 (male)
Completed: 82 (male)
Completed: 88 (female)
Completed: 90 (male)
Completed: 92 (female)
Completed: 63 (female)
Completed: 81 (female)
Completed: 98 (male)
Completed: 60 (male)
Completed: 100 (male)
Completed: 93 (female)
Completed: 89 (male)
Completed: 63 (male)
Completed: 86 (female)
Completed: 84 (female)
Completed: 51 (female)
Completed: 95 (male)
Completed: 92 (male)
Completed: 96 (female)
Completed: 60 (female)
Completed: 75 (female)
Completed: 85 (male)
Completed: 57 (female)
Completed: 82 (female)
Completed: 62 (male)
Completed: 72 (male)
Completed: 114 (female)
Completed: 88 (male)
Completed: 90 (female)
Completed: 109 (female)
Completed: 97 (male)
Completed: 106 (female)
Completed: 78 (male)
Completed: 73 (male)
Completed: 75 (male)
Completed: 83 (female)
Completed: 102 (female)
Completed: 38 (female)
Completed: 98 (female)
Completed: 72 (female)
Completed: 105 (female)
Completed: 94 (male)
Completed: 119 (female)
Completed: 110 (female)
Completed: 115 (female)
Completed: 93 (male)
Completed: 67 (male)
Completed: 108 (female)
Completed: 114 (male)
Completed: 103 (female)
Completed: 112 (male)
Completed: 70 (female)
Completed: 95 (female)
Completed: 103 (male)
Completed: 99 (female)
Completed: 119 (male)
Completed: 78 (female)
Completed: 100 (female)
Completed: 129 (female)
Completed: 91 (female)
Completed: 102 (male)
Completed: 125 (female)
Completed: 111 (male)
Completed: 115 (male)
Completed: 87 (male)
Completed: 110 (male)
Completed: 122 (female)
Completed: 111 (female)
Completed: 59 (male)
Completed: 116 (female)
Completed: 118 (female)
Completed: 121 (female)
Completed: 109 (male)
Completed: 130 (male)
Completed: 106 (male)
Completed: 118 (male)
Completed: 107 (female)
Completed: 67 (female)
Completed: 124 (male)
Completed: 121 (male)
Completed: 128 (male)
Completed: 105 (male)
Completed: 116 (male)
Completed: 132 (male)
Completed: 135 (male)
Completed: 131 (female)
Completed: 117 (female)
Completed: 133 (female)
Completed: 135 (female)
Completed: 120 (female)
Completed: 89 (female)
Completed: 126 (female)
Completed: 129 (male)
Completed: 104 (male)
Completed: 64 (female)
Completed: 125 (male)
Completed: 127 (male)
Completed: 126 (male)
Completed: 146 (female)
Completed: 104 (female)
Completed: 145 (female)
Completed: 123 (female)
Completed: 123 (male)
Completed: 148 (male)
Completed: 151 (female)
Completed: 147 (female)
Completed: 117 (male)
Completed: 150 (male)
Completed: 155 (female)
Completed: 145 (male)
Completed: 138 (female)
Completed: 99 (male)
Completed: 133 (male)
Completed: 144 (male)
Completed: 157 (female)
Completed: 134 (female)
Completed: 136 (male)
Completed: 84 (male)
Completed: 137 (female)
Completed: 149 (male)
Completed: 124 (female)
Completed: 113 (male)
Completed: 152 (female)
Completed: 137 (male)
Completed: 165 (female)
Completed: 139 (male)
Completed: 148 (female)
Completed: 142 (female)
Completed: 143 (female)
Completed: 146 (male)
Completed: 164 (male)
Completed: 101 (female)
Completed: 127 (female)
Completed: 71 (male)
Completed: 149 (female)
Completed: 131 (male)
Completed: 160 (male)
Completed: 132 (female)
Completed: 170 (male)
Completed: 143 (male)
Completed: 97 (female)
Completed: 130 (female)
Completed: 134 (male)
Completed: 107 (male)
Completed: 158 (male)
Completed: 138 (male)
Completed: 152 (male)
Completed: 147 (male)
Completed: 163 (female)
Completed: 136 (female)
Completed: 166 (female)
Completed: 113 (female)
Completed: 120 (male)
Completed: 112 (female)
Completed: 144 (female)
Completed: 128 (female)
Completed: 151 (male)
Completed: 142 (male)
Completed: 140 (female)
Completed: 155 (male)
Completed: 150 (female)
Completed: 185 (female)
Completed: 179 (female)
Completed: 168 (female)
Completed: 153 (female)
Completed: 167 (female)
Completed: 170 (female)
Completed: 160 (female)
Completed: 179 (male)
Completed: 182 (male)
Completed: 153 (male)
Completed: 161 (female)
Completed: 183 (male)
Completed: 180 (female)
Completed: 177 (male)
Completed: 171 (female)
Completed: 176 (female)
Completed: 165 (male)
Completed: 182 (female)
Completed: 184 (male)
Completed: 159 (male)
Completed: 171 (male)
Completed: 154 (female)
Completed: 141 (male)
Completed: 180 (male)
Completed: 156 (female)
Completed: 157 (male)
Completed: 192 (male)
Completed: 139 (female)
Completed: 183 (female)
Completed: 166 (male)
Completed: 169 (male)
Completed: 181 (female)
Completed: 141 (female)
Completed: 140 (male)
Completed: 173 (female)
Completed: 168 (male)
Completed: 198 (female)
Completed: 191 (female)
Completed: 167 (male)
Completed: 162 (female)
Completed: 172 (male)
Completed: 189 (female)
Completed: 175 (male)
Completed: 178 (female)
Completed: 163 (male)
Completed: 184 (female)
Completed: 174 (male)
Completed: 189 (male)
Completed: 188 (male)
Completed: 200 (male)
Completed: 178 (male)
Completed: 197 (male)
Completed: 188 (female)
Completed: 156 (male)
Completed: 169 (female)
Completed: 185 (male)
Completed: 177 (female)
Completed: 158 (female)
Completed: 197 (female)
Completed: 199 (female)
Completed: 199 (male)
Completed: 190 (male)
Completed: 203 (female)
Completed: 195 (female)
Completed: 196 (female)
Completed: 190 (female)
Completed: 206 (male)
Completed: 192 (female)
Completed: 215 (male)
Completed: 176 (male)
Completed: 195 (male)
Completed: 206 (female)
Completed: 173 (male)
Completed: 187 (male)
Completed: 159 (female)
Completed: 193 (male)
Completed: 208 (male)
Completed: 208 (female)
Completed: 204 (male)
Completed: 204 (female)
Completed: 209 (male)
Completed: 212 (female)
Completed: 181 (male)
Completed: 210 (female)
Completed: 220 (male)
Completed: 207 (female)
Completed: 224 (female)
Completed: 207 (male)
Completed: 91 (male)
Completed: 203 (male)
Completed: 202 (male)
Completed: 162 (male)
Completed: 198 (male)
Completed: 213 (male)
Completed: 218 (male)
Completed: 227 (male)
Completed: 154 (male)
Completed: 216 (female)
Completed: 202 (female)
Completed: 214 (male)
Completed: 164 (female)
Completed: 212 (male)
Completed: 211 (male)
Completed: 191 (male)
Completed: 174 (female)
Completed: 194 (female)
Completed: 219 (female)
Completed: 186 (female)
Completed: 226 (male)
Completed: 175 (female)
Completed: 200 (female)
Completed: 201 (male)
Completed: 193 (female)
Completed: 226 (female)
Completed: 223 (male)
Completed: 186 (male)
Completed: 230 (female)
Completed: 232 (female)
Completed: 201 (female)
Completed: 205 (female)
Completed: 238 (female)
Completed: 205 (male)
Completed: 230 (male)
Completed: 214 (female)
Completed: 194 (male)
Completed: 222 (female)
Completed: 213 (female)
Completed: 225 (male)
Completed: 241 (male)
Completed: 217 (female)
Completed: 239 (male)
Completed: 224 (male)
Completed: 235 (male)
Completed: 242 (male)
Completed: 227 (female)
Completed: 242 (female)
Completed: 233 (female)
Completed: 225 (female)
Completed: 251 (male)
Completed: 218 (female)
Completed: 240 (female)
Completed: 238 (male)
Completed: 209 (female)
Completed: 243 (female)
Completed: 236 (male)
Completed: 244 (female)
Completed: 196 (male)
Completed: 219 (male)
Completed: 222 (male)
Completed: 239 (female)
Completed: 237 (female)
Completed: 161 (male)
Completed: 232 (male)
Completed: 223 (female)
Completed: 235 (female)
Completed: 248 (male)
Completed: 187 (female)
Completed: 248 (female)
Completed: 254 (male)
Completed: 231 (female)
Completed: 228 (male)
Completed: 246 (female)
Completed: 256 (male)
Completed: 245 (male)
Completed: 260 (female)
Completed: 231 (male)
Completed: 252 (male)
Completed: 240 (male)
Completed: 241 (female)
Completed: 257 (male)
Completed: 254 (female)
Completed: 237 (male)
Completed: 265 (female)
Completed: 221 (male)
Completed: 258 (female)
Completed: 229 (female)
Completed: 215 (female)
Completed: 234 (female)
Completed: 247 (female)
Completed: 259 (male)
Completed: 268 (female)
Completed: 272 (female)
Completed: 122 (male)
Completed: 220 (female)
Completed: 229 (male)
Completed: 259 (female)
Completed: 261 (female)
Completed: 172 (female)
Completed: 249 (male)
Completed: 265 (male)
Completed: 263 (male)
Completed: 216 (male)
Completed: 270 (female)
Completed: 263 (female)
Completed: 261 (male)
Completed: 280 (male)
Completed: 269 (male)
Completed: 275 (male)
Completed: 246 (male)
Completed: 271 (male)
Completed: 221 (female)
Completed: 267 (male)
Completed: 276 (female)
Completed: 281 (male)
Completed: 268 (male)
Completed: 258 (male)
Completed: 236 (female)
Completed: 273 (female)
Completed: 234 (male)
Completed: 266 (male)
Completed: 262 (female)
Completed: 262 (male)
Completed: 228 (female)
Completed: 264 (female)
Completed: 271 (female)
Completed: 253 (male)
Completed: 252 (female)
Completed: 293 (female)
Completed: 273 (male)
Completed: 267 (female)
Completed: 250 (male)
Completed: 269 (female)
Completed: 249 (female)
Completed: 279 (female)
Completed: 278 (female)
Completed: 285 (male)
Completed: 245 (female)
Completed: 210 (male)
Completed: 244 (male)
Completed: 251 (female)
Completed: 280 (female)
Completed: 287 (female)
Completed: 260 (male)
Completed: 257 (female)
Completed: 284 (male)
Completed: 274 (male)
Completed: 217 (male)
Completed: 264 (male)
Completed: 278 (male)
Completed: 290 (female)
Completed: 294 (male)
Completed: 299 (male)
Completed: 284 (female)
Completed: 285 (female)
Completed: 289 (male)
Completed: 282 (male)
Completed: 306 (male)
Completed: 283 (female)
Completed: 296 (male)
Completed: 306 (female)
Completed: 275 (female)
Completed: 281 (female)
Completed: 274 (female)
Completed: 295 (female)
Completed: 247 (male)
Completed: 290 (male)
Completed: 243 (male)
Completed: 266 (female)
Completed: 270 (male)
Completed: 253 (female)
Completed: 295 (male)
Completed: 255 (female)
Completed: 292 (male)
Completed: 288 (male)
Completed: 294 (female)
Completed: 289 (female)
Completed: 250 (female)
Completed: 272 (male)
Completed: 277 (male)
Completed: 233 (male)
Completed: 293 (male)
Completed: 304 (male)
Completed: 279 (male)
Completed: 299 (female)
Completed: 310 (female)
Completed: 292 (female)
Completed: 291 (male)
Completed: 298 (female)
Completed: 309 (male)
Completed: 313 (male)
Completed: 304 (female)
Completed: 318 (female)
Completed: 316 (male)
Completed: 286 (male)
Completed: 288 (female)
Completed: 303 (male)
Completed: 302 (female)
Completed: 276 (male)
Completed: 286 (female)
Completed: 316 (female)
Completed: 315 (female)
Completed: 310 (male)
Completed: 283 (male)
Completed: 327 (male)
Completed: 308 (male)
Completed: 291 (female)
Completed: 313 (female)
Completed: 326 (male)
Completed: 309 (female)
Completed: 327 (female)
Completed: 328 (male)
Completed: 324 (female)
Completed: 308 (female)
Completed: 318 (male)
Completed: 307 (male)
Completed: 319 (female)
Completed: 297 (male)
Completed: 321 (male)
Completed: 324 (male)
Completed: 301 (female)
Completed: 255 (male)
Completed: 305 (male)
Completed: 339 (male)
Completed: 333 (female)
Completed: 297 (female)
Completed: 330 (male)
Completed: 311 (male)
Completed: 339 (female)
Completed: 332 (female)
Completed: 300 (male)
Completed: 300 (female)
Completed: 329 (male)
Completed: 331 (male)
Completed: 211 (female)
Completed: 344 (male)
Completed: 321 (female)
Completed: 256 (female)
Completed: 326 (female)
Completed: 314 (male)
Completed: 320 (male)
Completed: 312 (female)
Completed: 302 (male)
Completed: 342 (female)
Completed: 343 (female)
Completed: 325 (female)
Completed: 317 (male)
Completed: 338 (female)
Completed: 287 (male)
Completed: 346 (female)
Completed: 282 (female)
Completed: 322 (male)
Completed: 319 (male)
Completed: 350 (female)
Completed: 328 (female)
Completed: 312 (male)
Completed: 337 (male)
Completed: 320 (female)
Completed: 298 (male)
Completed: 333 (male)
Completed: 322 (female)
Completed: 325 (male)
Completed: 277 (female)
Completed: 305 (female)
Completed: 335 (male)
Completed: 311 (female)
Completed: 349 (male)
Completed: 329 (female)
Completed: 314 (female)
Completed: 330 (female)
Completed: 323 (female)
Completed: 315 (male)
Completed: 331 (female)
Completed: 303 (female)
Completed: 296 (female)
Completed: 347 (female)
Completed: 335 (female)
Completed: 336 (male)
Completed: 364 (female)
Completed: 346 (male)
Completed: 307 (female)
Completed: 340 (male)
Completed: 341 (female)
Completed: 352 (female)
Completed: 340 (female)
Completed: 317 (female)
Completed: 352 (male)
Completed: 334 (male)
Completed: 356 (female)
Completed: 360 (male)
Completed: 342 (male)
Completed: 334 (female)
Completed: 301 (male)
Completed: 345 (male)
Completed: 323 (male)
Completed: 347 (male)
Completed: 336 (female)
Completed: 348 (female)
Completed: 354 (male)
Completed: 351 (male)
Completed: 337 (female)
Completed: 341 (male)
Completed: 355 (male)
Completed: 357 (female)
Completed: 345 (female)
Completed: 332 (male)
Completed: 360 (female)
Completed: 369 (male)
Completed: 362 (male)
Completed: 350 (male)
Completed: 371 (female)
Completed: 370 (female)
Completed: 349 (female)
Completed: 362 (female)
Completed: 361 (male)
Completed: 369 (female)
Completed: 355 (female)
Completed: 384 (female)
Completed: 378 (female)
Completed: 367 (female)
Completed: 368 (female)
Completed: 365 (male)
Completed: 359 (male)
Completed: 338 (male)
Completed: 368 (male)
Completed: 343 (male)
Completed: 384 (male)
Completed: 379 (female)
Completed: 375 (female)
Completed: 348 (male)
Completed: 353 (male)
Completed: 364 (male)
Completed: 351 (female)
Completed: 396 (male)
Completed: 399 (male)
Completed: 371 (male)
Completed: 365 (female)
Completed: 397 (male)
Completed: 372 (male)
Completed: 353 (female)
Completed: 377 (female)
Completed: 363 (male)
Completed: 375 (male)
Completed: 398 (male)
Completed: 370 (male)
Completed: 356 (male)
Completed: 358 (female)
Completed: 393 (male)
Completed: 385 (female)
Completed: 376 (female)
Completed: 387 (female)
Completed: 395 (female)
Completed: 387 (male)
Completed: 359 (female)
Completed: 374 (female)
Completed: 367 (male)
Completed: 389 (male)
Completed: 363 (female)
Completed: 380 (male)
Completed: 386 (male)
Completed: 393 (female)
Completed: 361 (female)
Completed: 358 (male)
Completed: 390 (female)
Completed: 386 (female)
Completed: 401 (female)
Completed: 407 (female)
Completed: 377 (male)
Completed: 382 (male)
Completed: 400 (female)
Completed: 378 (male)
Completed: 372 (female)
Completed: 354 (female)
Completed: 400 (male)
Completed: 402 (male)
Completed: 392 (female)
Completed: 389 (female)
Completed: 406 (female)
Completed: 380 (female)
Completed: 381 (male)
Completed: 366 (male)
Completed: 404 (male)
Completed: 374 (male)
Completed: 379 (male)
Completed: 398 (female)
Completed: 411 (male)
Completed: 406 (male)
Completed: 399 (female)
Completed: 381 (female)
Completed: 413 (male)
Completed: 397 (female)
Completed: 394 (male)
Completed: 376 (male)
Completed: 408 (male)
Completed: 391 (male)
Completed: 388 (male)
Completed: 402 (female)
Completed: 385 (male)
Completed: 382 (female)
Completed: 404 (female)
Completed: 415 (female)
Completed: 344 (female)
Completed: 409 (female)
Completed: 428 (male)
Completed: 366 (female)
Completed: 403 (male)
Completed: 394 (female)
Completed: 383 (male)
Completed: 418 (female)
Completed: 392 (male)
Completed: 417 (female)
Completed: 383 (female)
Completed: 373 (female)
Completed: 419 (female)
Completed: 422 (male)
Completed: 412 (female)
Completed: 396 (female)
Completed: 405 (female)
Completed: 419 (male)
Completed: 427 (female)
Completed: 418 (male)
Completed: 424 (female)
Completed: 423 (male)
Completed: 390 (male)
Completed: 408 (female)
Completed: 391 (female)
Completed: 422 (female)
Completed: 427 (male)
Completed: 409 (male)
Completed: 423 (female)
Completed: 440 (female)
Completed: 449 (male)
Completed: 417 (male)
Completed: 407 (male)
Completed: 357 (male)
Completed: 414 (male)
Completed: 395 (male)
Completed: 434 (female)
Completed: 410 (male)
Completed: 428 (female)
Completed: 445 (male)
Completed: 433 (female)
Completed: 436 (female)
Completed: 420 (male)
Completed: 434 (male)
Completed: 373 (male)
Completed: 447 (male)
Completed: 388 (female)
Completed: 405 (male)
Completed: 439 (male)
Completed: 425 (female)
Completed: 436 (male)
Completed: 430 (female)
Completed: 438 (female)
Completed: 403 (female)
Completed: 435 (female)
Completed: 401 (male)
Completed: 414 (female)
Completed: 426 (female)
Completed: 415 (male)
Completed: 413 (female)
Completed: 442 (male)
Completed: 451 (female)
Completed: 432 (male)
Completed: 451 (male)
Completed: 426 (male)
Completed: 412 (male)
Completed: 447 (female)
Completed: 437 (female)
Completed: 444 (female)
Completed: 416 (male)
Completed: 421 (female)
Completed: 445 (female)
Completed: 432 (female)
Completed: 443 (female)
Completed: 444 (male)
Completed: 437 (male)
Completed: 443 (male)
Completed: 446 (female)

In [ ]:
(to_df['input_tokens'].sum() * 1.25) / 1000000

np.float64(0.94338625)

In [ ]:
(to_df['output_tokens'].sum() * 10) / 1000000

np.float64(10.15562)

# Harm Distribution Analysis

In [ ]:
def gpt_harm_eval(stimulus, actor, model="gpt-5", response=False):
    """
    Run harm evaluation questionnaire with GPT model for multiple relations.

    Parameters
    ----------
    stimulus : str
        Scenario description.
    actor : str
        The actor whose behavior is being judged.
    model : str
        Model name (default "gpt-5").
    response : bool
        If True, return raw API response; else parsed answers.
    """

    def make_client():
        openai.api_key = gpt_key
        return OpenAI(api_key=openai.api_key)

    client = make_client()

    # Inline prompt
    prompt = f"""
You are evaluating the moral and social harm of a behavior.

Scenario:
"{stimulus}"

The actor is: {actor}.

Please answer the following questions:

1. On a scale of 1–5, to what extent does {actor}’s behavior harm society as a whole?
2. On a scale of 1–5, to what extent does {actor}’s behavior harm their close family or friend?
3. On a scale of 1–5, to what extent does {actor}’s behavior harm their acquaintance?
4. On a scale of 1–5, to what extent does {actor}’s behavior harm a stranger?

Use only integer values from 1 to 5, where:
1 = not at all
2 = a little
3 = moderately
4 = a lot
5 = extremely
"""

    # JSON schema
    schema = {
        "type": "object",
        "properties": {
            "harm_society": {"type": "integer", "minimum": 1, "maximum": 5},
            "harm_family_friend": {"type": "integer", "minimum": 1, "maximum": 5},
            "harm_acquaintance": {"type": "integer", "minimum": 1, "maximum": 5},
            "harm_stranger": {"type": "integer", "minimum": 1, "maximum": 5}
        },
        "required": ["harm_society", "harm_family_friend", "harm_acquaintance", "harm_stranger"],
        "additionalProperties": False
    }

    # Call GPT with enforced schema
    resp = with_retries(
        lambda: client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            temperature=1 if model.startswith("gpt-5") else 0,
            max_completion_tokens=4096,
            response_format={
                "type": "json_schema",
                "json_schema": {
                    "name": "harm_eval_schema",
                    "schema": schema
                }
            }
        ),
        backend="gpt"
    )

    if response:
        return resp

    # Use parsed output if schema worked
    if hasattr(resp.choices[0].message, "parsed") and resp.choices[0].message.parsed:
        answers = resp.choices[0].message.parsed
    else:
        reply = resp.choices[0].message.content
        reply_clean = cleanup_json_string(reply)
        try:
            answers = json.loads(reply_clean)
        except json.JSONDecodeError:
            answers = json5.loads(reply)  # fallback

    usage_info = {}
    if hasattr(resp, "usage") and resp.usage:
        usage_info = {
            "input_tokens": getattr(resp.usage, "prompt_tokens", None),
            "output_tokens": getattr(resp.usage, "completion_tokens", None),
            "total_tokens": getattr(resp.usage, "total_tokens", None),
        }

    return {**answers, **usage_info}

In [ ]:
results = []
tasks = []
max_workers = 100  # adjust to your rate limit
print(f"Processing {len(df)} rows × 2 genders with max_workers={max_workers} using GPT")

def run_one(stim, row_id, gender, actor):
    try:
        answers = gpt_harm_eval(stim, actor, model="gpt-5")  # parsed + tokens
        out = {
            "ID": row_id,
            "stimuli": stim,
            "actor_gender": gender,
            "actor": actor
        }
        out.update(answers)  # flatten harm scores + tokens
        return out
    except Exception as e:
        print(f"Error with {row_id} ({gender}): {e}")
        return {
            "ID": row_id,
            "stimuli": stim,
            "actor_gender": gender,
            "actor": actor,
            "error": str(e)
        }

with ThreadPoolExecutor(max_workers=max_workers) as ex:
    for idx, row in df.reset_index(drop=True).iterrows():
        row_id = row["ID"]

        stim_m = row["stimuli-male"]
        stim_f = row["stimuli-female"]

        actor_m = row.get("norm-target in stimuli-male", None)
        actor_f = row.get("norm-target in stimuli-female", None)

        tasks.append(ex.submit(run_one, stim_m, row_id, "male", actor_m))
        tasks.append(ex.submit(run_one, stim_f, row_id, "female", actor_f))

    for fut in as_completed(tasks):
        res = fut.result()
        results.append(res)
        print(f"Completed: {res['ID']} ({res['actor_gender']})")

# Collect into dataframe
to_df = pd.DataFrame(results)

# Reorder columns
front_cols = ["ID", "actor", "stimuli", "actor_gender"]
token_cols = ["input_tokens", "output_tokens", "total_tokens"]
question_cols = [
    "harm_society",
    "harm_family_friend",
    "harm_acquaintance",
    "harm_stranger"
]
other_cols = [c for c in to_df.columns if c not in front_cols + token_cols + question_cols]

to_df = to_df[front_cols + question_cols + token_cols + other_cols]
to_df = to_df.sort_values("ID").reset_index(drop=True)

# Save
to_df.to_csv("gpt_harm_eval_responses.csv", index=False)
to_df.to_parquet("gpt_harm_eval_responses.parquet", index=False)
print("Done: responses saved.")

Processing 451 rows × 2 genders with max_workers=100 using GPT
Completed: 5 (female)
Completed: 25 (male)
Completed: 25 (female)
Completed: 4 (female)
Completed: 13 (female)
Completed: 26 (female)
Completed: 35 (male)
Completed: 26 (male)
Completed: 20 (male)
Completed: 47 (male)
Completed: 20 (female)
Completed: 4 (male)
Completed: 23 (female)
Completed: 18 (female)
Completed: 11 (female)
Completed: 5 (male)
Completed: 27 (male)
Completed: 14 (male)
Completed: 13 (male)
Completed: 18 (male)
Completed: 41 (female)
Completed: 37 (male)
Completed: 15 (female)
Completed: 32 (male)
Completed: 3 (female)
Completed: 32 (female)
Completed: 17 (male)
Completed: 16 (female)
Completed: 27 (female)
Completed: 14 (female)
Completed: 31 (male)
Completed: 21 (male)
Completed: 33 (male)
Completed: 24 (female)
Completed: 12 (female)
Completed: 7 (male)
Completed: 6 (female)
Completed: 21 (female)
Completed: 23 (male)
Completed: 34 (female)
Completed: 16 (male)
Completed: 40 (male)
Completed: 30 (female)
Completed: 41 (male)
Completed: 28 (female)
Completed: 47 (female)
Completed: 51 (male)
Completed: 45 (male)
Completed: 34 (male)
Completed: 29 (male)
Completed: 7 (female)
Completed: 50 (female)
Completed: 30 (male)
Completed: 8 (male)
Completed: 51 (female)
Completed: 55 (male)
Completed: 9 (female)
Completed: 2 (male)
Completed: 40 (female)
Completed: 15 (male)
Completed: 39 (male)
Completed: 54 (male)
Completed: 28 (male)
Completed: 31 (female)
Completed: 46 (male)
Completed: 56 (female)
Completed: 29 (female)
Completed: 59 (male)
Completed: 60 (male)
Completed: 63 (female)
Completed: 6 (male)
Completed: 39 (female)
Completed: 2 (female)
Completed: 24 (male)
Completed: 56 (male)
Completed: 12 (male)
Completed: 55 (female)
Completed: 37 (female)
Completed: 54 (female)
Completed: 68 (male)
Completed: 1 (male)
Completed: 46 (female)
Completed: 3 (male)
Completed: 53 (female)
Completed: 35 (female)
Completed: 38 (female)
Completed: 11 (male)
Completed: 17 (female)
Completed: 45 (female)
Completed: 38 (male)
Completed: 58 (male)
Completed: 22 (female)
Completed: 57 (male)
Completed: 1 (female)
Completed: 10 (male)
Completed: 67 (male)
Completed: 62 (male)
Completed: 83 (female)
Completed: 10 (female)
Completed: 19 (male)
Completed: 79 (female)
Completed: 49 (female)
Completed: 68 (female)
Completed: 33 (female)
Completed: 8 (female)
Completed: 52 (female)
Completed: 59 (female)
Completed: 42 (male)
Completed: 61 (female)
Completed: 69 (male)
Completed: 80 (male)
Completed: 71 (female)
Completed: 82 (female)
Completed: 65 (male)
Completed: 42 (female)
Completed: 80 (female)
Completed: 64 (female)
Completed: 52 (male)
Completed: 79 (male)
Completed: 76 (female)
Completed: 69 (female)
Completed: 62 (female)
Completed: 63 (male)
Completed: 49 (male)
Completed: 43 (female)
Completed: 87 (female)
Completed: 71 (male)
Completed: 90 (female)
Completed: 58 (female)
Completed: 88 (male)
Completed: 85 (female)
Completed: 87 (male)
Completed: 100 (female)
Completed: 94 (female)
Completed: 66 (male)
Completed: 100 (male)
Completed: 22 (male)
Completed: 103 (male)
Completed: 67 (female)
Completed: 61 (male)
Completed: 82 (male)
Completed: 97 (female)
Completed: 36 (male)
Completed: 95 (male)
Completed: 92 (female)
Completed: 70 (female)
Completed: 102 (female)
Completed: 94 (male)
Completed: 78 (female)
Completed: 73 (male)
Completed: 84 (male)
Completed: 83 (male)
Completed: 92 (male)
Completed: 64 (male)
Completed: 43 (male)
Completed: 76 (male)
Completed: 85 (male)
Completed: 74 (female)
Completed: 66 (female)
Completed: 97 (male)
Completed: 84 (female)
Completed: 101 (male)
Completed: 74 (male)
Completed: 102 (male)
Completed: 104 (male)
Completed: 96 (male)
Completed: 89 (male)
Completed: 70 (male)
Completed: 99 (female)
Completed: 89 (female)
Completed: 108 (male)
Completed: 93 (female)
Completed: 50 (male)
Completed: 103 (female)
Completed: 88 (female)
Completed: 77 (female)
Completed: 114 (male)
Completed: 60 (female)
Completed: 81 (male)
Completed: 90 (male)
Completed: 99 (male)
Completed: 86 (male)
Completed: 111 (female)
Completed: 48 (male)
Completed: 110 (male)
Completed: 115 (female)
Completed: 122 (male)
Completed: 109 (male)
Completed: 127 (male)
Completed: 96 (female)
Completed: 119 (male)
Completed: 127 (female)
Completed: 105 (female)
Completed: 122 (female)
Completed: 112 (male)
Completed: 112 (female)
Completed: 65 (female)
Completed: 78 (male)
Completed: 75 (male)
Completed: 117 (female)
Completed: 44 (male)
Completed: 111 (male)
Completed: 117 (male)
Completed: 9 (male)
Completed: 101 (female)
Completed: 77 (male)
Completed: 129 (female)
Completed: 115 (male)
Completed: 98 (male)
Completed: 120 (male)
Completed: 116 (female)
Completed: 95 (female)
Completed: 44 (female)
Completed: 118 (female)
Completed: 104 (female)
Completed: 53 (male)
Completed: 72 (female)
Completed: 108 (female)
Completed: 86 (female)
Completed: 130 (female)
Completed: 126 (female)
Completed: 114 (female)
Completed: 116 (male)
Completed: 106 (female)
Completed: 129 (male)
Completed: 48 (female)
Completed: 125 (female)
Completed: 131 (female)
Completed: 134 (female)
Completed: 131 (male)
Completed: 107 (female)
Completed: 75 (female)
Completed: 120 (female)
Completed: 137 (male)
Completed: 106 (male)
Completed: 93 (male)
Completed: 91 (male)
Completed: 140 (female)
Completed: 141 (male)
Completed: 126 (male)
Completed: 57 (female)
Completed: 110 (female)
Completed: 141 (female)
Completed: 148 (female)
Completed: 128 (female)
Completed: 145 (female)
Completed: 19 (female)
Completed: 145 (male)
Completed: 124 (female)
Completed: 107 (male)
Completed: 36 (female)
Completed: 142 (male)
Completed: 137 (female)
Completed: 134 (male)
Completed: 123 (male)
Completed: 119 (female)
Completed: 121 (female)
Completed: 113 (male)
Completed: 72 (male)
Completed: 146 (male)
Completed: 144 (male)
Completed: 132 (female)
Completed: 144 (female)
Completed: 132 (male)
Completed: 109 (female)
Completed: 73 (female)
Completed: 157 (female)
Completed: 149 (male)
Completed: 148 (male)
Completed: 118 (male)
Completed: 136 (male)
Completed: 150 (male)
Completed: 139 (female)
Completed: 135 (male)
Completed: 160 (female)
Completed: 123 (female)
Completed: 135 (female)
Completed: 146 (female)
Completed: 98 (female)
Completed: 133 (male)
Completed: 133 (female)
Completed: 105 (male)
Completed: 153 (male)
Completed: 151 (male)
Completed: 142 (female)
Completed: 150 (female)
Completed: 138 (female)
Completed: 165 (female)
Completed: 169 (female)
Completed: 168 (female)
Completed: 176 (male)
Completed: 157 (male)
Completed: 152 (male)
Completed: 171 (male)
Completed: 128 (male)
Completed: 158 (male)
Completed: 136 (female)
Completed: 143 (male)
Completed: 81 (female)
Completed: 143 (female)
Completed: 138 (male)
Completed: 180 (female)
Completed: 176 (female)
Completed: 158 (female)
Completed: 153 (female)
Completed: 155 (male)
Completed: 172 (male)
Completed: 147 (male)
Completed: 159 (male)
Completed: 140 (male)
Completed: 91 (female)
Completed: 154 (male)
Completed: 174 (female)
Completed: 113 (female)
Completed: 177 (female)
Completed: 156 (male)
Completed: 170 (female)
Completed: 166 (female)
Completed: 169 (male)
Completed: 172 (female)
Completed: 159 (female)
Completed: 155 (female)
Completed: 180 (male)
Completed: 178 (male)
Completed: 149 (female)
Completed: 179 (female)
Completed: 183 (male)
Completed: 168 (male)
Completed: 177 (male)
Completed: 171 (female)
Completed: 164 (female)
Completed: 164 (male)
Completed: 154 (female)
Completed: 125 (male)
Completed: 161 (male)
Completed: 166 (male)
Completed: 178 (female)
Completed: 170 (male)
Completed: 197 (male)
Completed: 152 (female)
Completed: 139 (male)
Completed: 147 (female)
Completed: 156 (female)
Completed: 121 (male)
Completed: 160 (male)
Completed: 165 (male)
Completed: 189 (male)
Completed: 183 (female)
Completed: 186 (male)
Completed: 189 (female)
Completed: 167 (male)
Completed: 185 (male)
Completed: 163 (male)
Completed: 182 (female)
Completed: 173 (female)
Completed: 195 (female)
Completed: 191 (male)
Completed: 161 (female)
Completed: 209 (male)
Completed: 167 (female)
Completed: 179 (male)
Completed: 209 (female)
Completed: 193 (female)
Completed: 187 (female)
Completed: 162 (female)
Completed: 195 (male)
Completed: 197 (female)
Completed: 188 (female)
Completed: 190 (female)
Completed: 151 (female)
Completed: 201 (female)
Completed: 192 (male)
Completed: 162 (male)
Completed: 203 (female)
Completed: 191 (female)
Completed: 124 (male)
Completed: 194 (female)
Completed: 203 (male)
Completed: 211 (female)
Completed: 173 (male)
Completed: 194 (male)
Completed: 175 (female)
Completed: 181 (female)
Completed: 163 (female)
Completed: 193 (male)
Completed: 207 (male)
Completed: 186 (female)
Completed: 207 (female)
Completed: 220 (male)
Completed: 205 (male)
Completed: 213 (female)
Completed: 202 (female)
Completed: 210 (female)
Completed: 185 (female)
Completed: 208 (male)
Completed: 227 (male)
Completed: 205 (female)
Completed: 218 (female)
Completed: 211 (male)
Completed: 200 (male)
Completed: 215 (female)
Completed: 220 (female)
Completed: 224 (male)
Completed: 214 (male)
Completed: 224 (female)
Completed: 210 (male)
Completed: 225 (male)
Completed: 223 (male)
Completed: 217 (male)
Completed: 225 (female)
Completed: 202 (male)
Completed: 232 (male)
Completed: 199 (male)
Completed: 237 (female)
Completed: 212 (female)
Completed: 206 (female)
Completed: 192 (female)
Completed: 238 (male)
Completed: 200 (female)
Completed: 227 (female)
Completed: 201 (male)
Completed: 198 (female)
Completed: 204 (male)
Completed: 188 (male)
Completed: 130 (male)
Completed: 234 (male)
Completed: 196 (female)
Completed: 204 (female)
Completed: 215 (male)
Completed: 190 (male)
Completed: 247 (male)
Completed: 206 (male)
Completed: 240 (male)
Completed: 247 (female)
Completed: 184 (male)
Completed: 216 (male)
Completed: 222 (female)
Completed: 175 (male)
Completed: 174 (male)
Completed: 223 (female)
Completed: 228 (male)
Completed: 233 (male)
Completed: 245 (male)
Completed: 241 (male)
Completed: 245 (female)
Completed: 182 (male)
Completed: 216 (female)
Completed: 252 (female)
Completed: 181 (male)
Completed: 217 (female)
Completed: 249 (female)
Completed: 239 (female)
Completed: 228 (female)
Completed: 229 (male)
Completed: 196 (male)
Completed: 235 (female)
Completed: 254 (male)
Completed: 249 (male)
Completed: 226 (male)
Completed: 214 (female)
Completed: 208 (female)
Completed: 184 (female)
Completed: 255 (female)
Completed: 237 (male)
Completed: 221 (female)
Completed: 251 (female)
Completed: 198 (male)
Completed: 236 (male)
Completed: 222 (male)
Completed: 251 (male)
Completed: 241 (female)
Completed: 238 (female)
Completed: 259 (male)
Completed: 236 (female)
Completed: 256 (female)
Completed: 219 (male)
Completed: 226 (female)
Completed: 212 (male)
Completed: 235 (male)
Completed: 259 (female)
Completed: 218 (male)
Completed: 260 (male)
Completed: 243 (male)
Completed: 258 (female)
Completed: 242 (female)
Completed: 257 (female)
Completed: 258 (male)
Completed: 274 (male)
Completed: 233 (female)
Completed: 272 (male)
Completed: 244 (female)
Completed: 244 (male)
Completed: 230 (male)
Completed: 256 (male)
Completed: 257 (male)
Completed: 234 (female)
Completed: 263 (female)
Completed: 272 (female)
Completed: 254 (female)
Completed: 231 (female)
Completed: 261 (female)
Completed: 275 (female)
Completed: 213 (male)
Completed: 230 (female)
Completed: 252 (male)
Completed: 260 (female)
Completed: 250 (female)
Completed: 279 (male)
Completed: 253 (male)
Completed: 248 (female)
Completed: 232 (female)
Completed: 229 (female)
Completed: 273 (male)
Completed: 281 (male)
Completed: 199 (female)
Completed: 280 (male)
Completed: 255 (male)
Completed: 271 (male)
Completed: 270 (male)
Completed: 219 (female)
Completed: 246 (male)
Completed: 278 (female)
Completed: 246 (female)
Completed: 270 (female)
Completed: 293 (female)
Completed: 243 (female)
Completed: 283 (female)
Completed: 269 (male)
Completed: 285 (male)
Completed: 265 (male)
Completed: 281 (female)
Completed: 267 (female)
Completed: 296 (male)
Completed: 262 (female)
Completed: 275 (male)
Completed: 287 (male)
Completed: 290 (male)
Completed: 265 (female)
Completed: 290 (female)
Completed: 273 (female)
Completed: 266 (female)
Completed: 250 (male)
Completed: 293 (male)
Completed: 248 (male)
Completed: 295 (male)
Completed: 266 (male)
Completed: 261 (male)
Completed: 288 (male)
Completed: 268 (female)
Completed: 280 (female)
Completed: 221 (male)
Completed: 288 (female)
Completed: 296 (female)
Completed: 276 (female)
Completed: 269 (female)
Completed: 304 (female)
Completed: 267 (male)
Completed: 294 (female)
Completed: 295 (female)
Completed: 240 (female)
Completed: 187 (male)
Completed: 242 (male)
Completed: 276 (male)
Completed: 284 (female)
Completed: 271 (female)
Completed: 282 (female)
Completed: 282 (male)
Completed: 278 (male)
Completed: 263 (male)
Completed: 303 (male)
Completed: 304 (male)
Completed: 283 (male)
Completed: 289 (female)
Completed: 299 (male)
Completed: 313 (male)
Completed: 316 (female)
Completed: 299 (female)
Completed: 316 (male)
Completed: 277 (female)
Completed: 301 (male)
Completed: 311 (male)
Completed: 308 (male)
Completed: 315 (female)
Completed: 253 (female)
Completed: 327 (male)
Completed: 287 (female)
Completed: 239 (male)
Completed: 277 (male)
Completed: 306 (male)
Completed: 303 (female)
Completed: 307 (male)
Completed: 315 (male)
Completed: 313 (female)
Completed: 306 (female)
Completed: 305 (female)
Completed: 284 (male)
Completed: 305 (male)
Completed: 324 (male)
Completed: 285 (female)
Completed: 310 (male)
Completed: 321 (male)
Completed: 326 (female)
Completed: 301 (female)
Completed: 274 (female)
Completed: 324 (female)
Completed: 320 (female)
Completed: 320 (male)
Completed: 264 (male)
Completed: 294 (male)
Completed: 318 (female)
Completed: 328 (male)
Completed: 298 (female)
Completed: 327 (female)
Completed: 302 (female)
Completed: 321 (female)
Completed: 326 (male)
Completed: 268 (male)
Completed: 308 (female)
Completed: 330 (female)
Completed: 279 (female)
Completed: 286 (female)
Completed: 314 (female)
Completed: 297 (female)
Completed: 298 (male)
Completed: 317 (female)
Completed: 331 (male)
Completed: 331 (female)
Completed: 343 (male)
Completed: 307 (female)
Completed: 322 (male)
Completed: 311 (female)
Completed: 309 (male)
Completed: 318 (male)
Completed: 325 (male)
Completed: 312 (female)
Completed: 349 (male)
Completed: 341 (female)
Completed: 332 (female)
Completed: 337 (male)
Completed: 344 (female)
Completed: 323 (female)
Completed: 329 (female)
Completed: 291 (female)
Completed: 335 (male)
Completed: 314 (male)
Completed: 289 (male)
Completed: 356 (female)
Completed: 350 (male)
Completed: 310 (female)
Completed: 322 (female)
Completed: 262 (male)
Completed: 264 (female)
Completed: 347 (female)
Completed: 347 (male)
Completed: 339 (female)
Completed: 335 (female)
Completed: 300 (female)
Completed: 323 (male)
Completed: 355 (female)
Completed: 332 (male)
Completed: 364 (female)
Completed: 353 (female)
Completed: 333 (female)
Completed: 333 (male)
Completed: 334 (female)
Completed: 352 (male)
Completed: 337 (female)
Completed: 355 (male)
Completed: 341 (male)
Completed: 359 (female)
Completed: 330 (male)
Completed: 345 (female)
Completed: 364 (male)
Completed: 328 (female)
Completed: 356 (male)
Completed: 360 (female)
Completed: 338 (female)
Completed: 360 (male)
Completed: 346 (male)
Completed: 297 (male)
Completed: 291 (male)
Completed: 366 (male)
Completed: 353 (male)
Completed: 349 (female)
Completed: 343 (female)
Completed: 348 (female)
Completed: 354 (male)
Completed: 340 (female)
Completed: 345 (male)
Completed: 292 (female)
Completed: 352 (female)
Completed: 357 (female)
Completed: 370 (female)
Completed: 361 (female)
Completed: 319 (male)
Completed: 342 (female)
Completed: 350 (female)
Completed: 339 (male)
Completed: 359 (male)
Completed: 309 (female)
Completed: 351 (female)
Completed: 329 (male)
Completed: 357 (male)
Completed: 325 (female)
Completed: 368 (female)
Completed: 336 (female)
Completed: 336 (male)
Completed: 300 (male)
Completed: 362 (male)
Completed: 351 (male)
Completed: 319 (female)
Completed: 365 (male)
Completed: 366 (female)
Completed: 365 (female)
Completed: 338 (male)
Completed: 368 (male)
Completed: 346 (female)
Completed: 378 (female)
Completed: 358 (female)
Completed: 387 (male)
Completed: 375 (male)
Completed: 292 (male)
Completed: 348 (male)
Completed: 394 (male)
Completed: 388 (male)
Completed: 382 (male)
Completed: 340 (male)
Completed: 377 (female)
Completed: 231 (male)
Completed: 369 (female)
Completed: 312 (male)
Completed: 387 (female)
Completed: 376 (male)
Completed: 334 (male)
Completed: 370 (male)
Completed: 378 (male)
Completed: 385 (male)
Completed: 395 (male)
Completed: 369 (male)
Completed: 377 (male)
Completed: 397 (female)
Completed: 361 (male)
Completed: 344 (male)
Completed: 399 (female)
Completed: 363 (male)
Completed: 396 (male)
Completed: 379 (female)
Completed: 389 (female)
Completed: 317 (male)
Completed: 383 (male)
Completed: 394 (female)
Completed: 358 (male)
Completed: 375 (female)
Completed: 354 (female)
Completed: 372 (female)
Completed: 382 (female)
Completed: 402 (male)
Completed: 371 (female)
Completed: 374 (female)
Completed: 400 (female)
Completed: 367 (female)
Completed: 376 (female)
Completed: 367 (male)
Completed: 386 (female)
Completed: 342 (male)
Completed: 379 (male)
Completed: 407 (male)
Completed: 413 (male)
Completed: 393 (female)
Completed: 385 (female)
Completed: 406 (female)
Completed: 391 (male)
Completed: 381 (female)
Completed: 408 (female)
Completed: 397 (male)
Completed: 412 (female)
Completed: 380 (female)
Completed: 399 (male)
Completed: 396 (female)
Completed: 400 (male)
Completed: 408 (male)
Completed: 374 (male)
Completed: 398 (female)
Completed: 409 (female)
Completed: 392 (female)
Completed: 405 (male)
Completed: 372 (male)
Completed: 384 (male)
Completed: 415 (male)
Completed: 424 (male)
Completed: 406 (male)
Completed: 412 (male)
Completed: 373 (male)
Completed: 390 (male)
Completed: 390 (female)
Completed: 386 (male)
Completed: 428 (male)
Completed: 402 (female)
Completed: 415 (female)
Completed: 389 (male)
Completed: 409 (male)
Completed: 363 (female)
Completed: 393 (male)
Completed: 388 (female)
Completed: 417 (male)
Completed: 429 (female)
Completed: 404 (male)
Completed: 424 (female)
Completed: 404 (female)
Completed: 420 (female)
Completed: 384 (female)
Completed: 373 (female)
Completed: 362 (female)
Completed: 392 (male)
Completed: 380 (male)
Completed: 433 (female)
Completed: 286 (male)
Completed: 433 (male)
Completed: 403 (male)
Completed: 401 (male)
Completed: 411 (male)
Completed: 381 (male)
Completed: 432 (female)
Completed: 405 (female)
Completed: 437 (male)
Completed: 371 (male)
Completed: 434 (male)
Completed: 416 (female)
Completed: 425 (male)
Completed: 444 (male)
Completed: 451 (male)
Completed: 440 (female)
Completed: 436 (male)
Completed: 423 (male)
Completed: 449 (female)
Completed: 410 (male)
Completed: 418 (female)
Completed: 437 (female)
Completed: 411 (female)
Completed: 435 (female)
Completed: 418 (male)
Completed: 421 (female)
Completed: 407 (female)
Completed: 421 (male)
Completed: 429 (male)
Completed: 430 (male)
Completed: 439 (male)
Completed: 444 (female)
Completed: 401 (female)
Completed: 417 (female)
Completed: 419 (male)
Completed: 434 (female)
Completed: 419 (female)
Completed: 449 (male)
Completed: 427 (male)
Completed: 422 (male)
Completed: 410 (female)
Completed: 414 (female)
Completed: 427 (female)
Completed: 430 (female)
Completed: 416 (male)
Completed: 422 (female)
Completed: 423 (female)
Completed: 391 (female)
Completed: 414 (male)
Completed: 445 (female)
Completed: 403 (female)
Completed: 451 (female)
Completed: 428 (female)
Completed: 413 (female)
Completed: 443 (male)
Completed: 436 (female)
Completed: 425 (female)
Completed: 432 (male)
Completed: 395 (female)
Completed: 426 (female)

,ID,actor,stimuli,actor_gender,harm_society,harm_family_friend,harm_acquaintance,harm_stranger,input_tokens,output_tokens,total_tokens
0,1,Maria,Maria did not tell someone's girlfriend that h...,female,2,1,3,1,234,809,1043
1,1,William,William did not tell someone's girlfriend that...,male,2,4,1,1,234,745,979
2,2,Mary,Mary rarely talks to her elderly roommates and...,female,1,1,2,1,243,681,924
3,2,John,John rarely talks to his elderly roommates and...,male,1,1,3,1,243,617,860
4,3,Robert,Robert stayed up until 5 am because he assumed...,male,1,2,1,1,241,745,986
...,...,...,...,...,...,...,...,...,...,...,...
897,449,Richard,Richard reads things in a British accent even ...,male,1,1,1,1,234,361,595
898,450,Elizabeth,Elizabeth touched a passed-out guy inappropria...,female,4,5,5,5,232,553,785
899,450,Charles,Charles touched a passed-out girl inappropriat...,male,4,5,5,5,232,873,1105
900,451,David,David smells his socks and underwear every tim...,male,1,1,1,1,240,169,409
901,451,Linda,Linda smells her socks and underwear every tim...,female,1,1,1,1,240,361,601

In [ ]:
(to_df['input_tokens'].sum() * 1.25) / 1000000

np.float64(0.26698625)

In [ ]:
(to_df['output_tokens'].sum() * 10) / 1000000

np.float64(4.29558)